### ISSUE TITLE
Toast notifications are stacking

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1010]
![image](https://user-images.githubusercontent.com/35497731/72374611-3d6ef200-36d0-11ea-8542-ac2028ad6a49.png)

Try stacking vertically and possibly clearing in some cases.

**Comment by marsmith** [comment]
I'm not sure about this one.  From reading the documentation this shouldn't be happening.  I'll dig into it a bit more but may need to pass to mitch.   toast library: https://github.com/jirikavi/AngularJS-Toaster

**Comment by marsmith** [comment]
Passing this on to @mitch-wim ... it looks like the odd behavior is coming from some CSS overrides in the main.css.  For example, we have a global setting of : `'close-button': false` but its still showing the close button for all toasts.  And I think the CSS is also responsible for stacking the toasts, as this is not default behavior of this plugin

**Comment by amedenblik** [comment]
This doesn't seem to be an issue anymore

![image](https://user-images.githubusercontent.com/40237491/173835528-5a6356cd-3383-435d-8175-d238d3379d4a.png)
