### ISSUE TITLE
Test application report warning message

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats#1024]
Add a warning or watermark or other notification in the reports coming from the test application that this is a development version, not for public consumption, etc. Currently, a report could be created from the test application and I can't tell that it is using test data, etc.

**Comment by marsmith** [comment]
Added message at bottom of report 
![image](https://user-images.githubusercontent.com/6529123/80618182-fd2e4800-8a10-11ea-8d71-0f5f31a85e80.png)
