### ISSUE TITLE
Archival/glacial storage of production data/application

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats#1025]
Create an archival process for the production data/machine for migrations

**Comment by amedenblik** [comment]
Data: The S3 streamstats-raw-data bucket and S3 streamstats-staged-data bucket already have version control enabled. When a file is updated in the S3 streamstats-raw-data bucket or S3 streamstats-staged-data bucket, the previous version is placed into glacier storage. Therefore, all previous version of all files are in glacier storage. We did discover that the streamstats-raw-data bucket is not being updated by the GIS team as expected, so we will review the [GIS Development Workflow](https://doimspp.sharepoint.com/:w:/r/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc=%7B13DFB0C3-02B0-453E-BE38-31E067FB937F%7D&file=GIS%20Development%20Workflow%20Documentation.docx&action=default&mobileredirect=true&cid=1a2e1287-93af-4cbc-90a9-967425db12b4&CID=a8ce0364-8637-c763-2c94-dd2f3013139d) with them at our next meeting.

Applications: archived already in existing GitHub/GitLab release workflows.
