### ISSUE TITLE
Basin editing issue 

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#1030]
We have an issue where the delineated basin polygon geometry has some issue where adding or removing edit polygons throws a topology error in the console: `found non-noded intersection between LINESTRING` .    Example delineation in ohio shows the error: 41.55993, -83.86761.

**Comment by kjacobsen16** [comment]
@marty reopening this, I'm seeing this issue in another area found by the same user with the first issue.

There's a disconnection of the stream grid downstream from 41.4783857, -83.8293846 at a ditch, so basins upstream of that disconnection are cut off. I can add new items if I delineate just above the ditch at that point, but if I go further upstream (41.48998, -83.80676) and try to add, I get the topology error (see image below).
![image](https://user-images.githubusercontent.com/35497731/83194904-01787e80-a0ff-11ea-91a4-0526c6d5f993.png)

**Comment by kjacobsen16** [comment]
Also worth noting here - I tried to edit several basins in ND and MN and got the same error. I found a point in NY and it worked fine. I wonder if this is a locational issue.

**Comment by marsmith** [comment]
Consider rolling back latest changes on basin editing as it seems like my changes created more issues.  Also, there is still an issue with basin edit ordering on the back end, after the problematic front end edits are submitted.  Possibly respond to the user that 'this is more complicated than we thought.'
