### ISSUE TITLE
QPPQ Questions to Answer By 6/2 Meeting

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1032]
Making this an issue so I don't forget:
1. On development site (or StreamEst) what record is used to construct the ref gage FDC? Prefer to use published FDC statistics but continue to pull dynamically to get ref gage hydrograph. *Note* this is something we discussed, and IL/IN want to use published statistics for QPPQ.

2. How are flow quantiles extrapolated and interpolated? Log-linear or Log-probability? 

3. How are zero flows at a selected ref gage handled? Is a censored flow value used in order to compute an exceedance probability or is the ref gage considered not available those days?

**Comment by HansVraga** [comment]
I think we can close this?

**Comment by kjacobsen16** [comment]
Yes, but I think we got some new questions last time we should look into.
