### ISSUE TITLE
National layers issues

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1035]
We have two national services:
![image](https://user-images.githubusercontent.com/35497731/83297662-94c1ba80-a1b8-11ea-9bc0-0d0d63cdfe4e.png)
We need to:
- [x] republish the nationalLayers service to make sure it's up to date

- [x]  Switch to `nationalLayers` in the app 

- [x] Make sure gage clicks and other functions using the national layers are working

- [x] Delete `nationalLayer` once ☝️ that's done

**Comment by kjacobsen16** [comment]
Alright @marsmith the `nationalLayers` service is updated and should be good to go now 👍

**Comment by marsmith** [comment]
OK, I updated appconfig and tested in the app seems to be good

**Comment by harper-wavra** [comment]
Stopped `nationalLayer` servcies, if no errors arise over this week I will delete next week.
