### ISSUE TITLE
Create gage page modal

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#1040]
Leverage new gage stats services (examples: 
https://test.streamstats.usgs.gov/gagestatsservices/stations/552
    https://test.streamstats.usgs.gov/gagestatsservices/stations/05301200
)

**Comment by HansVraga** [comment]
Example of the existing gage pages https://streamstatsags.cr.usgs.gov/gagepages/html/03572210.htm

**Comment by kjacobsen16** [comment]
@marsmith Pete asked if we can allow a user to filter the statistics shown in the gage pages by statistic group. Can you set that up on the client side? Also, are we displaying the statistic group for the statistics (I know characteristics don't have groups)?

**Comment by kjacobsen16** [comment]
Another ask - add options for "Include all reported statistics" or "include all preferred statistics" (hides stats with IsPreferred = false)

We'll be making these changes in the gagestats management client as well, so whoever gets to it first could share code to speed things up
