### ISSUE TITLE
Gage modal - query NWIS for period of Record

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#1041]
When we pull our gage statistic collection report we are pulling data from the station table that includes the Period of Record. We should be querying NWIS for this information rather than our local database because our local database doesn't frequently get updated.

Example from NWIS - https://waterdata.usgs.gov/mt/nwis/inventory/?site_no=12324590&agency_cd=USGS
Example Data collection report link - https://streamstatsags.cr.usgs.gov/gagepages/html/12324590.htm
![image](https://user-images.githubusercontent.com/12058013/86613734-9e88cb80-bf77-11ea-8cbe-84dcb1c05a6c.png)

**Comment by amedenblik** [comment]
Closing in favor of #1073
