### ISSUE TITLE
Return exclusion polygon ID

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1064]
>can we return the exclusion poly ID with the delineation? 

Not sure if this is a services issue or client issue

**Comment by amedenblik** [comment]
Closing this in favor of work being done in https://code.usgs.gov/StreamStats/web-services-and-apis/ss-delineate/ and https://code.usgs.gov/StreamStats/web-services-and-apis/ss-pourpoint. This doesn't seem like a client issue.
