### ISSUE TITLE
Export to KML/KMZ 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#1067]
Feature request from cooperator: Export to KML/KMZ
```
We often use the feature to export the delineated watersheds for use in GIS – shape files & Geo JONS (?)

Could we add an option to get output in KML/KMZ? This would be wildly popular. In particular, we could then load directly into our DOT mapviewer.

Thanks

Charlie

Charles Hebson, P.E.

MaineDOT / Environmental Office

State House Station 16

Augusta ME 04333-0016

207.557.1052
```

**Comment by HansVraga** [comment]
Didn't look like this is a leaflet feature out of the box.

However, initial googling suggests there is a plug-in for doing this conversation from GeoJSON.

**Comment by kjacobsen16** [comment]
Looks like this library might do it https://www.npmjs.com/package/tokml

**Comment by marsmith** [comment]
I have used that package, its great: https://github.com/marsmith/305b-mapper/blob/master/src/scripts/app.js#L543-L557

**Comment by kjacobsen16** [comment]
Nice, thanks @marsmith!
