### ISSUE TITLE
Add Monthly backups of SS postgres RDS instances

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1068]
https://github.com/USGS-WiM/wim-infrastructure/blob/master/scripts/wim/aws/wim_rds_backups_monthly.py

While in there, widen the "keep range" of the daily backups to 35 days

**Comment by kjacobsen16** [comment]
Notes here from infrastructure call w/ Aaron: https://doimspp.sharepoint.com/:w:/r/sites/GS-UMidWIM/_layouts/15/doc.aspx?sourcedoc=%7B595db923-f1d1-4527-be06-a77868412d60%7D&action=edit&cid=c36929ef-c228-4d7b-8734-8f9641684c2c&CID=33a116da-40e9-c684-73a1-74708713a035

Also can do https://github.com/USGS-WiM/NSSServices/issues/183 around same time

**Comment by amedenblik** [comment]
@harper-wavra do you think this can be closed? I believe we have backups covered

**Comment by harper-wavra** [comment]
I think we are good to close.
