### ISSUE TITLE
Additional NWIS info - Gage page

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1073]
Check if NWIS has the:

- [x]  Period of record
- [ ]  Years of Record

And include them in the Gage Page if so

**Comment by kjacobsen16** [comment]
This should be done the same as https://github.com/USGS-WiM/NSS/issues/436. We are already querying the period of record for QPPQ so the url is in our appConfig: https://github.com/USGS-WiM/StreamStats/blob/dev/src/appConfig.js#L33

**Comment by Abigail770** [comment]
I followed what was in QPPQ to add the NWIS period of record.  I didn't see Years of Record in the NWIS documentation at all.  What's the difference between period of record and years of record (maybe there's an alternative name for years of record in NWIS)?

**Comment by amedenblik** [comment]
Talked to Pete M and he says that adding just Period of Record is fine!
