### ISSUE TITLE
Add software version(s) to About tab

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats#1076]
Add an about tab for application versioning and/or updates. Could possibly put in the "Disclaimers" tab. 

If we keep a good list of fixes or updates for each version we can list those in the about tab too. 
![image](https://user-images.githubusercontent.com/16928289/111335867-59568680-863a-11eb-8539-ac23b712e318.png)

**Comment by amedenblik** [comment]
Pete will add notes about our updates as a news item when we have major or minor releases. I have added "provide notes for news item if applicable" to the migration template/checklist.
