### ISSUE TITLE
QPPQ Remaining Enhancements

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1078]
From cooperator:
- [x] Add option to enter gage number
- [ ] (awaiting more from Mackenzie/Amy) limit gage selection in IL/IN to gages in approved list
- [x]  Allow use of MM/DD/YYYY format in choosing dates
- [ ]  Doing this over a year takes a fair bit longer to build the report - from Jeremy "this has to do with optimizing the retrieval to NWIS flow data. If you select over 2+ yrs of data, it'll slow down the response. I didn't have much time to look into it, I'm guessing it might be client side loading of the timeseries (but it could also be the query/processing of the data server side as well)"
- [x] There is no way to simply exit out of the FDCTM window without either accepting the current reference gage "x Ok" or "Select from Map" which will take you back to the map, where you can then access options in the side panel if desired.
If you have no reference gage selected, "x Ok" won't allow you to exit. Maybe a simple x in the upper corner?
   - maybe add a "cancel" button but it goes back to the scenario selection
   - or maybe we should change the FDCTM window to show up when the user clicks a "configure" button (like TOT)

From KJ:
- [x] Edit nearest gages to not get geojson object, can remove the use of the "properties" object and just get the properties directly (see TODO in getGageInfo())
- [ ] GagePage - remove extra calls for things that are now returned
- [ ] Check TODOs
- [x] Report print needs Mitch help
- [ ] Do we need to notify if gage is upstream or downstream
- [ ] (bigger task) Display correlation for the nearest gages?

**Comment by kjacobsen16** [comment]
@harper-wavra This issue was my running list of enhancement issues for QPPQ. At the time, most of these were optional, and some of the items at the bottom were added by me as more code cleanup/potential enhancements, but the ones that the WSC wants are:

- [ ] take list of gages from the krig services correlation matrix and only allow users to select gages from that list as a reference gage
- [ ] Use Flow Duration Curve Transfer Method or FDCTM rather than QPPQ, and add additional info somewhere saying "also known as QPPQ"
- [ ] See if we can get a distance from the target location to the index gage
    - we might need to see an external library like turf.js or something else to get a distance between two lat/longs
- [ ] Check response coming from NLDI service failures to make sure it notifies properly when it's an NLDI service failure
    - if you need to edit the error text, you'll need to do so in the gagestats services, which make calls to NLDI to get the nearest gages on network
- [ ] change anywhere it says "reference gage" to "index gage"
- [ ] See how long it would take to display whether the gage is upstream or downstream
    - This would also be in the gagestatsservices - I started looking into this at one point - I'll see if I have any changes locally for this when I'm fully back in
-  [ ] This wasn't talked about in this meeting but the last one - they have multivariable regions that have flow duration equations for IL/IN. We removed the polygons because we didn't have the review v. approved status yet. We should get those polygons added back into the DB and make sure the equations are marked as review for now
    - you can check with Ryan to see if he has those. Otherwise, I may have them around somewhere

Note that they will likely have some report changes coming and they're planning to come back with new text to explain what distance on network means.

You can add separate issues for these as well, but figured I'd add them here since some of them were mentioned above.

**Comment by harper-wavra** [comment]
Closing in favor of issue #1152
