### ISSUE TITLE
MN Bridges Popup Issue

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1099]
This is inconsistent, but if you open the app, zoom to Level 16, select Minnesota, then click on bridges, the popup will frequently show up like this:
![image](https://user-images.githubusercontent.com/35497731/114052783-f67c9780-9853-11eb-852d-7bace83b3f4e.png)

**Comment by amedenblik** [comment]
I have not been able to recreate this issue.

**Comment by amedenblik** [comment]
This was probably fixed with #1172. I clicked 100 bridges in MN and did not encounter the issue. Closing the issue.
