### ISSUE TITLE
Add print button to new gage page modal

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1109]

**Comment by kjacobsen16** [comment]
This should be done the same as https://github.com/USGS-WiM/NSS/issues/418. The gage page modal is shown by zooming in past zoom level 8 so you can see gages, clicking on one, and clicking on the "New StreamStats Gage Modal" link 
![image](https://user-images.githubusercontent.com/35497731/117069370-01f79d00-acf2-11eb-8cbf-26645c8c1025.png)

**Comment by Abigail770** [comment]
It looks like other print buttons in SS have analytics attached to them:
Report: `analytics-on analytics-event="Print" analytics-category="Report" analytics-label="Print"`
Exploration: `analytics-on analytics-event="Print" analytics-category="Map" analytics-label="elevationProfilePrint"`
Should I add analytics? What category/label should I use?

**Comment by amedenblik** [comment]
Let's use `analytics-on analytics-event="Print" analytics-category="GagePage" analytics-label="gagePagePrint"`
