### ISSUE TITLE
QPPQ Modal Styling Fixes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1122]
The QPPQ modal has a table to list the reference gage options, but it doesn't show up well on smaller screens
![image](https://user-images.githubusercontent.com/35497731/119188328-1fda3700-ba40-11eb-99e6-beffbc4495b6.png)

I have my most recent edits in progress in branch KJ-1050, but you can also pull in dev - you will just have to edit the app.config to add "FDCTM" to the "Applications" array for Illinois to test it.

To replicate:
1. Delineate a point in Illinois
2. Continue to the "Select Scenarios" step
3. Select "Flow-Duration QPPQ Method"
4. Hit "Continue"
5. In the modal, select "Query Nearest Gages", hit "Go" (if nothing comes back, increase the distance)

I tried using the `col-xs-x` classes but :nodice:

**Comment by mitchas** [comment]
Should be fixed - I shrunk it a bit and made it scroll horizontatlly.
I also added another CSS break point for modals so they take up more screen width on smaller screens instead of having the wasted space on the sides.

**Comment by kjacobsen16** [comment]
Nice! This looks much better, thanks!
