### ISSUE TITLE
Fix removeGeoJson() function in MapController

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1125]
None of the geojson layers are being removed from the legend when the removeGeoJson() function in the MapController is called.

This is called when a basin is cleared, so can cause some confusion when a basin is cleared if those items aren't on the map. This is especially confusing with the Non-simplified basin, since some basins don't need simplification and don't have a non-simplified polygon to display.
![image](https://user-images.githubusercontent.com/35497731/124295188-2c14e200-db1e-11eb-8152-53027dccd6d8.png)

To recreate:
1. Delineate at 18.44253, -66.36785 in Puerto Rico. You'll receive a warning that the app is displaying a simplified basin. The Non-Simplified basin should show up in the legend under "Application Layers" unchecked. If you toggle it on, you should see a red polygon covering the basin.
![image](https://user-images.githubusercontent.com/35497731/124295630-b0fffb80-db1e-11eb-98ad-5a40dfa711f9.png)

2. Hit the "Clear Basin" option in the sidebar
![image](https://user-images.githubusercontent.com/35497731/124295657-b8270980-db1e-11eb-9ea4-6c75730dc431.png)

3. Check the Legend - you should still see the non-simplified basin, basin and click point in there even though they're not on the map
![image](https://user-images.githubusercontent.com/35497731/124295700-c412cb80-db1e-11eb-81f8-0ab7aa26b9a5.png)

4. Delineate at 18.35679, -66.34300. The non-simplified basin layer will still be checked in the legend, but if you toggle it off/on, nothing shows up because the basin is small enough that it isn't simplified and therefore does not have a non-simplified basin option.
![image](https://user-images.githubusercontent.com/35497731/124295817-e4428a80-db1e-11eb-80bd-5ce10926c98a.png)
5. Clear basin again and delineate at 18.34899, -66.47179. This time, there is a non-simplified basin but the toggle is on, so it looks like there isn't one. If you toggle the non-simplified basin off/on again in the legend, you'll see the non-simplified basin.
![image](https://user-images.githubusercontent.com/35497731/124296595-c1fd3c80-db1f-11eb-8b34-ede6ed4fe92c.png)

**Comment by harper-wavra** [comment]
Should be able to close after https://github.com/USGS-WiM/wim_angular/pull/113 is merged.

**Comment by amedenblik** [comment]
Fixed with https://github.com/USGS-WiM/wim_angular/pull/113
