### ISSUE TITLE
Update SS USGS web page to point to new stat labels web page

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1147]
Also from my backlog of emails I've kept tabs on. Once Tara is done with the current TOT updates, we'll want her to update the links to the BCs and flow stat labels to point to the new page at https://streamstats.usgs.gov/statistic-labels/ (which uses our services instead of a statistic page).

It's currently linked to https://www.usgs.gov/atom/50557

**Comment by amedenblik** [comment]
Issue resolved. The text "Definitions of basin characteristics and streamflow statistics that appear in StreamStats outputs" on http://streamstats.usgs.gov/ correctly links to https://streamstats.usgs.gov/statistic-labels/.
