### ISSUE TITLE
Add additional functionality to gage pages

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1148]
From John [(at bottom of 7/9 meeting notes):](https://doimspp.sharepoint.com/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc={3db134d6-2d7c-49a3-9d03-8bc1b11e7f5b}&action=edit&wd=target%28Bimonthly%20Meetings.one%7C1b5f17b3-7a5d-4a94-a4ce-36e48aae7711%2F2021-07-09%7C150ac2d5-2ffa-419a-8365-f84bdbf3e713%2F%29)

- Some gages have links to special text output files (Curtis Weaver) https://streamstatsags.cr.usgs.gov/gagepages/html/02097517.htm 
    - Iowa has something similar 
- SIMS gage information (Pete will check with Daniel Pearson  
- John will put everything on DEV machine 
- Script to add the extra info:  on dev, D:\web\common\js\getGPageOtherInfo.js 
    - Need to be sure the URLs are pointing correctly 
- SIMSbaseURL = 'https://streamstatsags.cr.usgs.gov/SimsService/SIMSservice.asmx/GetSIMSXml'; 
    - NOTE: Not working - JDG - 7/11/2021 
- NCbaseURL = '/NC_gagePages/'; 
- Web server virtual directory on dev: D:\web\NC_gagePages20150403 
    - https://dev.streamstats.usgs.gov/NC_gagePages/Sta_02077240_daily_discharge_percentiles_table_by-wateryears.txt 
    - https://dev.streamstats.usgs.gov/NC_gagePages/Sta_02077240_daily_discharge_percentiles_table_by-day-month-seasonal.txt 
    - IAbaseURL = '/IA_gagePages/'; 
- Web server virtual directory on dev : D:\web\IA_gagePages20170420 
    - https://dev.streamstats.usgs.gov/IA_gagePages/05388500_stats.pdf 
- gagePages that call these: 
    - Web server virtual directory on dev : D:\web\gagePagesSample 
    - https://dev.streamstats.usgs.gov/gagepages/html/

**Comment by harper-wavra** [comment]
Made new issues with more information, #1323 and #1285
