### ISSUE TITLE
Update D:\ folder setup on the Dev server

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats#1149]
(not SS client related)

John reordered his Batch processor code on his other servers, so we'll need to replicate it on the dev server (or ask him to) if he hasn't already.

This essentially was a request of mine so that all the BatchProcessor items on the D: server are under D:\BatchProcesser so we know where to look for BP-related things. Currently there are multiple folders used by the BatchProcessor, including D:\scripts, D:\web, and D:\RegionPolys (maybe more).

**Comment by amedenblik** [comment]
This issue seems outdated, given past server changes and upcoming BP changes. Closing, but please let me know if anything thinks this should be reopened.
