### ISSUE TITLE
Display SEP and Equation Weighting

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1161]
After [NSSService Issue 263](https://github.com/USGS-WiM/NSSServices/issues/236) is complete and
Seths weighting code is edited we need to:

- [ ] Print SEP (Si) in the report
- [ ] Send SEP (Si) to Seth's weighting code and get a response
- [ ] From the response for Seth's code display results like below:

Add a section at the bottom of the report ("Methods Weighting"): with Q (10^Z), units, PIl (Prediction Interval-Lower), PIu (Prediction Interval-Upper), and SEP
![image](https://user-images.githubusercontent.com/40237491/157499098-7a7379a2-7674-42d2-8718-776288df918b.png)

CI = 1.64*SEP
PIU = 10^(Z+CI)
PIL = 10^(Z-CI)

**Comment by amedenblik** [comment]
Seth's weighting code is now here: https://github.com/USGS-WiM/ss-weightingservices

**Comment by harper-wavra** [comment]
If `paramsOutOfRange` is true we send back `Errors`, `EquivalentYear`, `IntervalBounds` and `SEP` back as null with error message 'One or more of the parameters is outside the suggested range. Estimates were extrapolated with unknown errors. '. We should ask Pete (@USGSPMM3) if we want to send SEP back even if this happens.

https://github.com/USGS-WiM/NSSServices/blob/dev/NSSAgent/NSSAgent.cs#L727
Example point: 46.64627, -106.86841
