### ISSUE TITLE
January 2022 Migration 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1162]
GitHub issue checklist: 

Use the migration document [here](https://doimspp.sharepoint.com/:w:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B545482F7-D3E5-45B1-A81F-F3D6140E2A46%7D&file=StreamStats%20Cloud%20Migration.docx&action=default&mobileredirect=true).  

 

Before migration: 

- [x] Ensure all expected updates are listed in the [Migrations section](https://doimspp.sharepoint.com/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc={3db134d6-2d7c-49a3-9d03-8bc1b11e7f5b}&action=edit&wd=target%28Migrations.one%7Ca7c80c4a-4ff8-46c3-8122-e38fae74a8dc%2F%29&wdorigin=717) in StreamStats OneNote. Contact the listed contact person if there are any questions.
- [x] Check any new data in E:\data\ to ensure it is cleaned up.
- [x] Clean up any test data in the databases so when we update it goes as smoothly as possible.
- [x] Run:
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest) 
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/) 

 

Migration checklist:  

- [x] 1) Turn Off TestWeb  
- [x] 2) Snapshot existing TestWeb  
- [x] 3) Create 2 ProdWeb(a&b)-new EC2 instances from TestWebSnapshot  
- [x] 4) Update config files on prod services  
- [x] 5) Test the ArcGIS desktop licenses on ProdWebA and ProdWebB  
- [x] 6) Test the services 
- [x] 7) Point prod load balancer to new prod web machines  
- [x] 8) Reassign Elastic IP addresses from old to new prod web machines  
- [x] 9) Turn on TestWeb 
- [x] 10) ~~(if needed) Update StateServices map service~~
- [x] 11) ~~Update the EC2 instance reference in the S3:ss-lambda/prod_scale_ec2_instances_ids.txt, and sandbox_start_ec2_instances_ids.txt and sandbox_stop_ec2_instances_ids.txt files~~
- [x] 12) (if needed) Update Databases (StreamStats and NSS) 
- [x] 13) Run: 
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest) 
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/) 
- [x] 14) Once you’ve confirmed the migration has gone well (3 business days later):  
    - [x] Terminate old ProdWebA, ProdWebB machines  
    - [x] Delete their attached data volumes (the 1800GB data drives)   

Additional items:
- [x] Update test GageStatsServices
- [x] Update test NSSServices
- [x] Update production KrigServices

**Comment by amedenblik** [comment]
Updates with this migration:

- WV: updated XML, updated region polygons
- NSSServices on Test was updated ([see changes here](https://github.com/USGS-WiM/NSSServices/pull/244))
- GagestatsServices on Test was updated ([see changes here](https://github.com/USGS-WiM/GageStatsServices/pull/115)) 
- KrigServices on Prod was updated
