### ISSUE TITLE
Add additional flow statistics warning

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1168]
This feature may already exist. From [SC StreamStats Phase II proposal](https://doimspp.sharepoint.com/sites/SSPhaseII/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FSSPhaseII%2FShared%20Documents%2FGeneral%2FProposal%2FSC%5FStreamStats%5FPhase%5FII%5FProposal%5FFinal%2Epdf&parent=%2Fsites%2FSSPhaseII%2FShared%20Documents%2FGeneral%2FProposal):

**Additional Flow Statistics Warning**

A warning(s) will be added and displayed in the flow statistics report if specified thresholds are reached for a specified National Streamflow Statistics regression region (Turnipseed and Ries, 2006; Ries, 2007; Feaster and others, 2009). For example, a warning applied to the rural regression equations for a basin with greater than 10-percent impervious area.

**Comment by USGSPMM3** [comment]
I believe these can be addressed with the current warnings as long as we add percent impervious as a required variable but please check with Ryan

**Comment by amedenblik** [comment]
This will be handled by the database. No additional programming tasks.
