### ISSUE TITLE
Allow multipoint delineation

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1169]
Waiting on open source delineation. Deadline: end of September 2022

From the [SC StreamStats Phase II proposal](https://doimspp.sharepoint.com/sites/SSPhaseII/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FSSPhaseII%2FShared%20Documents%2FGeneral%2FProposal%2FSC%5FStreamStats%5FPhase%5FII%5FProposal%5FFinal%2Epdf&parent=%2Fsites%2FSSPhaseII%2FShared%20Documents%2FGeneral%2FProposal):

"Due to data improvements from lidar data in South Carolina, there can be multiple flow lines throughout swampy low-lying areas of the landscape. In these low-lying areas, streamgage operations typically require multiple measurements across various channels to capture the full extent of the drainage basin. The StreamStats application currently does not provide a way to spatially select and aggregate multiple stream segments to capture the full extent of flow in these areas, and a delineation from one ungaged point may not represent the full drainage basin represented by the gage. Multipoint delineation would add the functionality to select multiple stream segments by point selection and provide a method for aggregating the resultant basin characteristics for flow statistics calculations."

**Comment by amedenblik** [comment]
Also add analytics to capture the points (line) that are submitted to the service

**Comment by amedenblik** [comment]
Include upper limit on line length

**Comment by harper-wavra** [comment]
Things completed so far in branch HW-1169:
- allow users in SC to select 'Delineate By Line'
- allow users to draw a line 
- send the line to ssLineIntersection to get back points to be delineated with
- send those points to ssExcluedPolygon to see if they are valid points
- added Google Analytics to get region and line used to delineate 

Left to do:
- [x] get ssLineIntersection and ssSnapPoints working for all regions, need to figure out how to host streamgrid rasters.
- [x] make multiple delineation calls
- [x] send combined delineation through edited basin endpoint to get BCs and scenario results #1828 
- [ ] include an upper limit on the length of the line. 
    - This could be by distance, in which case we could reuse code from the measure tool (client-side), or by the number of intersection points (service change). May need Pete's input on this. 
- [ ] improve analytics once more code has been added
- [x] combine delineations into one polygon
- [ ] bug: if clicking second point too fast the line doesn't stop after two clicks

**Comment by amedenblik** [comment]
Consider disabling editing basins when multipoint delineation is used

**Comment by amedenblik** [comment]
Example lines (start point and endpoint):

- 33.89489, -80.17977 and 33.90020. -80.16477
- 33.83959, -79.44883 and 33.85760, -79.44722
- Swampy global basin: 33.7224 / -80.6341  to 33.7442 / -80.5770. Bridge at: 33.7692, -80.6390
- 33.5071, -79.6014 (awaiting additional info)
- 33.4560, -79.9041 (awaiting additional info)
