### ISSUE TITLE
February 2022 Migration

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1174]
**GitHub issue checklist:** 

Use the migration document [here](https://doimspp.sharepoint.com/:w:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B545482F7-D3E5-45B1-A81F-F3D6140E2A46%7D&file=StreamStats%20Cloud%20Migration.docx&action=default&mobileredirect=true).  

**Before migration:** 

- [x] Ensure all expected updates are listed in the [Migrations section](https://doimspp.sharepoint.com/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc={3db134d6-2d7c-49a3-9d03-8bc1b11e7f5b}&action=edit&wd=target%28Migrations.one%7Ca7c80c4a-4ff8-46c3-8122-e38fae74a8dc%2F%29&wdorigin=717) in StreamStats OneNote. Contact the listed contact person if there are any questions.
- [x] Clean up any test data in the databases so when we update it goes as smoothly as possible.
- [x] Run:
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest) 
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/) 
 - [x] Create new release for code ([checklist](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B86ee3545-8271-46a1-b16f-158b12f19ba3%7D&action=edit&wd=target(Introduction.one%7CFA6D5C1D-D7FB-4D35-B339-992EF3438208%2F)onenote%3Ahttps%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FIntroduction.one#GitHub%20Release%20Checklist%26section-id%3D%7BFA6D5C1D-D7FB-4D35-B339-992EF3438208%7D%26page-id%3D%7B57C9AF33-A622-47D6-9707-B76CA291DD70%7D%26end), [instructions](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B86ee3545-8271-46a1-b16f-158b12f19ba3%7D&action=edit&wd=target(FAQs.one%7CD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%2F)onenote%3Ahttps%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FFAQs.one#I'm%20ready%20for%20a%20release.%20Now%20what%26section-id%3D%7BD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%7D%26page-id%3D%7B53ABA9A9-4A9D-4427-8DAA-662F20112BF9%7D%26end)). We added SC Dams, ~~Coordinate reach fix~~, localres to DE and NJ. Need to remove coordinated reach from production code.

**Migration checklist:**  

- [x] 1) Turn Off TestWeb  
- [x] 2) Snapshot existing TestWeb  
- [x] 3) Create 2 ProdWeb(a&b)-new EC2 instances from TestWebSnapshot  
- [x] 4) Update config files on prod services  
- [x] 5) Test the ArcGIS desktop licenses on ProdWebA and ProdWebB  
- [x] 6) Turn off shared E: drive
- [x] 7) Edit Task Scheduler scripts 
- [x] 8) Test the services 
- [x] 9) Point prod load balancer to new prod web machines  
- [x] 10) Reassign Elastic IP addresses from old to new prod web machines  
- [x] 11) Turn on TestWeb 
- [x] 12) Update StateServices map service
- [x] 13) ~~Update the EC2 instance reference in the S3:ss-lambda/prod_scale_ec2_instances_ids.txt, and sandbox_start_ec2_instances_ids.txt and sandbox_stop_ec2_instances_ids.txt files~~
- [x] 14) Deploy new production code 
- [x] 15) Update Databases (StreamStats and NSS) 
- [x] 16) Run: 
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest) 
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/) 
- [x] Message Chad about updating Test
- [x] 17) Once you’ve confirmed the migration has gone well (3 business days later):  
    - [x] Terminate old ProdWebA, ProdWebB machines  
    - [x] Delete their attached data volumes (the 1800GB data drives)   

**Additional items:**
- [x] Should we disable Pull From S3? from the script `# Important: this is only valid for test.streamstats.usgs.gov server. When migrating to prod,  # disable the windows scheduler task`
- [x] On Tuesday check if copylogs task is working
- [x] Update BatchTester values for NJ? DE?

**Comment by amedenblik** [comment]
Updates with this migration:

- New release of client code, version 4.7.0 ([see changes here](https://github.com/USGS-WiM/StreamStats/releases/tag/v4.7.0))
- NJ: all new base data
- DE: all new base data & new regressions
- SC: added dams, roadways and regulation; changed pop-ups for bridges
- IN: XML file changed
- OH: XML file changed
