### ISSUE TITLE
SC Roads Update

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1177]
- Vary the line width per the USGS cartographic standards for the SCDOT Road Network and Local Road Network.
![image](https://user-images.githubusercontent.com/59063181/152571238-bb8a7cc8-4550-46bc-9b0c-cadf70dcc448.png)

- Change the order that the information appears in for both roads and bridges. Waiting on Thomas's reply for what order he would like to see information. Should get an answer by the 9th.

**Comment by amedenblik** [comment]
SCDOT would like the attributes in the following order (corresponding fields are in parentheses).

**Bridges:**

Structure ID: 0910002600400 (STRUCTURE_)
Asset ID: 3198 (ASSET_ID)
Crossing: BURKE CREEK (CROSSING)
County Identifier: 9 (COUNTY_ID)
Route Type: I- (RTE_TYPE)
Route Number: 26 (RTE_NBR)
Route Direction: E (RTE_DIR)
Route LRS: 09010002600E (RTE_LRS)
Location: 8MI W OF ST MATTHEWS (LOCATION)
Structure: 32 (STRUCTURE1)


**SCDOT Owned Roads:**

Route Identifier: LEXINGTON S-117 N (ROUTE_ID)
Route Type: S- (ROUTE_TYPE)
County Identifier: 32 (COUNTY_ID)
Route Number: 117 (ROUTE_NUMB)
Street Name: SPRING HILL RD (STREET_NAM)
Route LRS: 32070011700N (ROUTE_LRS)
Beginning Milepost: 1.765 (BEG_MILEPO)
Ending Milepost: 2.05 (END_MILEPO)
Evacuation Route: 0 (EVAC_ROUTE)
Toll Road: N (TOLL_ROAD)
One-way: 0 (ONEWAY)


**Non-SCDOT Owned Roads:**

Street Name: BOYKIN LN (RoadName)
Route LRS: 18090075500N (RouteLRS)
Total Number of Lanes: 2 (TotalNumbe)
Beginning Milepost: 0 (BeginMileP)
Ending Milepost: 0.691 (EndMilePoi)
Factored AADT: 200 (FactoredAA)
Factored AADT Year: 2020 (FactoredA1)
Functional Class Name: Rural – Local (Functiona1)
