### ISSUE TITLE
Add Culverts WMS Layer

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1186]
Add MA Culverts Layer: https://usgs.maps.arcgis.com/home/item.html?id=769d2098dbb34398a6d32ba48e418e44#overview

When a user selects MA the culverts layer should be displayed. As of right now you need to log in to see the map layer. If needed we can have a simple login functionality in order to view layer, could also have a secrets file with login information.

**Comment by amedenblik** [comment]
@Abigail770 We add state layers to StreamStats by editing the [appConfig.js file](https://github.com/USGS-WiM/StreamStats/blob/dev/src/appConfig.js). You can use other states that have layers as a model for the MA region: see [this example](https://github.com/USGS-WiM/StreamStats/blob/dev/src/appConfig.js#L386L434) for the SC bridges. 

To get the service URL, click the link Harper provided above and click "[Feature Service](https://services.arcgis.com/v01gqwM5QqNysAAi/arcgis/rest/services/Massachusetts_Stream_Crossing_Project_Data/FeatureServer?token=xLQs6Snqxs2obAatFoYzt436uyOzy2euS0Gr3LlTFfziadH5SSaxRRJD7fcP1z5vLQxXprrnE4IcVHqCv-d8FJkxELeiNkPovl7Gb1xxTtleZ-gmbJCRA81oBynkLBOHtERq-JEBX1DLZmYJOICndIiZRxbYGjIhaYjNSsXfm9FT_ij2ll12nRXTTa_FhHSlE8KACPagZ_0-_hl_05vgaoLWUD-Gt5p-UUOK6wcBGro.)" on the right. You will then want to click "[NAACC_Squanacook_Stream_Crossings](https://services.arcgis.com/v01gqwM5QqNysAAi/ArcGIS/rest/services/Massachusetts_Stream_Crossing_Project_Data/FeatureServer/0?token=xLQs6Snqxs2obAatFoYzt436uyOzy2euS0Gr3LlTFfziadH5SSaxRRJD7fcP1z5vLQxXprrnE4IcVHqCv-d8FJkxELeiNkPovl7Gb1xxTtleZ-gmbJCRA81oBynkLBOHtERq-JEBX1DLZmYJOICndIiZRxbYGjIhaYjNSsXfm9FT_ij2ll12nRXTTa_FhHSlE8KACPagZ_0-_hl_05vgaoLWUD-Gt5p-UUOK6wcBGro.) (0)" under Layers to get information about that service.
