### ISSUE TITLE
Generate Culvert Report

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1188]
When a user selects a culvert point there should be a button to "Display Report." If a user selects this button the lidar delineation should be shown on the map and the left sidebar should "skip" the Delineation and Select Scenario steps, in order to go right to the Build a Report step. The report should following the SS report template and included a citation for their lidar data.

Report information TBD

**Comment by Abigail770** [comment]
Do we want the Display Report button to be in the popup or in the sidebar?

**Comment by Abigail770** [comment]
Should "Show Basin Characteristics" and "Basin Characteristics Report" still be available in the sidebar under Build a Report?  Or just "Hydraulic Model Report"?
![image](https://user-images.githubusercontent.com/54085652/155230603-8026a9e1-8773-4bb0-9101-0639bf85b232.png)

**Comment by harper-wavra** [comment]
Just Hydraulic Model Report should be shown. When we skip basin delineation and selecting scenarios there won’t be enough information to create those other two reports.
