### ISSUE TITLE
Separate Exclude Poly and Stream grid 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1195]
It has been requested to separate the exude poly and stream grid layers so they can be turned on and off separately.

If we complete this issue, it could be helpful for issue #1182

**Comment by Abigail770** [comment]
Should both layers still be toggleable under the region name dropdown (e.g. NC Map Layers), or listed as separate layers like below?
![image](https://user-images.githubusercontent.com/54085652/159278588-0f33211f-8ef7-401c-b408-9e506cc9e195.png)

**Comment by harper-wavra** [comment]
I am not sure how many users would know to go into NC Map Layers to toggle the streamgrid and exclude polys on/off, so my initial thought is to separate them. 

Maybe @USGSPMM3 has additional thoughts?

**Comment by amedenblik** [comment]
I'd be inclined to leave the layers under NC Map Layers, since that is where users are used to seeing them. Will defer to Pete M, though!

**Comment by Abigail770** [comment]
I've created a [branch in wim_angular](https://github.com/USGS-WiM/wim_angular/tree/add-sublayer-toggle) with changes to the legend there.  I've tested the changes locally with [branch 1195](https://github.com/USGS-WiM/StreamStats/issues/1195) and it's working there.

I can make a pull request for the branch in wim_angular (not sure if this should go to staging or master).  I searched through WIM's repos and it looks like GroundWaterWatch, Streamest and STN are all using the legend from wim_angular, plus a few archived repos (STNWeb2_Oracle, STNPublicInfo).

**Comment by harper-wavra** [comment]
It should first go into staging, then we can merge staging into master and create a new release. 

If the change you made in wim_angular is a non breaking change, then the repositories that use it (GroundWaterWatch, Streamest and STN) wouldn't need to make any changes. Have you worked with STN? Maybe if we pull that down we could see if using your new wim_angular branch breaks anything. 

If the change if a breaking change then I think the repositories that use it (GroundWaterWatch, Streamest and STN) can just pull from the former release. For example it looks like the current release (https://github.com/USGS-WiM/wim_angular/releases) is 1.1.4 so those repos can point to that release and Streamstats can point to the new release we create.
