### ISSUE TITLE
March 2022 Migration

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1198]
**GitHub issue checklist:**  

Use the migration document [here](https://doimspp.sharepoint.com/:w:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B545482F7-D3E5-45B1-A81F-F3D6140E2A46%7D&file=StreamStats%20Cloud%20Migration.docx&action=default&mobileredirect=true).   

**Before migration:**  
- [x] Ensure all expected updates are listed in the [Migrations section](https://doimspp.sharepoint.com/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc={3db134d6-2d7c-49a3-9d03-8bc1b11e7f5b}&action=edit&wd=target%28Migrations.one%7Ca7c80c4a-4ff8-46c3-8122-e38fae74a8dc%2F%29&wdorigin=717) in StreamStats OneNote. Contact the listed contact person if there are any questions. 
- [x] Clean up any test data in the databases so when we update it goes as smoothly as possible. 
- [x] Run: 
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest)  
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/)  
- [x] (if needed) Create new release for code ([checklist](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B86ee3545-8271-46a1-b16f-158b12f19ba3%7D&action=edit&wd=target(Introduction.one%7CFA6D5C1D-D7FB-4D35-B339-992EF3438208%2F)onenote%3Ahttps%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FIntroduction.one#GitHub%20Release%20Checklist%26section-id%3D%7BFA6D5C1D-D7FB-4D35-B339-992EF3438208%7D%26page-id%3D%7B57C9AF33-A622-47D6-9707-B76CA291DD70%7D%26end), [instructions](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B86ee3545-8271-46a1-b16f-158b12f19ba3%7D&action=edit&wd=target(FAQs.one%7CD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%2F)onenote%3Ahttps%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FFAQs.one#I'm%20ready%20for%20a%20release.%20Now%20what%26section-id%3D%7BD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%7D%26page-id%3D%7B53ABA9A9-4A9D-4427-8DAA-662F20112BF9%7D%26end)).
    - [x] Client Code -  IA QPPQ, IN coordinated reach, change of NSSServices to NSSServicesV2.
    - [x] NSSServices - QPPQ additions 

**Migration checklist:**   
- [x] 1) Turn Off TestWeb   
- [x] 2) Snapshot existing TestWeb   
- [x] 3) Create 2 ProdWeb(a&b)-new EC2 instances from TestWebSnapshot   
- [x] 4) Update config files on prod services   
- [x] 5) Test the ArcGIS desktop licenses on ProdWebA and ProdWebB   
- [x] 6) Turn off shared E: drive 
- [x] 7) Edit Task Scheduler scripts  
- [x] 8) Test the services  
- [x] 9) Point prod load balancer to new prod web machines   
- [x] 10) Reassign Elastic IP addresses from old to new prod web machines   
- [x] 11) Turn on TestWeb  
- [x] 12) ~(if needed) Update StateServices map service~
- [x] 13) (if needed) Deploy new production code  
- [x] 14) (if needed) Update Databases (StreamStats and NSS)  
- [x] 15) Run:  
    - [x] [SS Integration Tests]( https://github.com/USGS-WiM/StreamStatsIntegrationTest)  
    - [x] [BatchTester]( http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/batchTester/)  
- [x] 16) Once you’ve confirmed the migration has gone well (3 business days later):   
    - [x] Terminate old ProdWebA, ProdWebB machines   
    - [x] Delete their attached data volumes (the 1800GB data drives)    

**Additional items:** 
- [x] NavigationServices and GagestatsServices were both updated on test, we should turn these back on prod.
- [x] Confirm that StreamStats is no longer using NSSServicesV2 (see #1197 for info) and that NSSServicesV2 are removed from prod and test
- [x] Update dist folders on Test for NSSServices; check web.config for "Production" and appsettings.json for DB credentials

**Comment by amedenblik** [comment]
Having issues with new NSSServices/database migration.

Plan for 3/25/22:
- [x] Change appConfig on StreamStats client on AWS: 
     - [x] Remove "FDCTM" application from Iowa
     - [x] Confirm that it is using NSSServices (not NSSServicesV2)
- [x] Roll back NSSServices on both new prod machines to dist202107
- [x] Check appsettings.json and web.config in the NSSServices dist202107
- [x] Confirm that NSSServices is working on new prod machines
- [x] Do steps 8 through 11 above
- [x] Do step 15
- [x] Confirm that NSSservicesV2 is not being used
- [x] Update dist folders on Test for NSSServices; check web.config for "Production" and appsettings.json for DB credentials
- [x] Update the StreamStats Teams channel

Plan for ~~3/28/22~~ 4/1/22:
- [x] Work on fixing NSSServices with prod database https://github.com/USGS-WiM/wim-infrastructure/issues/236
- [x] Update NSSServices dist folder path in IIS and check appsettings.json and web.config
- [x] Test new NSSServices
- [x] Update appConfig for StreamStats client on AWS: add back "FDCTM" to Iowa
- [x] Update the StreamStats Teams channel 
- [x] Talk with Ryan about how to proceed with Location table in DB
