### ISSUE TITLE
Add IN Coordinated Reach Functionality

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1201]
- [x] Add the fixed Coordinated Reach code from #1178 
- [x] Add an IN layer called "Reaches": https://gis.streamstats.usgs.gov/arcgis/rest/services/coordinatedreaches/in/MapServer/
- [x] Include a Coordinated Reach flowstat report that includes (at minimum) these fields: StreamID/ID, Stream Name, and Basin Name(optional).

**Comment by harper-wavra** [comment]
@USGSPMM3 The first two bullet points should be easy enough to add in. As for the 3rd item in the list, how would you like the Coordinate Reach flowstat report to be formatted? It sounds like he wants StreamID and Stream Name added for sure and Basin Name is optional. The [report.pdf](https://github.com/USGS-WiM/StreamStats/files/8143575/report.pdf)
currently only shows the basin name as far as I can tell. Where would you like us to add StreamID and Stream Name to the report?

Also do you have a preference for how the coordinate reach layer is displayed? I think Ryan might have mentioned making it yellow so it sticks out from the streamgrid layer.

**Comment by USGSPMM3** [comment]
@harper-wavra -sorry for not seeing this:

For the Layer I think yellow is fine. I was also contemplating a thicker blue line so it looks like river reaches but is more prominent. Your call.

In the report we show the basin name in the parenthesis, can we just add the StreamID and name? Or replace the basin with stream ID and name? I don't know if Moon needs all 3?
