### ISSUE TITLE
Use correct QPPQ results when area-weighting does not occur

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1207]
When a Limitation is in place that prevents area-weighting of regression regions, the QPPQ results for multiple regions are returned instead of one area-weighted QPPQ result. The client needs to select the correct region's QPPQ results and use those for the graphs and tables in the report. 

This issue is related to service work: https://github.com/USGS-WiM/NSSServices/issues/237

**Comment by harper-wavra** [comment]
Printing out all results in issue https://github.com/USGS-WiM/StreamStats/issues/1306, this issue is no longer relevant.
