### ISSUE TITLE
Fix Deploy to Test GitHub Action

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1221]
The GitHub action that occurs when dev is pulled into staging is failing. 

Example: https://github.com/USGS-WiM/StreamStats/actions/runs/1987565726

One "solution" is to disable the action, since pushing updates to Test requires some manual intervention anyway.

**Comment by harper-wavra** [comment]
Disabled both Deploy to Test and Deploy to Prod github actions. Sometimes it requires manual updates to the appconfig when pushing to test and production, so for now its better to deploy manually.
