### ISSUE TITLE
Populate State/Region options at smaller Zoom levels

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#124]
State/Region select options don't populate while zooming until zoom level 14. Is it possible to populate earlier?

**Comment by marsmith** [comment]
Yes , this can happen whenever.  I'm not sure how we came up with 14. 

Just as a talking point maybe for a future call, in v3 if you only have a single state taking up your whole view, it doesn't ask you to confirm that state, it just assumes. I'm not sure this is a good thing

**Comment by HansVraga** [comment]
Lets force the user to select an area, rather than assume. Weird things could happen once you assume if the user then pans around...

I like zoom level 8 or 9 to start showing the options to the user.
