### ISSUE TITLE
New Outlines

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#125]
Are these outlines supposed to be displayed?

![weirdoutlines](https://cloud.githubusercontent.com/assets/12058013/11132825/3a6df5a0-8960-11e5-9a67-58b1f1b9a974.PNG)

**Comment by HansVraga** [comment]
They appeared when I zoomed in to level 14, selected Colorado, then zoomed out all as far as I could, then zoomed back in to here.

**Comment by marsmith** [comment]
Nope, good find

**Comment by marsmith** [comment]
Looks like added layers need to be cleared if zoom level and state/region selection need to be cleared if zoom level goes back under a certain threshold

**Comment by marsmith** [comment]
Should be fixed with #140
