### ISSUE TITLE
Persistent Download Basin popup

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1251]
Freshdesk ticket: https://streamstats.freshdesk.com/a/tickets/117354

This issue was reported by some users: After delineating a basin, the "download basin" options dropdown appears automatically without clicking the download basin button. This only occurs in Chrome after some updates were pushed. One version of Chrome that is seeing this issue is Chrome Version 99.0.4844.51 (Official Build) (64-bit). 

![image](https://user-images.githubusercontent.com/40237491/159927289-d189f013-e65b-41bb-ae38-51b2c74af723.png)

Waiting to work on this, because I do not see this bug on my version of Chrome.

**Comment by HansVraga** [comment]
Suggest a `wontfix` and close for this one, I have a later version of chrome and this bug is not appearing for me - which to me suggests this was a chrome bug.

**Comment by amedenblik** [comment]
Closing-- cannot recreate the issue

**Comment by amedenblik** [comment]
This happens if you're on VPN

**Comment by amedenblik** [comment]
Note from Kitty on May 9: "Ryan and I have not noticed the popup lately. It seems to have gone away again."
