### ISSUE TITLE
Add note about published dataset in report for basin shown

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/StreamStats#1267]

**Comment by Abigail770** [comment]
Would something similar to the Provisional Data Statement in Thresholds be appropriate here?

"The data and basin layer presented in this report are unpublished and subject to revision until they have been thoroughly reviewed and received final approval.  Subsequent review may result in significant revisions to the data."

**Comment by amedenblik** [comment]
Once their data are published, the "[Approved data released to the public](https://www.usgs.gov/about/organization/science-support/office-science-quality-and-integrity/fundamental-science-5#1)" disclaimer would be appropriate. This note is already in the "About" modal, so I think we are good here:
![image](https://user-images.githubusercontent.com/40237491/163628830-2434a24a-97d1-4acd-a77a-a29df0f26bd9.png)

Please feel free to re-open this issue if I am forgetting something we discussed!
