### ISSUE TITLE
DRNAREA not showing up/calculating for point in Montana

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#1273]
Drafting this issue as we're ironing out some other issues introduced with the March 2022 Migration. 
Following delineation for point 46.63709, -112.08449, you can review all available BCs for calculation and DRNAREA does not appear. 

- If you select a scenario (like BANKFULL STATS) DRNAREA does appear
- If you proceed with calculations, DRNAREA fails to calculate.
![image](https://user-images.githubusercontent.com/12058013/161294484-b920d699-01da-4714-891a-49431bbb72eb.png)

**Comment by amedenblik** [comment]
Thanks for making this issue. To be clear for our records, this was definitely an issue prior to March 2022 migration.

**Comment by harper-wavra** [comment]
@USGSPMM3 Should this drnarea be available at this point?
