### ISSUE TITLE
Add Maine Mean August Baseflow WMS layer

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1275]
Add Mean August Baseflow WMS layer on Dev for Maine

https://streamstats.freshdesk.com/a/tickets/117330

https://usgs.maps.arcgis.com/home/item.html?id=eb8d1922d4984488a0c283933504fee6

**Comment by amedenblik** [comment]
Seems like this map layer will work fine.

Questions for meeting with Maine team:
1. What is the difference between State/County/Town/Neighborhood Scale View layers? Do we need to include all these, or just one?

Include all layers because symbology is different based on scale

2. What is the desired symbology? Do they want what is in the ArcGIS Online map?

They want the symbology in the ArcGIS Online map

3. Do they want a popup when you click on the layer? What attributes do they want to appear? If so, they'll need to provide field name and a formatted title: ex. "July Average Precipitation: <JULYAVPRE>"

They want what appears in the pop-up on the ArcGIS Online map. It is the same for all 4 layers.

Title of layer: Mean August Baseflow

**Comment by harper-wavra** [comment]
Branch AM-1275 is working for the state view. 
Not sure if we need to copy the same [code](https://github.com/USGS-WiM/StreamStats/blob/AM-1275/src/appConfig.js#L317-#L401) for county, town and neighborhood, or if there is a way to loop over it? I also might be making this more complicated then it needs to be :sweat_smile:
