### ISSUE TITLE
QPPQ Additions

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1292]
Feedback on https://dev.streamstats.usgs.gov/ss-test-qppq/

1. - [x] The downloadable CSV includes the data for the tab that the user is on (DA-only vs multivariate), which is great. It looks like when the CSV is opened, there is no indication of which method was chosen within it . Would it be difficult to add a cell somewhere that defines which method the user downloaded?
2. - [x] Make the QPPQ section in the report collapsible
        - [ ] Fix issue with plots getting smaller after being collapsed and opened  --> #1332 
        - [x] Fix issue with tab formatting looking weird: 
![image](https://user-images.githubusercontent.com/40237491/172644994-7e13e1d3-2d7b-484c-a188-a6133b045199.png) Used to look like this: 
![image](https://user-images.githubusercontent.com/40237491/172645080-ae8a9861-7ef4-4b9c-ae96-c0e651d387fd.png)

3. - [x] Add citation to the QPPQ section in the report: https://pubs.er.usgs.gov/publication/sir20155181
4. - [x] The flow-duration statistics are returned as part of the report, in a collapsible section titled the "Flow Duration Curve Transfer Method". Would it be possible to update the title of this section to match the terminology returned form the development site for the FDCs, “Flow-Duration Statistics”? That would help differentiate it from the following section as well (also titled FDCTM). Solution: When FDCTM scenario is selected, automatically select the FDS scenario and do not allow it to be unselected. The report will then contain the FDS section and the FDCTM graph section. The report will not contain an FDCTM statistics section.
     - [x] Fix resulting bug: 
![image](https://user-images.githubusercontent.com/40237491/172682127-8451830c-9af5-4a07-be5f-916c8bd884cd.png)

5. - [x] The estimated FDC table that is included in the FDCTM output (starts at 0.01 and ends at 99.9) is in the opposite order of estimated FDC in the flow-duration stats section (starts at 99.9 and ends at 0.1). Would it be possible to put those in the same order?
6. - [x] ~Omit the second "(FDCTM)" in the title of the section~ Cannot reproduce this issue
![image](https://user-images.githubusercontent.com/40237491/172460259-afeec7fc-cc6d-4898-a139-ac76037f3308.png)

**Comment by harper-wavra** [comment]
Added additional feedback, and changes to this issue that were requested by Mackenzie.

**Comment by harper-wavra** [comment]
For citations I found these two, are there others? Can this be pushed to production or are these not published yet?

[1] Linhart, S.M., Nania, J.F., Sanders, C.L., Jr., and Archfield, S.A., 2012, Computing daily mean streamflow at ungaged locations in Iowa by using the Flow Anywhere and Flow Duration Curve Transfer statistical methods: U.S. Geological Survey Scientific Investigations Report 2012–5232, 50 p., https://doi.org/10.3133/sir20125232.

[2] Over, T.M., Riley, J.D., Marti, M.K., Sharpe, J.B., and Arvin, D., 2014, Estimation of regional flow-duration curves for Indiana and Illinois (ver. 2.0, April 2022): U.S. Geological Survey Scientific Investigations Report 2014–5177, 24 p. and additional downloads, tables 2–5, 8–13, and 18, https://doi.org/10.3133/sir20145177.

**Comment by harper-wavra** [comment]
For **point 3**, I found these two, are there others? Can this be pushed to production or are these not published yet?

- [1] Linhart, S.M., Nania, J.F., Sanders, C.L., Jr., and Archfield, S.A., 2012, Computing daily mean streamflow at ungaged locations in Iowa by using the Flow Anywhere and Flow Duration Curve Transfer statistical methods: U.S. Geological Survey Scientific Investigations Report 2012–5232, 50 p., https://doi.org/10.3133/sir20125232.
- [2] Over, T.M., Riley, J.D., Marti, M.K., Sharpe, J.B., and Arvin, D., 2014, Estimation of regional flow-duration curves for Indiana and Illinois (ver. 2.0, April 2022): U.S. Geological Survey Scientific Investigations Report 2014–5177, 24 p. and additional downloads, tables 2–5, 8–13, and 18, https://doi.org/10.3133/sir20145177.

For **point 4**, when you select both Flow-Duration Statistics and Flow-Duration Curve Transfer Method you end up with the section in the report named 'Flow-Duration Statistics' and a section named 'Flow-Duration Curve Transfer Method', both show the same results. At our next call we should chat to see how they want to handle that. 

![image](https://user-images.githubusercontent.com/59063181/171474853-f2f5ae3c-367e-4b4b-937a-54f48402c9eb.png)

For **point 5**, I think we could change the way the plot is, but I don't think we'd want to change the way the stats section is as that's how it is for all other stats.

**Comment by amedenblik** [comment]
Updates from conversation with Pete:

- **Point 3:** add this citation at the bottom of FDCTM section https://pubs.er.usgs.gov/publication/sir20155181
- **Point 4:** When FDCTM scenario is selected, automatically select the FDS scenario and do not allow it to be unselected. The report will then contain the FDS section and the FDCTM graph section. The report will not contain an FDCTM statistics section.
