### ISSUE TITLE
Able to delineate before getting to zoom level 15

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#132]
It seems to work (see images - was able to do this at zoom 14) but I think we want to force users to level 15 so they have the blue streams populated before delineating. 
![delinateat14zoom](https://cloud.githubusercontent.com/assets/12058013/11183751/92008074-8c41-11e5-9ed6-f952a3b1b4ba.PNG)
![result](https://cloud.githubusercontent.com/assets/12058013/11183754/96d42fce-8c41-11e5-843f-ca83457fc9dc.PNG)

**Comment by marsmith** [comment]
Implemented with #138 

![image](https://cloud.githubusercontent.com/assets/6529123/11305364/4deb056c-8f7a-11e5-92de-3f51f8502768.png)
