### ISSUE TITLE
Cooperators logos not displaying

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1329]
The cooperator logos aren't displaying in the About modal.
Here is an example after you have selected Utah:
![image](https://user-images.githubusercontent.com/59063181/172244036-94770e79-382b-44de-bd51-219031514e6e.png)

**Comment by harper-wavra** [comment]
The text and images for the 'State/Regional Info' comes directly from the freshdesk pages: https://streamstats.freshdesk.com/a/solutions/categories/9000106501/folders/9000163157?view=all. If you click on the Utah page there you can see the links to the photos are broken there as well. They images need to be fixed in those pages and that will in turn fix them in Streamstats. 

- adding as a discussion item for next meeting

**Comment by harper-wavra** [comment]
Pete to task Katie and Jarod with fixing these articles in freshdesk.

**Comment by amedenblik** [comment]
State / Regional Info moved to Drupal. Closing this issue as it's no longer relevant.
