### ISSUE TITLE
Move additional IA and NC pages

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1336]
NC and IA have additional gage pages and they are stored on VM205. We want them off VM205. There are a couple options:

- Host on S3
- Host on production machines
- Something else? Pete feels we should be hosting them since we have been hosting them thus far

Need to figure out which would be the best option and change where these are hosted and the link to how they are accessed.

**Comment by amedenblik** [comment]
Files will be hosted here: 
[s3://streamstats.usgs.gov/gagePages/IA/](https://s3.console.aws.amazon.com/s3/buckets/streamstats.usgs.gov?region=us-east-1&prefix=gagePages/IA/)
[s3://streamstats.usgs.gov/gagePages/NC/](https://s3.console.aws.amazon.com/s3/buckets/streamstats.usgs.gov?region=us-east-1&prefix=gagePages/NC/)

Example: https://streamstats.usgs.gov/gagePages/IA/05470000_stats.pdf

Waiting on files from John

**Comment by harper-wavra** [comment]
They have all been moved into the S3 bucket. I think this is ready to be made into a PR.

some examples:
https://streamstats.usgs.gov/gagePages/NC/Sta_02082506_daily_discharge_percentiles_table_by-wateryears.txt
https://streamstats.usgs.gov/gagePages/NC/Sta_02082506_daily_discharge_percentiles_table_by-day-month-seasonal.txt
https://streamstats.usgs.gov/gagePages/IA/05464220_stats.pdf
