### ISSUE TITLE
Coordinated Discharge Streams GIS layer 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1363]
See if we can update IN coordained reach map layer to new layer, [https://services.arcgis.com/2Mcx1M1MORKfBNPM/arcgis/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservices.arcgis.com%2F2Mcx1M1MORKfBNPM%2Farcgis%2Frest%2Fservices%2FIndiana_Coordinated_Discharge_view%2FFeatureServer&data=05%7C01%7Chwavra%40usgs.gov%7C60f5174bf5c246f7280d08da6356b722%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637931521329388958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kZZdIdAyDuinLy4JsOlM%2FFh4ev9KTSpHQoo4mn7TA%2F0%3D&reserved=0). 

Should ask @USGSPMM3 for more information/timelines at our next check-in.

**Comment by USGSPMM3** [comment]
I'm thinking by August migration we have it implemented and QAQC'd? I suspect it will take some back and forth with Moon, especially if they couldn't create the database/table like we wanted or intended (not sure if that is the case)

**Comment by harper-wavra** [comment]
- [x] Use new service to display on map
- [x] Use new service to query click point (https://services.arcgis.com/2Mcx1M1MORKfBNPM/ArcGIS/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer/2/query?geometry=-86.02263955697747%2C40.0643834040393%2C-86.02252204824619%2C40.06429347200293&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=Stream_Name,StreamID_ID,BASIN_NAME,DVA_EQ_ID,a10,b10,a25,b25,a50,b50,a100,b100,a500,b500&returnGeometry=false&returnIdsOnly=false&returnCountOnly=false&returnZ=false&returnM=false&f=pjson)
- [x] Change legend icon

**Comment by harper-wavra** [comment]
Mostly complete in branch HW-1363, waiting on more info from IN cooperators.

**Comment by amedenblik** [comment]
Added layer as "SS: IN DNR Coordinated Reaches" to StreamStats Uptime Robot
