### ISSUE TITLE
HydrologyFeatures application: rename sidebar

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1369]
Follow up to #1362

Change sidebar button from "Select Hydrologic Features" to "Edit Hydrologic Features"

**Comment by KhanyaMateta** [comment]
In which file is this issue in?

**Comment by amedenblik** [comment]
Hi @KhanyaMateta, thanks for your interest in contributing! We actually decided that this issue is no longer needed.
