### ISSUE TITLE
Flood-Frequency Statistics and Custom Plots

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1371]
Include flood-frequency statistics computed at a gage on a plot of the daily mean flows or annual peak flows. Current streamgage selection functionality will be modified to allow for the inclusion of flood-frequency statistics such as the 50-, 20-, 10-, 4-, 2-, 1-, 0.5-, and 0.2-percent chance exceedance flows (also known as the 2, 5, 10, 25, 50, 100, 200, and 500-year recurrence interval floods) on a chosen graph, which also will be available on a downloadable image (Feaster and others, 2009, 2014). Available output data will include hydrograph, location coordinates, and associated data.

![image](https://user-images.githubusercontent.com/40237491/179068056-47bf8410-3eb4-4d2b-bd93-6420ee6def85.png)

**Comment by harper-wavra** [comment]
Use below gage statistics to get values for the horizontal lines. 
![image](https://user-images.githubusercontent.com/59063181/179230032-9a14dde7-4303-4c20-9ec5-446d85de0025.png)

**Comment by harper-wavra** [comment]
After talking with Tom we are going to start with a plot of the annual peak flows.

Example request: 
Annual peaks - https://nwis.waterdata.usgs.gov/usa/nwis/peak/?format=rdb&site_no=02173500&

**Comment by harper-wavra** [comment]
I got started on this in branch HW-1371 (https://github.com/USGS-WiM/StreamStats/tree/HW-1371). I didnt get too far but feel free to use or take a look at it.

**Comment by amedenblik** [comment]
New inspiration graph: from  https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000 
![image](https://user-images.githubusercontent.com/40237491/187305259-ff8ae3b9-b7f7-4fb5-8129-67e5f711888c.png)

**Comment by harper-wavra** [comment]
Functionality we want to bring over from ^ plot:
- Choose start date & end date
- Annual peaks & colors
- Daily data (as blue line) 
- Be able to zoom in
- Horizontal AEP flood lines

**Comment by harper-wavra** [comment]
Closing in favor of https://github.com/USGS-WiM/StreamStats/issues/1424
