### ISSUE TITLE
SC Synthetic UH: Allow report to be printable

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1388]
See parent issue #1344 for more details
Complete #1386 first

- [x] Ensure that the modal can be printed and includes all information relevant to the SC Synthetic Unit Hydrograph Method, when the user clicks the "Print" button.`

- [x] Ensure modal values can be exported and includes all information relevant to the SC Synthetic Unit Hydrograph Method, when user clicks the "Download CSV."

**Comment by harper-wavra** [comment]
Download CSV was completed in issue #1387

**Comment by amedenblik** [comment]
Closed with https://github.com/USGS-WiM/StreamStats/pull/1425
