### ISSUE TITLE
SC Synthetic UH: Display warning messages 

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1392]
See parent issue #1344 for more details
Complete https://github.com/USGS-WiM/SC-RunoffModelingServices/issues/66 first

At the top of the output section, add warnings in a yellow warning box.

**Comment by harper-wavra** [comment]
I am was looking at this issue today. It looks like we had an open issue in the services but should these warning messages come back from the services instead? 

Also are there any warnings coming back from the services for synthetic UH currently, if so I don't think we are getting and printing them correctly. It seems like from the issue in the services there are not any, but I just want to make sure.

**Comment by amedenblik** [comment]
I agree that these warning messages should come back from the services instead. Just updated the description of this issue and made this issue instead (https://github.com/USGS-WiM/SC-RunoffModelingServices/issues/66).

**Comment by harper-wavra** [comment]
We are going to just add all SC Unit Hydrograph warning to the bottom of the results like they do in the spreadsheet.

**Comment by amedenblik** [comment]
Closed with #1433
