### ISSUE TITLE
Fix FDCTM issues

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1394]
In general:

- [ ] Results in Iowa (and maybe other regions?) do not appear sometimes
![image](https://user-images.githubusercontent.com/40237491/182483237-80f08e0a-bc9d-449e-bdee-59a3ac83e49e.png)

Exceedance Probabilities graph:
- [x] The y-axis tick labels sometimes do not show up completely or overlap the y-axis label
![image](https://user-images.githubusercontent.com/40237491/182434499-fc0fdcee-cd87-4031-a7d1-51ce41f3896d.png)

Estimated Flows graph:
- [x] The y-axis tick labels and the y-axis label do not show up. Probably just need to change the left margin 
![image](https://user-images.githubusercontent.com/40237491/182433864-7ee29d44-060b-4ae6-97ad-8894db92b754.png)

- [x] Change the series labels to be "Observed" and "Estimated"
![image](https://user-images.githubusercontent.com/40237491/182433921-2a2f92e4-9974-4ae4-86ed-2c67f7641933.png)

- [x] Both series are the same color (dark blue) instead of dark blue and light blue 

Estimated Flows table:

- [x] Change observed flow column to be "Observed ([gage number])"

![image](https://user-images.githubusercontent.com/40237491/182434166-71331a6a-baec-4633-a5be-832b33659f55.png)

**Comment by harper-wavra** [comment]
Not seeing the color issue anymore. Checked both locally and on production and I am seeing dark and light blue.
![image](https://user-images.githubusercontent.com/59063181/197210917-d1b3da2c-1199-40a7-8ded-25a3ac9f6407.png)
