### ISSUE TITLE
Remove references to legacy real-time gage pages

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1418]
Legacy real-time gage pages will be decommissioned in July 2023. We should remove any references to the legacy pages:

![image](https://user-images.githubusercontent.com/40237491/187227887-7807a428-a34a-41d3-9ad9-6f2764bc23b5.png)

![image](https://user-images.githubusercontent.com/40237491/187227736-10d89fce-da53-48ab-b813-0b30c5ab36e7.png)

**Comment by harper-wavra** [comment]
@USGSPMM3 

We will remove the Legacy Link. Other thoughts:

After you click into the StreamStats Gage Page, should we change NWIS Latitude & Longitude to Waterdata Latitude and Longitude? It uses the request https://waterservices.usgs.gov/nwis/site?site=10126400, which I assume isn't changing. 

The gagepop up also has a link to nwis. Should we change that link to say "Waterdata Page" and link it to https://waterdata.usgs.gov/monitoring-location/10126400/?
![image](https://user-images.githubusercontent.com/59063181/196278107-067f4cbb-b613-4499-9063-4a582387931b.png)

**Comment by amedenblik** [comment]
> The gagepop up also has a link to nwis. Should we change that link to say "Waterdata Page" and link it to https://waterdata.usgs.gov/monitoring-location/10126400/?

The link was already updated to via #1328 and will be pushed to Prod on Wednesday 👍 We could consider renaming the link for this issue though.
