### ISSUE TITLE
Create interface to enter Peak Rate Factor data for SC Synthetic Unit Hydrograph Method

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1421]
Part of #1344

See "PRF Calculator" sheet: `https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH_Verified%20on%205%20August%202022.xlsm?d=w9840a86621414c59884b8aa9e0ad817c&csf=1&web=1&e=yn9vEl`

**Comment by harper-wavra** [comment]
Need to finish https://github.com/USGS-WiM/SC-RunoffModelingServices/issues/44 first.

We will have drop downs for landuse, when users select the landuse the prf values will be automatically populated, but will be able to be edited, the user will also have to input area. We will then send to the prf endpoint and get PRF (or WSPRF) back from the services, which will then be sent to the scsyntheticunithydrograph endpoint.

![image](https://user-images.githubusercontent.com/59063181/192800878-e316237e-e80b-4c87-a0b1-608edb4f893a.png)

**Comment by amedenblik** [comment]
Closed with #1435
