### ISSUE TITLE
Annual Flow Plot with Flood-Frequency Statistics

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1424]
**General Information**: We would like to add a new modal popup for each stream gage that includes a plot of the annual peak flows with horizonal lines for the flood-frequency statistics. The idea of this plot comes from https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000, [second plot on the left](https://user-images.githubusercontent.com/59063181/190000736-a8414fd3-1c54-438c-be04-bb0ff9a8483a.png) and [this image](https://user-images.githubusercontent.com/59063181/190183917-45afcf1c-5a11-4d08-ad03-9943c99d74f8.png). 

**Overview of Functionality**: When you zoom in past a level 7 on StreamStats the gages will start to appear as colored triangles. When you click on one of those icons a gage popup will appear. Inside that popup is some general information about the gage as well as a couple of links, including links to NWIS and a link to our StreamStats Gage Page modal. We would like to add another link, that follows in the same way the StreamStats Gage Page link works to open a new modal. Inside that modal is where we would like to display this plot. The plot should display the annual peaks, retrieved from NWIS, and the x-percent AEP flood statistics as horizontal lines retrieved from our own GageStatsServices.

**Steps to Complete**:
1. Create a link which opens a new modal in the gage popup. You will have to create a new view and controller for this step. See the [Gagepage.html](https://github.com/USGS-WiM/StreamStats/blob/dev/src/Views/gagepage.html) and [GagePageController.ts](https://github.com/USGS-WiM/StreamStats/blob/dev/src/Controllers/GagePageController.ts) as examples.
2. Decide which plotting library to use. In order to create the plot, we will need to use a plotting library. The developer for the weather.gov plots used [HighCharts](https://www.highcharts.com/blog/tutorials/194-using-highcharts-with-angular-js/) so it could be helpful to use the same. Within StreamStats we have also used the library [NVD3](https://nvd3.org/), so that could be another option. If you search for 'nvd3' in the code, you can see where we have used it already. The future plan is to recreate most of the plots you see on that weather.gov page, so using HighCharts might be best in the long run. 
3. Pull annual peaks values from NWIS to begin to create a plot in the modal. The nwis call you can use is: https://nwis.waterdata.usgs.gov/usa/nwis/peak/?format=rdb&site_no=02173500&startDT=2021-04-29&endDT=2022-12-30. Date can be on the x axis and Discharge can be on the y axis, then each annual peak value will be a point on the plot. 
4. Display horizonal lines for the flood-frequency statistics. These values come from our gage statistics, we want to be able to plot all of the x-percent AEP flood values that a gage has.
![image](https://user-images.githubusercontent.com/59063181/190190718-8934c09b-b9fc-41e4-8f86-54a87ec50fd6.png)
The above image shows all of the x-percent AEP flood values that a gage _could_ have, sometimes they will only have some of these and sometimes they will have none. To get all the statistics for a certain gage you will use the service call: https://test.streamstats.usgs.gov/gagestatsservices/stations/02173500. For a better view of what this json looks like you can use our [service documentation ](https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Station) or just find a json viewer online (https://jsonformatter.org/json-pretty-print). After you make that call and get the returned object you will need to sort through the `statistics` array and get the `value` of those with `regressionTypeID` equal to the IDs in the image above. So look for IDs equal to 9, 852, 8, 4, 7, 3, 6, 1, 501, 5, 2, 500, 851, 1438, then plots those values as horizontal lines in the plot.
5. Plot the daily values as a line (this is the blue line from the NWS Gage Analysis Plot). The call to NWIS for daily values is: https://nwis.waterservices.usgs.gov/nwis/iv/?format=json&sites=02173500&parameterCd=00060&startDT=2022-04-29&endDT=2022-12-30. 
6. Add inputs so the user can enter a start and end date. Have two input boxes that allow the users to select a start date and an end date, then once the user clicks a button the plot should update to only show the values between those two dates. You should be able to configure the two NWIS calls with your start and end dates. 

**Functionality we also want from the NWS Gage Analysis Plot**:
- [ ] Show annual peaks and horizonal flood statistic lines with same colors - I think we need more information on this
- [x] Zoom into graph

**Tips:**
- If you go to https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000, right click "View Source", you will be able to view the source code for that webpage along with all of its plots. The developer who wrote this page said we could look and use the code. The plot we want to recreate has an id of "dischargegraph." A couple of the functions and sections of code that are used to create that plot and that could be helpful to look at are
    - Lines 97-165 - HTML code used to display the plot
    - Line 4407 - 4431 - LoadQ, used to get new data after new dates and the 'Load Primary Data' button is clicked.
    - Lines 4520-4579 - Gets the nwis data for plotting
- Thresholds also does something similar. https://test.wim.usgs.gov/thresholds/#/ zoom into somewhere and turn on the streamgages layer and click on a gage. It will show a plot of the daily values. The code for Thresholds is here, https://github.com/USGS-WiM/Thresholds.
- Make new branches based on the SC-Runoff branch for this issue. Pull requests should merge into the SC-Runoff branch. We will need to manually close issues after merge requests are completed, since we are not merging into the default branch
- Old issue https://github.com/USGS-WiM/StreamStats/issues/1371 (has some helpful images)

**Comment by maggiejaenicke** [comment]
Closed with PR #1496. Adding functionalities to this plot with issue #1498.
