### ISSUE TITLE
BP: Add "Select State/Region" dropdown

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1457]
Part of #1455 

- [x] Create a dropdown that says "Select State / Region:"
- [x] Make a service call to https://streamstats.usgs.gov/nssservices/regions to retrieve the list of all the Regions
- [x] Populate the dropdown with the "name" of each Region 
- [x] Also create a checkbox that says "Basin Delineation", which gets forcibly selected when a State/Region is selected

Note: we may need to refine this, as there are some regions like "Undefined" that we may not want to include.

**Comment by laws-spatial** [comment]
- [x] Add filter for "Undefined" region name
