### ISSUE TITLE
BP: Add user information and submit

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1460]
Part of #1455 

- [x] Add a text box that says "ID Field:". Add a "?" icon next to this element, so that users can hover over the icon and get more information about what this means. 
     - Example of "?" icon with mouseover: go to https://dev.streamstats.usgs.gov/sc-runoff/ and search for coordinate 34.01174, -80.96048 in the search box. Select "South Carolina" as the region and delineate at the coordinate. Click "Continue". Click "Peak Flow Statistics" and "Continue". Click "Open Report". It will be visible on the top of the report ([image](https://user-images.githubusercontent.com/40237491/230174870-a26acf7d-8c08-49d9-893a-d00ce4d7af2e.png)). ([Link to associated code](https://github.com/USGS-WiM/StreamStats/blob/SC-Runoff/src/Views/reportview.html#L37L42))
- [x] Add a file uploader button that says "Upload Shapefile (.zip):" 
- [x] Add a text box that says "Email Address:"
- [x] Add a button at the bottom of the form that says "Submit Batch". 
- [x] Required elements should be outlined in yellow when incomplete. A "Parameters Must Be Entered Before Results Can Be Calculated" message should also appear at the bottom of the form
     - You can see a good example of this by delineating a basin in Colorado and clicking "Open Storm Runoff Models": 
[image](https://user-images.githubusercontent.com/40237491/230176757-23bacd6e-a855-43ba-af26-74f6a81331f5.png)
- [x] The "Submit Batch" button should be disabled unless the following criteria are met:
     - [x] A State/Region was selected
     - [x] "ID Field" is not empty 
     - [x] Email address is not empty
     - [x] A .zip file was uploaded 
 - [x] When the user clicks the "Submit Batch" button, do the following:
      - [x] Notify the user via a green/success toast message: "The batch was submitted successfully. You will be notified by email when results are available."
      - Note: will make a separate issue for actually submitting the batch via the BatchProcessor service.

**Comment by alaws-USGS** [comment]
Note: tooltip functionality through class="report-tooltip" should be the same as SCRunoff when both batchprocessor and SCRunoff are merged into SS. Confirmed by adding copying .report-tooltip from SCRunoff branch to working branch in **BP** in main.css. After confirmation, discarded changes to main.css in batchprocessor branch.

**Comment by alaws-USGS** [comment]
@amedenblik For
"""
Required elements should be outlined in yellow when incomplete. A "Parameters Must Be Entered Before Results Can Be Calculated" message should also appear at the bottom of the form
"""

Would a match to what the current SS says be more appropriate?
"A scenario OR one or more basin characteristics from the dropdown above must be selected to continue"

**Comment by amedenblik** [comment]
Confirmed with Pete M that we'd like to allow users the option to run the new BP with only delineations requested. We don't need to require at least one BC or Flow Stat.

**Comment by alaws-USGS** [comment]
Sounds good!

**Comment by amedenblik** [comment]
Closed with #1599
