### ISSUE TITLE
BP: Create URL parameter

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1462]
Part of #1455 

- [x] Add a URL path such as https://streamstats.usgs.gov/ss/bp/submit, so that when a user accesses that link, it automatically opens the BP modal and goes to the "Submit Batch" tab.
- [x] Add a URL path such as https://streamstats.usgs.gov/ss/bp/status, so that when a user accesses that link, it automatically opens the BP modal and goes to the "Batch Status" tab.
     - [x] Add a URL path parameter https://streamstats.usgs.gov/ss/bp/status?email=person@example.com, so that when a user accesses that link, it automatically opens the BP modal, goes to the "Batch Status" tab, and filters the results by the requested email address.
- [x] Add a URL path such as https://streamstats.usgs.gov/ss/bp/streamgrid, so that when a user accesses that link, it automatically opens the BP modal and goes to the "Download Stream Grids" tab.

**Comment by amedenblik** [comment]
Hints: relevant code from another project: https://code.usgs.gov/StreamStats/clients/information-portal/-/blob/dev/index.html#L538

Which handles this URL with a region parameter: https://test.streamstats.usgs.gov/information-portal/?region=AZ

This would capture the URL parameters. If the URL parameters are there, then use the Modal Service methods to open the modal.

**Comment by amedenblik** [comment]
Thoughts from Erik:

This seems hacky but I think you could just get your window href using window.location.href  , reading the URL param and then resetting the href to 'window.location.href = 'https://dev.streamstats.usgs.gov/bp/'   to load the page as it exists. and call the method to open the modal.

 Maybe using the $routeParams service would be more AngularJS-y though.

**Comment by harper-wavra** [comment]
https://streamstats.usgs.gov/ss/?BP=submit- submit page
https://streamstats.usgs.gov/ss/?BP=status - status page
[https://streamstats.usgs.gov/ss/?BP=status?email=person@example.com](https://streamstats.usgs.gov/ss/?BP=status&email=person@example.com) - users batches
https://streamstats.usgs.gov/ss/?BP=streamgrid - streamgrid page
https://streamstats.usgs.gov/ss/?BP=queue - queue page
