### ISSUE TITLE
Additional Functionality for Annual Flow Plot with Flood-Frequency Statistics

### ISSUE THREAD

**Issue by maggiejaenicke** [USGS-WiM/StreamStats#1498]
**Tips:**
- Make new branches based on the gageplots branch
- See issue https://github.com/USGS-WiM/StreamStats/issues/1424 for details on the creation of these plots.
- See comments in pull request #1496 

**Functionalities to add:**

- [x] #1514

- [x] **Add inputs so the user can enter a start and end date.** Have two input boxes that allow the users to select a start date and an end date, then once the user clicks a button the plot should update to only show the values between those two dates. You should be able to configure the two NWIS calls with your start and end dates. For an example, see the [weather.gov page](https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000), right click "View page source", and search for "dischargeStart" and "dischargeEnd". 

- [x] **Add a button to AEP PlotLines turn AEP PlotLines off and on.** Some charts have AEP lines that are very close together (ex: 06177720), which appear very cluttered. The user can zoom in to get a better view of the lines, but it might be useful to have a functionality to turn them off and on so that the user can view the entire plot without it being obscured by the lines. Something like [this](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/axis-addplotband/) might work. [Highcharts site](https://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines) documentation on adding and removing -- see "dynamically update."

- [x] Change the default zoom to "all" (part of the rangeSelector). Because the daily values are used for the navigator (timeline slider), the default zoom includes just the daily values. This usually isn't a problem and all the data are visible, but this plot (02173500) is an example of where you miss data on the initial load. 

- [x] Add the ability to view the plot in log scale. A checkbox would probably be ideal. This functionality is available in the [weather.gov plot.](https://www.weather.gov/source/aprfc/gageAnalysis.html?site=1234000). 

- [x] Add these statistic IDs: 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318

**Comment by amedenblik** [comment]
Closed with #1515
