### ISSUE TITLE
Gageplots loading issue 

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1500]
When the `gageplots` branch is deployed (https://dev.streamstats.usgs.gov/gageplots/), the plot does not load on the Gage Analysis Plots tab of the Gage Page:

![image](https://user-images.githubusercontent.com/40237491/211625035-4f057391-b735-4ee1-a21b-52fbadb8f14a.png)

There are numerous console errors:
![image](https://user-images.githubusercontent.com/40237491/211625113-69788ab2-d92c-45e7-a4e3-6bbd84fa3084.png)

This issue does not happen when running the `gageplots` branch locally, but I suspect that it occurs because the gage plot is being rendered before the data is ready. A first attempt at this issue would be initiating the gage plot *after* all dependent data has been loaded. We should also consider adding a spinning loader for the location where the plot should be.

**Comment by harper-wavra** [comment]
https://stackoverflow.com/questions/40225020/how-to-solve-typeerror-cannot-read-property-chart-of-undefined
https://stackoverflow.com/questions/41244791/cannot-read-property-chart-of-undefined-highcharts-ng
