### ISSUE TITLE
Large Basins not working - unit hydrograph

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1546]
I tried point 33.261423516334474, -80.88909387588501 on the dev site and was receiving a 413 error from the calculatemissingparametersSCSUH endpoint. 413 error means 'Request Entity Too Large.'

If you run through the workflow at that point, you should be able to get the request body that is failing.

**Comment by harper-wavra** [comment]
The response from the delineation request has a content length of 1,256,962. We reuse the response of this request to send the delineation to calculatemissingparametersSCSUH.

If you look at the request to calculatemissingparametersSCSUH in the network tab you can see the content-length is 1,215,170.
Howevever if I keep going through the workflow the content-length of the bylocation call to NSS is 21725, which also uses the polygon.

May need to look at the client and see if there is any simplification happening to the request to NSS that we can use here.

**Comment by harper-wavra** [comment]
Related Issue: https://github.com/USGS-WiM/wim-infrastructure/issues/325

**Comment by amedenblik** [comment]
Closed with #1549
