### ISSUE TITLE
Add USLE & MUSLE Results

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1566]
On the Syntenic Unit Hydrograph tab, there should a button for users to calculate USLE & MUSLE results. Along with all previous inputs they will need to enter 
1.  county name (r factor tab)
2.  soil name (k factor tab) will also needed in https://github.com/USGS-WiM/StreamStats/issues/1565
3.  slope length (ls factor tab)
4.  slope steepness (ls factor tab)
5.  cover name (c factor tab)
6.  practice name (p factor tab)

**Comment by amedenblik** [comment]
Closed with #1577
