### ISSUE TITLE
Add Google Analytics tag for PROSPER

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1578]

**Comment by harper-wavra** [comment]
& update https://doimspp.sharepoint.com/:x:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B759edfb9-01a6-48cb-807e-1f65561fde80%7D&action=editnew&cid=e0d6a875-43bb-493e-8094-b3cbd2c90717
