### ISSUE TITLE
Fix geosearch bar

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1610]
The geosearch bar is not working.

Console message: `search_api 2.1 WARNING [_search #searchBox]: api service error: timeout`

Example query: https://txdata.usgs.gov/search_api/2.1/services.ashx/search?term=123&search_states=ALL&lat_min=-90&lat_max=90&lon_min=-180&lon_max=180&include_gnis_major=true&include_gnis_minor=false&include_state=true&include_zip_code=true&include_area_code=false&include_usgs_sw=true&include_usgs_gw=true&include_usgs_sp=true&include_usgs_at=true&include_usgs_ot=true&include_huc2=true&include_huc4=true&include_huc6=true&include_huc8=true&include_huc10=true&include_huc12=true&top_n=50&caller=jsapi_2.1

Response: `{"error":"Invalid Query"}`

**Comment by harper-wavra** [comment]
Seems to have fixed itself.
