### ISSUE TITLE
Add loader to BP 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1615]
Add some loaders to the BP modal
- [x] While waiting for statistic groups to load. Could just have a spinner where they will appear.
- [x] While waiting for basin characteristics to load. Could just have a spinner where they will appear.
- Others?

**Comment by alaws-USGS** [comment]
Have spinner appear as well when switching between selected regions/states

**Comment by alaws-USGS** [comment]
Ng-hide elements when list is not around.

**Comment by amedenblik** [comment]
Closed with #1628
