### ISSUE TITLE
BP: loader bug

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1631]
Follow-up to #1615 (missed this bug)

Steps to recreate:
1. Do not select a State / Region
2. Check "Compute Flow Statistics" and "Compute Basin Characteristics"
3. The loading spinners appear in the "Select Flow Statistics" and "Select Basin Characteristics" areas

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/56c7e2fd-84f2-424e-8110-d05c56d2a881)

When a State / Region is not selected:
- Hide the "Select All Flow Statistics" and "Select All Basin Characteristics" buttons
- Hide the spinner
- Show text that says "Please select a State / Region to select Flow Statistics" and "Please select a State / Region to select Basin Characteristics"

**Comment by alaws-USGS** [comment]
I have the fix for this and will do this once #1601 is completed.

**Comment by amedenblik** [comment]
Closed with #1656
