### ISSUE TITLE
BP: Some BCs not appearing until Flow Statistic is selected

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1646]
How to recreate:

1. Select Alaska as State/Region
2.  Check "Compute Flow Statistics" and "Compute Basin Characteristics"
3. Note how there are only 2 BCs: DRNAREA and PRECPRIS00
4. Check "Peak-Flow Statistics"
5. Note how the ELEV BC has showed up

All BCs should show up in the Basin Characteristic list from the start

**Comment by alaws-USGS** [comment]
@amedenblik I investigated this issue. I believe this is an issue with the list of parameters found at https://test.streamstats.usgs.gov/streamstatsservices/parameters.json?rcode=AL, which does not contain ELEV. ELEV is being added to the list of basin characteristics (availableParamList) based on the checked flowstats by the code below, which ensures that all flowstats that are asked for will have all the necessary basin characteristics to go with them.

https://github.com/USGS-WiM/StreamStats/blob/4c2044915cb49a97553e10a5889664da678be480/src/Controllers/BatchProcessorController.ts#L331C17-L366C30

**Comment by alaws-USGS** [comment]
https://github.com/USGS-WiM/StreamStats/blob/4c2044915cb49a97553e10a5889664da678be480/src/Controllers/BatchProcessorController.ts#L331C1-L366C30
