### ISSUE TITLE
Enable WY flowstats

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1652]
Edit appconfig:
`{ "RegionID": "WY", "Name": "Wyoming", "Bounds": [[40.994289, -111.053428], [45.002793, -104.051705]], "Layers": {}, "Applications": [], "regionEnabled": true, **"ScenariosAvailable": true**, "URL": "https://www.usgs.gov/streamstats/wyoming-streamstats" }`

I made this change on dev & asked Pete to take a look, if he says it looks good we can make this change and push to test and prod.

**Comment by amedenblik** [comment]
Per Pete's approval, I made this change on Test and Prod.
