### ISSUE TITLE
Order Stream Grids table by alphabetical State / Region name

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1664]
Should be a quick fix. Currently they are not sorted and Delaware ended up at the bottom because I updated the FileName in the database: 

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/620da7c2-cd12-495a-9f57-f1fc3d7df1a1)

**Comment by amedenblik** [comment]
@harper-wavra I accidentally pushed to the batch-processor branch 🤦‍♀️ Can you please take a look and close the issue if you think this is fine?

**Comment by harper-wavra** [comment]
I approved this one & merged it in, https://github.com/USGS-WiM/StreamStats/pull/1662

**Comment by harper-wavra** [comment]
Looks good 👍
