### ISSUE TITLE
Gageplots Feedback - Annual Peak Streamflow plot

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1707]
More feedback may be added later! This is what we have received so far.

- [x] Consider adding option for a log scale
- [x] It should be noted that the % AEP flows are the at-site stats as opposed to the weighted %AEP flows (weighting of at-site values with regression values)
     - Maybe add a dropdown for data sources for each plot -- this way users can see exactly what stats/data is being used (see #1709)
     - (Awaiting guidance from Pete M on the wording of the note)
- [x] "It’s confusing that the x-scale shown for the peak flows is only correct for the default window"
     - [x] We're going to try: if the x-scale is zoomed to be greater than 1 year, plot the points on their actual year & uncheck the "Plot Annual Streamflow Peaks on Latest Year" box  
     - [x] Consider allowing an option to plot the peak flows on any user-specified year: drop-down options would be to plot points on actual date, 2023, 2022, 2021, etc... 
- When you use the slider at the bottom of the graph, all the peak flows get pushed to the far right. It would be better if only the peak flows associate with the period chosen on the slider would show up and use the x-scale being used for the daily mean streamflow.
     - See previous point 
- [x] For some sites (06334330 for example) the annual peak streamflow plot loads in blank and only by zooming out the slider can one see the peak flow values. Looks like the peaks are plotting on the wrong year for some reason:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/a67fc1ab-d934-4bb6-b0fd-9c5c8698a79f)
     - This may occur because the most recent year is determined based on the daily streamflow data, which is unavailable for this site

- [x] This one (06127900) seems to be having problems too

- [x] Add these statistics to the drop-down statistic group options:
     - Weighted AEP Statistics: 
          - Weighted 80% AEP: 1065
          - Weighted 66.7% AEP: 20
          - Weighted 50% AEP: 513
          - Weighted 42.9% AEP: 512
          - Weighted 20% AEP: 21
          - Weighted 10% AEP: 22
          - Weighted 4% AEP: 23
          - Weighted 2% AEP: 24
          - Weighted 1% AEP: 25
          - Weighted 0.5% AEP: 26
          - Weighted 0.2% AEP: 27
     - Regulated AEP Statistics:
          - Regulated 80% AEP: 1328
          - Regulated 66.7% AEP: 517
          - Regulated 50% AEP: 516
          - Regulated 42.9% AEP: 518
          - Regulated 20% AEP: 519
          - Regulated 10% AEP: 520
          - Regulated 4% AEP: 521
          - Regulated 2% AEP: 522
          - Regulated 1% AEP: 523
          - Regulated 0.5% AEP: 524
          - Regulated 0.2% AEP: 525
- [x] Switch plot to water years (October 1 - September 30)
          - Change peakOnYear dates and mechanism for switching dates with dropdown (choosePeakYear function)
          - Adjust initial load x axis range
          - Change wording for checkbox/select year

**Comment by amedenblik** [comment]
Added comments from Seth and Toby

**Comment by amedenblik** [comment]
@USGSPMM3 

Regarding this item: "It should be noted that the % AEP flows are the at-site stats as opposed to the weighted %AEP flows (weighting of at-site values with regression values)"

Can you please provide guidance on the wording for this note? And where should the note be on the page? We were thinking here:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/c913f9f4-7581-4d0a-86d1-dbcb0b09bd1c)

**Comment by maggiejaenicke** [comment]
@USGSPMM3 @amedenblik @harper-wavra Could any of you point me to a gage that has Weighted and Regulated AEP Statistics? I want to check that the data I added will show up at the appropriate gages.

**Comment by amedenblik** [comment]
Yes, here are a few! Let me know if this isn't what you're looking for or if you want more examples.

01430000
03132000
03138500
02112000

Saving this database query for future reference:
`SELECT * FROM "Stations" WHERE "ID" IN (SELECT "StationID" FROM "Statistics" WHERE "RegressionTypeID" IN (SELECT "ID" FROM "shared"."RegressionType" WHERE ("Name" ILIKE '%regulated%')  AND "StatisticGroupTypeID" = '2' AND "Name" NOT ILIKE '%skew%' ORDER BY "StatisticGroupTypeID")) AND "IsRegulated" = TRUE AND "Code" IN (SELECT "Code" FROM "Stations" WHERE "ID" IN (SELECT "StationID" FROM "Statistics" WHERE "RegressionTypeID" IN (SELECT "ID" FROM "shared"."RegressionType" WHERE ("Name" ILIKE '%weighted%')  AND "StatisticGroupTypeID" = '2' AND "Name" NOT ILIKE '%skew%' ORDER BY "StatisticGroupTypeID")) AND "IsRegulated" = TRUE)`

**Comment by USGSPMM3** [comment]
@maggiejaenicke @amedenblik 
Several comments:

- are we still allowing users to select low-flow statistics in the dropdown menus, like 7Q10? If so, we should change the heading from "Show Flood Statistics" to "Show Streamgage Statistics" or even "Show Streamgage Frequency Statistics". 
- I am struggling with how to describe all variations of the flow statistics (at-site, regression, and at-site weighted with regression, and alternate (could be some other method like MOVE3)
- I'm thinking that we could say "Statistics are computed using at-site streamgage data or estimated using record extension or regional estimation methods. Please see https://streamstats.usgs.gov/information-portal/ (or a link to the gage stats for that gage) for more detailed information"
- Or, we add a little info button that links to the definition for whatever stat label we are displaying? Those don't specifically state at-site or weighted.

**Comment by maggiejaenicke** [comment]
@USGSPMM3 

> @maggiejaenicke @amedenblik Several comments:
> 
> * are we still allowing users to select low-flow statistics in the dropdown menus, like 7Q10? If so, we should change the heading from "Show Flood Statistics" to "Show Streamgage Statistics" or even "Show Streamgage Frequency Statistics".
> * I am struggling with how to describe all variations of the flow statistics (at-site, regression, and at-site weighted with regression, and alternate (could be some other method like MOVE3)
> * I'm thinking that we could say "Statistics are computed using at-site streamgage data or estimated using record extension or regional estimation methods. Please see https://streamstats.usgs.gov/information-portal/ (or a link to the gage stats for that gage) for more detailed information"
> * Or, we add a little info button that links to the definition for whatever stat label we are displaying? Those don't specifically state at-site or weighted.

Yes we have low-flow statistics as options in the dropdown. I'll change it to "Show Streamgage Statistics" but let me know if you prefer the other or something else!

I like both ideas for the statistics note, and I think we could even do a bit of a hybrid between them. We could go with the message you wrote but have it change slightly depending on what statistic group we're displaying. For example:
_"**Low-flow statistics** (hyperlink to definition) are computed using (**info specific to those stats**). Please see https://streamstats.usgs.gov/information-portal/ (or a link to the gage stats for that gage) for more detailed information"_
We could swap out the bold parts depending on what statistic group is selected. 

Could you point me to definitions for the different statistics? Is there something within StreamStats/USGS I should use?

**Comment by maggiejaenicke** [comment]
@amedenblik 

> Yes, here are a few! Let me know if this isn't what you're looking for or if you want more examples.
> 
> 01430000 03132000 03138500 02112000
> 
> Saving this database query for future reference: `SELECT * FROM "Stations" WHERE "ID" IN (SELECT "StationID" FROM "Statistics" WHERE "RegressionTypeID" IN (SELECT "ID" FROM "shared"."RegressionType" WHERE ("Name" ILIKE '%regulated%') AND "StatisticGroupTypeID" = '2' AND "Name" NOT ILIKE '%skew%' ORDER BY "StatisticGroupTypeID")) AND "IsRegulated" = TRUE AND "Code" IN (SELECT "Code" FROM "Stations" WHERE "ID" IN (SELECT "StationID" FROM "Statistics" WHERE "RegressionTypeID" IN (SELECT "ID" FROM "shared"."RegressionType" WHERE ("Name" ILIKE '%weighted%') AND "StatisticGroupTypeID" = '2' AND "Name" NOT ILIKE '%skew%' ORDER BY "StatisticGroupTypeID")) AND "IsRegulated" = TRUE)`

Is there a way to query for specific RegressionTypeIDs? I'm looking at the gagestatsservices urls for these gages and not seeing any of the RegressionTypeIDs listed in the issue. 

Here are the gagestatsservices pages for those gages:
[01430000](https://test.streamstats.usgs.gov/gagestatsservices/stations/01430000)
[03132000](https://test.streamstats.usgs.gov/gagestatsservices/stations/03132000)
[03138500](https://test.streamstats.usgs.gov/gagestatsservices/stations/03138500)
[02112000](https://test.streamstats.usgs.gov/gagestatsservices/stations/02112000)

**Comment by amedenblik** [comment]
> Is there a way to query for specific RegressionTypeIDs? I'm looking at the gagestatsservices urls for these gages and not seeing any of the RegressionTypeIDs listed in the issue.

I may have messed up with my database query for those gages.

You can query gages by RegressionTypeID like this:

https://streamstats.usgs.gov/gagestatsservices/stations?regressionTypes=1065 (for just one ID)

https://streamstats.usgs.gov/gagestatsservices/stations?regressionTypes=1065,20,513 (Comma-separated list of regression type IDs)

Documentation: https://streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations

**Comment by amedenblik** [comment]
Sorry, accidentally closed!

**Comment by USGSPMM3** [comment]
>Could you point me to definitions for the different statistics? Is there something within StreamStats/USGS I should use?

In the "Statistic Type" of the https://streamstats.usgs.gov/information-portal/, you can find the definition for each stat label however I don't know how helpful those may be. Some of the stats description indicate "regression" but many of them do not indicate they are computed using data from the streamgage. @amedenblik and @harper, do we want to add more fields, create a separate table just for the gage plots, or do you have some other way we should address this issue systematically? It may not matter outside of plots (yet)

**Comment by amedenblik** [comment]
@USGSPMM3 let's discuss this more at our next check-in

@maggiejaenicke for now, let's go with "Statistics are computed using at-site streamgage data or estimated using record extension or regional estimation methods. Please see the Gage Information tab for more detailed information." because we do not have a definition for groups of statistics (just individual statistics) and the definitions for individual statistics aren't always accurate for gages right now.

**Comment by amedenblik** [comment]
Closed with #1913
