### ISSUE TITLE
Gageplots Feedback - Stage vs. Discharge plot

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1708]
More feedback may be added later! This is what we have received so far.

- [x] Change "Show Flood Statistics" to "Show Streamgage Statistics"
- [ ] For some sites without measurement data, the stage vs. discharge plot won't plot discharge vs gage height for peak flows. Site 06326510 is an example. Stage vs. discharge plot should still show the annual peaks even though there are no measurements.
     - Replaced by #1924 
- [ ] Sometimes the scale on the stage vs. discharge plots cuts off some values. The default scale for 06125520 cuts off all but two values. Switching to the log scale shows the other values.
     - Replaced by #1925 
- [ ] Would it be possible to add the ability to show or hide measurements based on control conditions (the control column here: [USGS Surface Water for USA: Streamflow Measurements](https://nwis.waterdata.usgs.gov/nwis/measurements/?site_no=06209500))?
     - The control conditions _might_ be the same as the qualification codes listed here https://github.com/USGS-WiM/StreamStats/issues/1666
     - Replaced by #1927 
- [ ] I tried the option to download a jpeg from the stage discharge plot. In the image it generated the legend symbol doesn't match the symbols on the plot: 
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/c5e29e8c-7735-464b-95c2-164371f1b710)
     - We are getting rid of this option anyway
- [ ] "The Legend for the Age data should be placed in the upper left corner so that it is not covering data. Move this below data toggle options"
     - Replaced by #1921 
- [ ] "One other item I noticed while using the plots today, the text box describing the measurements in the stage vs. discharge plot displays in front of the dropdown menu, so you can't read the dropdown options if it's in the wrong place:"
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/1e34936d-76bb-4045-b7f2-8124515f3523)
This should be resolved when we move the legend off the plot (and reduce the options in the dropdown menu with this [issue](https://github.com/USGS-WiM/StreamStats/issues/1709))

**Comment by amedenblik** [comment]
Added feedback from Seth and Toby

**Comment by maggiejaenicke** [comment]
Broke this into individual issues so I'm closing this! 
Instead see: 
#1921 
#1924 
#1925 
#1927
