### ISSUE TITLE
Create Sediment Modal 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1723]
If a user delineates a basin in MN, there should be an option on the sidebar under "Select Scenarios" to "Configure Sediment Machine Learning Methods". When the user selects that a modal should appear. 

Inside that modal there should be inputs for a date range and streamflow.

See #1544 for additional details.

**Comment by amedenblik** [comment]
Update from 2023-10-03 conversation with Will Lund: we should limit the selectable date range to be 2006-01-01 and later. Include a "?" icon that shows this text when the user hovers: "Date range is limited to 2006 and later due to model limitations."

**Comment by amedenblik** [comment]
Closing in favor of issues listed in #1544
