### ISSUE TITLE
Not able to delete batch 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1730]
On https://dev.streamstats.usgs.gov/bp/ (or when running locally) when trying to delete a batch it fails. If you try on the internal site (https://staging-apps.usgs.gov/streamstats/bp/) it works. 

This is the error in the console: 
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/66fa0d55-eb88-4411-adb5-124d7df8a682)

**Comment by amedenblik** [comment]
Closed with #1731
