### ISSUE TITLE
BP - Check if scenarios are available

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1740]
We need to check if `ScenariosAvailable=false` in the appconfig. If it equals false, there should be no options for flow statistics. 

For example, if I select Connecticut River Basin in the BP I am currently able to select from 3 flow statistics. None should be available for selection because in the appconfig under CRB `"ScenariosAvailable": false`.

**Comment by amedenblik** [comment]
Closed with #1741
