### ISSUE TITLE
Incorporate excludePolygon endpoint

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1742]
_Waiting on services_

Since we are using sspourpoint & its exclude polygon endpoint in the BP we should also start using it in the client. I think we can work off the bp branch and push it out with that update.

**Comment by amedenblik** [comment]
Related issue? #920

**Comment by harper-wavra** [comment]
I think #920 will take some work from the GIS team to reassign exclude polygon types in the map services.

**Comment by harper-wavra** [comment]
Waiting on test ubuntu server.

**Comment by amedenblik** [comment]
Include a checkbox "Snap clicked point to stream grid" and check it by default
