### ISSUE TITLE
Rounding DA

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1779]
From Pete

"Here is info we can add to an issue on rounding DA. Which comes from OSW memo https://water.usgs.gov/water-resources/memos/memo.php?id=527"

`if available maps permit this precision, drainage areas should be published to the nearest square mile for areas greater than or equal to 100 square miles (mi2); to the nearest tenth of a square mile from 10 to 100 mi2, and to the nearest hundredth of a square mile for areas less than 10 mi2.`

**Comment by amedenblik** [comment]
From John:

https://doimspp.sharepoint.com/:w:/r/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc=%7B7B039BD9-4BF9-4FAF-BA7E-021310F69AC4%7D&file=Batch%20Processor%20developer%20guide.docx&action=default&mobileredirect=true

[ValueRounder.py.txt](https://github.com/USGS-WiM/StreamStats/files/12820822/ValueRounder.py.txt)

**Comment by amedenblik** [comment]
We are going to use #1786 instead
