### ISSUE TITLE
Streamgrid - access denied

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1791]
When trying to download a streamgrid from https://dev.streamstats.usgs.gov/ss/?BP=streamGrid, I am getting:
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/276432cd-9842-44e4-97da-c9f037c58212)

**Comment by amedenblik** [comment]
Commented about this issue here https://code.usgs.gov/WiM/wim-infrastructure/-/issues/367#note_525931

**Comment by harper-wavra** [comment]
I think I see the issue with the streamgrids, the link is https://s3.amazonaws.com/test.streamstats.usgs.gov/streamgrids/crb_strgrid.zip when it should be https://s3.amazonaws.com/dev.streamstats.usgs.gov/streamgrids/crb_strgrid.zip.

I wonder if we just havent pushed up the latest code yet.

**Comment by harper-wavra** [comment]
That was the issue, things should be working on dev now.

I updated dev, test and the internal site so they are all on the same page.
