### ISSUE TITLE
Consider adding instructions about zipped up folder

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1827]
Got a ticket about a user not being able to submit a batch. The issue was because the necessary files were nested inside the zipped folder instead of being at the top-most level. 

'We may need to refine our description for submitting a shapefile. The batch processor is expecting zipped files, rather than a zipped version of a folder containing the shapefile. So for example, the component files of the shapefile should be selected, then right-clicked and sent to a compressed folder. If you instead select a folder containing your shapefile, then zip that folder, the batch processor will be unable to read it.'

I thought Ryan's description was pretty good but may need to word-smith it a bit.

**Comment by amedenblik** [comment]
Alternatively, is it worth considering searching for the shapefile components in a sub-folder?
