### ISSUE TITLE
Change disclaimer about weighted regression regions

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1832]
See email "[EXTERNAL] RE: New StreamStats Batch Processor - Testers Wanted" for more info/context.

If a regression regions is less than 1% of the basin area, it is not included in equation weighting.

Pete has recommended we update the report disclaimer to provide more information about this. 

Waiting on updated text (or for the go-ahead to change the services to exclude this 1% rule).

**Comment by USGSPMM3** [comment]
@amedenblik 
Option A: Round % basin to nearest percent, then check and weight if value is not equal to 0. In this case we would end up with 1% and 99%.
Option B: Change rounding rule to 0.1%

Revisions: When each region is solved I'm wondering if we should put at the top "Estimates based region xxx equations" and then in the weighted results, "final results weighted based on xx% in region xxx and xx% in region y. "  This would remove the misconception that the value is based on 99.3% of the basin being IN that region.

**Comment by harper-wavra** [comment]
closing for https://code.usgs.gov/StreamStats/web-services-and-apis/NSSServices/-/issues/288
