### ISSUE TITLE
"NHD Features of Delineated Basin" feature not working

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1846]
This section of the report always seems to fail to provide features and throws errors when you try to print the report CSV. It previously worked. Not sure what may have changed.

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/5445d1ec-4250-462e-a714-b0e7d0fe76df)

See also https://github.com/USGS-WiM/StreamStats/issues/1571

**Comment by harper-wavra** [comment]
Worked at 33.89776, -80.69228

**Comment by harper-wavra** [comment]
Failed at 32.42453, -80.92225 with the following error:
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/0087be25-1e97-4d75-9718-97118ac46a41)

**Comment by harper-wavra** [comment]
33.55817, -80.46056 - streams listed twice

**Comment by amedenblik** [comment]
Closed with #1881
