### ISSUE TITLE
Disable DC catch basins below zoom level 16

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1849]
"I'm planning to approve the DC stormdrain QAQC for migration today but wanted to check on changing some view settings. Can we leave the storm drain inlets turned off until we get to a zoom level of 16 or higher? The inlets completely block all of the other map features and I don't think they're pertinent until you're zoomed way in and looking at very local delineations. I suspect we could do this with all of the stormdrain applications so we don't have custom setups for each one."

**Comment by amedenblik** [comment]
Temporary fix: set minZoom to 14 for DC stormdrain layers

**Comment by harper-wavra** [comment]
We figured out how to do this with just the map services. Waiting to hear if we should do the same with Mystic.

**Comment by amedenblik** [comment]
Change was also made to the Mystic.
