### ISSUE TITLE
Prepare BP for official deployment

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1861]
- [x] Remove yellow warning banner https://github.com/USGS-WiM/StreamStats/pull/1890
- [x] Remove the text "Preview Version" https://github.com/USGS-WiM/StreamStats/pull/1890
- [x] Ask John to redirect old BP to new BP
- [x] Update Drupal article (https://www.usgs.gov/streamstats/streamstats-batch-processing-tool)
- [x] Link to Drupal article in the BP modal https://github.com/USGS-WiM/StreamStats/pull/1890

**Comment by amedenblik** [comment]
@harper-wavra please review the Drupal article content here: https://doimspp.sharepoint.com/:w:/r/sites/StreamStatsTeam/Shared%20Documents/SS_TeamSpace/Original%20Batch%20Processor%20%26%20sshydro/New%20BP%20Drupal%20Article.docx?d=w714c00cdcb7f4a6fb40ce10faf2cc18e&csf=1&web=1&e=h8rLPd

New screenshot:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/5b857096-60b8-450e-8c39-b054c750eab9)

**Comment by harper-wavra** [comment]
Made a couple of small suggestions, but overall looked good!

**Comment by amedenblik** [comment]
Thanks! Emailed Tara with new content. Will close this issue once Drupal content has been updated.
