### ISSUE TITLE
BP: Download Stream Grids tab has double entries

### ISSUE THREAD

**Issue by alaws-USGS** [USGS-WiM/StreamStats#1876]
When navigating to the Download Stream Grids tab via the hyperlink on the Submit Batch tab, it causes the list of stream grids to double
![image](https://github.com/USGS-WiM/StreamStats/assets/108412194/267cad16-ed6b-4a7c-969f-f29906683a1e)

**Comment by amedenblik** [comment]
Possibly related to #1844
