### ISSUE TITLE
Basins not merging

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1905]
At around 33.59925, -80.62439 we noticed that not all the basins were merging together. I tried in a couple of other spots, and it seems if there are more than three points, we are having issues dissolving the polygons. 

![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/c5941e82-823d-4ca1-af23-d203154ab0ef)

**Comment by amedenblik** [comment]
While addressing this issue, we may want to look into this error:

This is around 33.89489, -80.17977 (this is one of the test sites that Kitty provided)

This line never successfully delineates: 
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/c698d510-c090-419e-9d51-7cc57d5936a7)

Error:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/699f8c80-18e1-48fa-8b1b-1e12472034f7)

**Comment by harper-wavra** [comment]
The issue with Kitty's test point seems to be coming from [self-intersections in the huc poly layer](https://github.com/USGS-WiM/StreamStats/assets/59063181/dca61fc7-4bdd-4f72-b974-11fc70adb98a). There are two points:
1. -80.36302773225532, 34.32068306629874 [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/38d4f908-564f-436b-a22a-a53acb7dc4a9)
2. -80.42593563430405, 34.34918481335387 [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/d21c4209-b28f-4b0d-aac6-c6e163338ba9)

**Comment by amedenblik** [comment]
Closed with #1942
