### ISSUE TITLE
Add "Loading..." messages to slow functions within Annual Peak Streamflow plot

### ISSUE THREAD

**Issue by maggiejaenicke** [USGS-WiM/StreamStats#1912]
The `togglePeakYear()` function includes a loading message using this code: 

            `let chart = $('#chart1').highcharts();`
            `chart.showLoading('Loading...')`

- [ ] Add "Loading..." messages to more functions that are slow

Potential functions that could use a loading message: 

- `choosePeakYear()`
- `resetZoom()`
- `dateRangePicker()`

**Comment by amedenblik** [comment]
A gage to use for testing might be 03138500. During the review of #1913, the plots never finished loading for me.

**Comment by maggiejaenicke** [comment]
Also want the loading message for the functions in `afterSetExtremes`

**Comment by maggiejaenicke** [comment]
> A gage to use for testing might be 03138500. During the review of #1913, the plots never finished loading for me.

Issue with 03138500 is an error regarding defaultTimeZone. I'll fix.
