### ISSUE TITLE
MN Sediment - Add configuration button to sidebar

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1915]
Parent issue is #1544 

## User Story

1. User navigates to the state of Minnesota 
2. In the "SELECT A STATE / REGION" section of the sidebar, user clicks the "Minnesota" button
3. In the "IDENTIFY A STUDY AREA" section of the sidebar, user clicks the "Delineate" button
4. User clicks a blue stream grid cell on the map and waits for the basin to delineate
5. In the "IDENTIFY A STUDY AREA" section of the sidebar, user clicks the "Continue" button
6. In the "SELECT SCENARIOS" section of the sidebar, below the "Basin Characteristics" section, a "Configure Sediment Machine Learning Method" button will appear

## Tasks

- [x] In the appConfig.js file, add "Sediment" to Minnesota's "Applications" list
- [x] If the "Sediment" application is enabled, add the "Configure Sediment Machine Learning Method" button
  - Hint: Look for the "Configure Flow Anywhere Method" button as an example

**Comment by njestes** [comment]
@amedenblik got a question on this statement in the second task: 

'If the "Sediment" application is enabled'

Is it enabled by virtue of the fact that it is in the Applications array for Minnesota?

a la: "Applications": ["Sediment"]?

Do I now just need to make sure the "Configure" button shows up when the selected state is MN?

**Comment by amedenblik** [comment]
> Is it enabled by virtue of the fact that it is in the Applications array for Minnesota?

Correct 👍

> Do I now just need to make sure the "Configure" button shows up when the selected state is MN?

In the future, we may want to enable the "Sediment" application for other states too, so we want the "Configure" button to show up when `this.regionservice.selectedRegion.Applications` contains "Sediment"

**Comment by amedenblik** [comment]
Closed with #1918 

(Issues are not closed automatically, since PRs are not merged into the default branch)
