### ISSUE TITLE
Stage vs. Discharge Plot - Move Legend for Age & Quality Data

### ISSUE THREAD

**Issue by maggiejaenicke** [USGS-WiM/StreamStats#1921]
- [ ] Move Legend for Age & Quality Data off the plot area so it is under the data toggle options
- [ ] Disable Legend when no USGS Measured Data is present (ex: 06326510)

- in `gagepage.html`, this is the "`ageQualityLegend-item`"

Replaces item in #1708

**Comment by amedenblik** [comment]
Closed with #1969
