### ISSUE TITLE
Stage vs. Discharge Plot - Fix plot scale so all values are shown in linear scale

### ISSUE THREAD

**Issue by maggiejaenicke** [USGS-WiM/StreamStats#1925]
Sometimes the scale on the stage vs. discharge plots cuts off some values. 
The default scale for 06125520 cuts off all but two values. Switching to the log scale shows the other values.
All values are also cut off on 05513450 & 03419000, but are shown when switched to log scale.

- [x] Fix plot scale so all values are shown when plot is in linear scale

Replaces item in #1708

**Comment by amedenblik** [comment]
Gage 02173500 (http://127.0.0.1:8080/src/?gage=02173500&tab=plots) seems to cut off some of the annual peaks in linear mode as well (ex. 2005)

**Comment by amedenblik** [comment]
Closed with #1974
