### ISSUE TITLE
Fix "No Data to Display" messages on Annual Peak Streamflow plot and Stage vs. Discharge plot

### ISSUE THREAD

**Issue by maggiejaenicke** [USGS-WiM/StreamStats#1936]
The Daily Streamflow raster plot has a "No Data to Display" message in the plot area when no data is present. 

- [ ] Fix "No data" message to the Annual Peak Streamflow Plot - it only shows up on the test plot when you zoom in
     - test plot: 05501600
- [ ] Add/Fix "No data" message to the Stage vs. Discharge Plot
     - haven't found a good test plot for this one--just makes sure it's working!

**Comment by maggiejaenicke** [comment]
Seems like this is actually working now!

**Comment by amedenblik** [comment]
"No data" message to the Stage vs. Discharge Plot -- test plot gage 021697451 (http://127.0.0.1:8080/src/?gage=021697451)
