### ISSUE TITLE
Self-intersections - Basins not merging 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1941]
Around 33.89489, -80.17977 (this is one of the test sites that Kitty provided)
This line never successfully delineates:
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/f0376143-fc13-40ea-a3e7-626d67758f03)
Error:
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/0240cf64-177e-4a42-9903-6d61c2be0351)
The issue with this point is coming from [self-intersections in the huc poly layer](https://github.com/USGS-WiM/StreamStats/assets/59063181/dca61fc7-4bdd-4f72-b974-11fc70adb98a). There are two points:

-80.36302773225532, 34.32068306629874 [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/38d4f908-564f-436b-a22a-a53acb7dc4a9)
-80.42593563430405, 34.34918481335387 [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/d21c4209-b28f-4b0d-aac6-c6e163338ba9)

**Comment by amedenblik** [comment]
Upgraded to `"@turf/turf": "^6.5.0",` in the package.json and am not getting the same error at 33.89489, -80.17977, but it also doesn't show the left basin at all:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/9ec5aa4f-78c9-4a75-84a8-df3a3b519034)
