### ISSUE TITLE
Streamgage Statistics not showing all options in dropdown

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1975]
For gage 12340000, not all the streamgage statistics are showing up in the dropdown:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/8de4dea9-913c-42bd-a852-b50a1610e1d2)

https://dev.streamstats.usgs.gov/gageplots/?gage=12340000&tab=plots

**Comment by maggiejaenicke** [comment]
@amedenblik What other stats does that gage have that should be showing up?

**Comment by amedenblik** [comment]
If you go to the Info tab > Streamflow Statistics section and select the "Peak-Flow Statistics" group, you can see that there are statistics for the 0.2-percent AEP flood, 0.5-percent AEP flood, etc. (Annual Exceedance Probability (AEP)). 

@USGSPMM3 do you know what other statistic groups we should be seeing here?

**Comment by maggiejaenicke** [comment]
@amedenblik @USGSPMM3 This is because all of these statistics are marked `"isPreferred": false`. I believe at one point we talked about filtering these out and just using `"isPreferred": true` (which in this case is just the Alternative AEP). Should I display all stats, regardless of `"isPreferred"`?

**Comment by USGSPMM3** [comment]
> @amedenblik @USGSPMM3 This is because all of these statistics are marked `"isPreferred": false`. I believe at one point we talked about filtering these out and just using `"isPreferred": true` (which in this case is just the Alternative AEP). Should I display all stats, regardless of `"isPreferred"`?

@maggiejaenicke  and @amedenblik For this site I was looking to see the non-peak flow statistics, such as the 7Q10 low flow statistic. Maybe we dropped those from the effort a while back and I forgot? As for other peak flow statistics, I do like using the IsPreferred:true for now. If we have requests later we can change it.

**Comment by amedenblik** [comment]
@USGSPMM3 We have included low flow statistics (see [comment here](https://github.com/USGS-WiM/StreamStats/issues/1537#issuecomment-1459453674) with a list) but for this particular gage, none of them are marked as IsPreferred = true:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/50ae12c9-9c99-47fe-bd37-4eb0f9076dfc)

**Comment by maggiejaenicke** [comment]
Working as expected. @USGSPMM3 Feel free to reopen if we want to adjust these settings.
