### ISSUE TITLE
Rural Hydrograph computational error

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1978]
SCDOT reports that USGS rural hydrograph computations for the 2% (50yr) and 1%(100 yr) hydrographs are much larger than expected.
[34.44148, -81.03518](https://github.com/USGS-WiM/StreamStats/assets/59063181/34cb97d0-7ed2-49d5-9353-9577cc749a69)

Issue seems to be with lines https://github.com/USGS-WiM/StreamStats/blob/SC-Runoff/src/Controllers/SCStormRunoffController.ts#L844-#L848, where if the AEP is 1 or 2, its also grabbing the results from 10 and 20 AEP results.

**Comment by amedenblik** [comment]
Closed with #1979
