### ISSUE TITLE
search API is slow after an option is selected

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#203]
look into this, and hook up toast notifications

**Comment by marsmith** [comment]
I think I have duplicated this and the other "UI oddity" bugs and the solution is consistent.  What happens here is that the search comes back immediately, but the map doesn't pan.  As soon as you move the mouse to the map, then it places the point immediately and zooms. 

So, i think they all can be summarized as when a map marker creation happens, there needs to be subsequent mouse/pointer movement for the action to start. 

Potentially angular leaflet bug

**Comment by jknewson** [comment]
I think there is a way to refresh the map after selection.

**Comment by marsmith** [comment]
map.invalidateSize();

I found is one way.  What seems to work is using map.setView(latlng, zoomlevel) instead of setting the leaflet directive center property.  

What are your thoughts?

**Comment by marsmith** [comment]
fixed for now pending Jeremy's ok with #226

**Comment by marsmith** [comment]
possibily related, there are angular leaflet warnings being thrown in the console every time the angular leaflet directive "center" property is changed:

![image](https://cloud.githubusercontent.com/assets/6529123/12021227/9720e06c-ad52-11e5-8562-59b222b000e6.png)

**Comment by marsmith** [comment]
Same UI issue mentioned in this issue:
https://github.com/tombatossals/angular-leaflet-directive/issues/497

they have a JSfiddle here where what we are doing works fine on a settimeout:
http://jsfiddle.net/jwpoehnelt/t58bpwkk/

**Comment by marsmith** [comment]
also reference here:
https://github.com/tombatossals/angular-leaflet-directive/issues/903

**Comment by marsmith** [comment]
closing for now with workaround in place
