### ISSUE TITLE
Text Edits to "About" modal

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#357]
Remove this paragraph:

> Separate applications have been established for each state that has implemented StreamStats. The State Applications link at the left provides access to a web page that shows where StreamStats is available and where it is being implemented. Users can select an individual state application from the map or the pull-down list on the State Applications page to view an introductory page for the state, which contains a link to the StreamStats user interface. The introductory pages explain any unique functionality that is available for the state and provides citations to reports that document the methods implemented for the state.

Change:

> Information for each state and regional application can be found by visiting the StreamStats state/region applications page here: http://water.usgs.gov/osw/streamstats/ssonline.html

to:

Introductory pages that explain any unique functionality, outline the general implementation level, and provide citations to reports documenting the methods implemented for each state and region are available here: http://water.usgs.gov/osw/streamstats/ssonline.html

**Comment by marsmith** [comment]
#387
