### ISSUE TITLE
tweak check for parameters out of limit so that if a value equals the limit , it is still ok

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#359]
![image](https://cloud.githubusercontent.com/assets/6529123/13014619/be3a745c-d182-11e5-8364-08193c0e5b98.png)

**Comment by marsmith** [comment]
I think this message is coming back incorrectly from the sevices, passing to jeremy

**Comment by jknewson** [comment]
I'm not getting any msg back with the above msg - maybe a fluke, I'm closing for now, but may need to reopen it. Below is the fiddler request used to test:

POST  http://commons.wim.usgs.gov/nssservices/regions/24/scenarios/estimate.json?statisticgroups=2&regressionregions=533&unitsystems=2 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Accept: application/json, text/plain, _/_
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=utf-8
Referer: http://localhost:55482/src/
Origin: http://localhost:55482
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

[{"StatisticGroupID":2,"StatisticGroupName":"Peak-Flow Statistics","RegressionRegions":[{"ID":533,"Name":"Peak_Piedmont_and_BlueRidge_Rural_2010_AHMMD","Parameters":[{"ID":1720,"Name":"Drainage Area","Description":"Area that drains to a point on a stream","Code":"DRNAREA","UnitType":{"ID":35,"Unit":"square miles","Abbr":"mi^2"},"Value":8.08,"Limits":{"Max":820.0,"Min":0.11}},{"ID":1721,"Name":"Percent Limestone","Description":"Percentage of area of limestone geology","Code":"LIME","UnitType":{"ID":11,"Unit":"percent","Abbr":"%"},"Value":0,"Limits":{"Max":81.7,"Min":0.0}},{"ID":1722,"Name":"Percent forest from MD 2010 land use","Description":"Percent forest from Maryland 2010 land-use data","Code":"FOREST_MD","UnitType":{"ID":11,"Unit":"percent","Abbr":"%"},"Value":23.5,"Limits":{"Max":100.0,"Min":2.7}}]}],"Links":[{"rel":"citations","Href":"http://localhost/NSSService/citations?regressionregions=533","method":"GET"}]}]
