### ISSUE TITLE
region list - flashes on change

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#39]
fix the region list so that it doesn't flash/change as much when changes occur. IE, only on zoom in and check if it has changed

**Comment by marsmith** [comment]
sometimes, also I've seen the region list doesn't appear at all, even if >=15 zoom

**Comment by marsmith** [comment]
I'm pretty sure what is happening here is that this happens when you zoom in more than one level too fast, the response from the region query doesn't come back before the new query is issued--- results in two or more sets of results coming back at the same time

**Comment by marsmith** [comment]
fixed
