### ISSUE TITLE
Implement News/Status information for SS users in version 4

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#436]
Add a pop-up to the initial load of version 4 that alerts users to any articles published in the Freshdesk system "Application Status -> Active News/Status" solutions folder.

Add a tab to the "About" modal that displays any articles in the Active News/Status folder, and also shows (collapsed in a accordion) any articles in the "Application Status -> Past News/Status" folder.

**Comment by marsmith** [comment]
addressed with #442
