### ISSUE TITLE
 forgot to point some of our popup controllers to appConfig file

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#444]
I have a vague idea of what is going on here, but the following chats will probably describe the issue better than if I put it into my own words: 

> I'm looking through the github site.... it looks like we forgot to point some of our popup controllers to appConfig file
> 
> marsmith 08:31
> what do you mean?
> 
> jknewson 08:32
> search the repository for http://ssdev.cr.usgs.gov
> in theroy this should only be located in appConfig.json file
> 
> marsmith 08:32
> oh crap
> ok
> right
> 
> jknewson 08:33
> yeah oops.. Its no big deal... I'll just tell him to search and replace http://ssdev.cr.usgs.gov in custom.min.js for now
> 
> marsmith 08:34
> or you want to just do a quick release
> can we just make those blank strings?
> 
> jknewson 08:35
> I guess we could.... What do you think about having configuration.baseurls have its own file, that doesn't get minified
> for easy updating?
> 
> marsmith 08:35
> probably solid
> or the whole thing?
> 
> jknewson 08:35
> no it should point to config.baseurl[streamstats] or something like that
> 
> marsmith 08:35
> but it does have the freshdesk token
> only got 236 users yesterday
> 
> jknewson 08:36
> I guess we could do the whole thing

**Comment by marsmith** [comment]
detach appConfig.js from minimize section, make sure refs to ssdev directly are all replaced with variable from appConfig

**Comment by marsmith** [comment]
implemented #450
