### ISSUE TITLE
Append unregulated flow statistics to report

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#463]

**Comment by jknewson** [comment]
Still has some issues with method.

**Comment by marsmith** [comment]
This is weird, sometimes it works, other time it throws an angular error in the console, I'm trying to track down

**Comment by marsmith** [comment]
Narrowed this down to a timing issue.  The 'unregulated' flow stats request is reliant on the first full basin request to have already come back. 

https://github.com/USGS-WiM/StreamStats/blob/master/src/Services/nssService.ts#L257-L265

suggest adding this line:
`if (!rr.Results || !rr.Parameters) setTimeout(() => { console.log('Waiting for flow results to be returned before inserting UnRegulated flow results') }, 1000);
`

**Comment by marsmith** [comment]
This is working now as far as I can tell, closing
