### ISSUE TITLE
multiple gages at same location.

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#486]
should list all gages at same location, currently only lists 1.

**Comment by HansVraga** [comment]
Could add tabs to the pop-up when more than one site is at the location.

**Comment by marsmith** [comment]
fixed, just append multiple results:

![image](https://cloud.githubusercontent.com/assets/6529123/26788104/2fe88bcc-49da-11e7-8c04-e0e2d4d8c69a.png)
