### ISSUE TITLE
Search Bar in step 1 won't load over https:// 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#490]
Using https:// in streamstats isn't possible because the search bar won't load - and that prevents the states from loading.

In order to use the "show your location" tool in the toolbox, you have to have a secure connection.

**Comment by marsmith** [comment]
looks like its up now:
https://txpub.usgs.gov/dss/search_api/1.1/web/index.html#tab4?top

**Comment by marsmith** [comment]
implemented in #547
