### ISSUE TITLE
Profile tool functions

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#491]
Tasks based on Ryan's email
- [ ] Verify green circle starts are the right end of the line
- [ ] Ensure y-axis label has correct units

> Hi Jeremy & Marty,
> 
> Based on an info request in my Science Center, I did some playing with the profile tool at a location in SD. My profile started in a downstream waterbody, then followed a str900 path upstream and into a slough. I really like the features of this tool- especially the way the little green circle traces along my line while I hover over the profile plot. I did notice a couple things, though. I think the y-axis values it shows are in meters, although the y-axis label shows the elevation as being in feet. It also seems like the little green dot might be starting from the wrong end of the profile line, such that when I'm hovering over the higher-elevation end of the plot, the green dot is starting at the lower-elevation end of the line.
> 
> Ryan

**Comment by HansVraga** [comment]
to fix: Hard Code Units on ESRI elevation request

**Comment by HansVraga** [comment]
http://elevation.arcgis.com/arcgis/rest/directories/arcgisoutput/Tools/ElevationSync_GPServer/Tools_ElevationSync/Profile.htm

**Comment by marsmith** [comment]
Can we test this? not sure if fixed, added 'feet' as unit on request though in #519

**Comment by marsmith** [comment]
fixed with #536

map ESRI elevation service [x,y,z] array Z units from meters to feet
