### ISSUE TITLE
Basin Characteristics in Shapefile

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#492]
See thread. There is a desire to include the Basin Characteristics in shapefile download.

> In version 4 of StreamStats, I've computed statistics for a basin and downloaded the shapefiles. The statistics show up in the report but the statistic attributes in the GlobalWatershed shapefile  are all zeros. Is the transfer of statistics to the shapefile not working at present? -Greg Kultan

and 

> In North Carolina, we would not consider that an enhancement. That is a basic functionality of the StreamStats package that has been available in previous versions and is expected by users. This should be a certainty, not a consideration, as our cooperators will be vocal about missing it.  -Kitty Kolb

**Comment by HansVraga** [comment]
Consider sending back characteristics as a .csv, or just send back everything as a GeoJson

**Comment by HansVraga** [comment]
Feedback from Kernell:
> For consistency in v4, it would be best to present both the StatLabel and the description for everything.

**Comment by marsmith** [comment]
Look at what the batch processor does, and potentially bundle a related table

**Comment by jknewson** [comment]
Done- just closeing
