### ISSUE TITLE
Fix 'clear delineation' and 'reset view' buttons

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#495]
maybe even have those buttons to a hard page refresh

**Comment by HansVraga** [comment]
- [ ] Remove "Reset View"
- [ ] for "clear delineation" it seems to break after you move on in the workflow to calculating flows

**Comment by marsmith** [comment]
fixed in #519

**Comment by marsmith** [comment]
'Clear basin' button does not clear any selected basin chars

**Comment by marsmith** [comment]
fixed with #521
