### ISSUE TITLE
Add "Below" to "Select a State or Regional Study Area"

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#496]
Add "Below" to the end of "Select a State or Regional Study Area"; in response to feedback that it wasn't intuitive when one state/area was displayed that it wasn't already selected.

**Comment by HansVraga** [comment]
(image for reference)
![image](https://cloud.githubusercontent.com/assets/12058013/16451721/aca66cfc-3dd2-11e6-98ed-e52abd10bafd.png)

**Comment by jknewson** [comment]
We could probably do an automatic select if there is only 1 state.

**Comment by marsmith** [comment]
Yea i was just thinking that (auto-select if one).  I'm not sure how this
button "looks selected" though.  hollow buttons usually aren't

On Wed, Jun 29, 2016 at 8:23 AM, Hans Vraga notifications@github.com
wrote:

> (image for reference)
> [image: image]
> https://cloud.githubusercontent.com/assets/12058013/16451721/aca66cfc-3dd2-11e6-98ed-e52abd10bafd.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-WiM/StreamStats/issues/496#issuecomment-229340057,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGOgY3NlbEFgH5KImFweJTbsTvGCRQP7ks5qQmOrgaJpZM4JBEqz
> .

## 

Martyn Smith
Cartographer
_marsmith@usgs.gov_ marsmith@usgs.gov
518.285.5618

NYWSC Webpage http://ny.water.usgs.gov/
Like us on Facebook https://www.facebook.com/USGSNewYork?_rdr
USGS Professional Page https://profile.usgs.gov/marsmith

**Comment by marsmith** [comment]
fixed in #516
