### ISSUE TITLE
add validation to selected BC's if BC failes add a refresh to reissue a request

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#512]

**Comment by HansVraga** [comment]
Ensure all BCs that were requested (to meet selected scenarios in NSS) are returned from ArcHydro. If not, put a toast error message with the missing characteristic. Force user to fill out characteristic before computing flows.

**Comment by marsmith** [comment]
made red if invalid:
http://www.coding-issues.com/2015/09/show-red-border-for-invalid-inputs-fields-on-form-submit-angularjs.html

**Comment by marsmith** [comment]
addressed in #527
