### ISSUE TITLE
Enable ESRI-based Network Navigation for whole country

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#514]
Currently limited to Rainy River Basin

**Comment by marsmith** [comment]
https://docs.google.com/spreadsheets/d/1BmlHKTJyj1NAgV1KImq1jevG1KjRPZloxi5zLcWPEvU/edit#gid=0

some additional things in here for network nav

**Comment by jknewson** [comment]
yeah, not going to happen. -StreamStats Coordinator slated this a non-goal. Network nav will be NLDI based.
