### ISSUE TITLE
Implement SSL, HTTPS

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#517]

**Comment by HansVraga** [comment]
TX has their Geosearch working on https://
but it sounds like parts of it doesn't work...

> You may already know this, but USGS water services and all of NWISWeb for that matter doesn't seem to be https yet.
> So our clientside stuff accessing NWISWeb water services all broke.
> They have a https staging area while they are transitioning that solved our problem.
> Put "staging" in normal NWISWeb urls to access, examples:
>     https://staging.waterservices.usgs.gov/
>     https://staging.waterdata.usgs.gov/tx/nwis/uv/?site_no=08123620&PARAmeter_cd=00065,00060,00054,62614,62615,62619,63158,63160
> I'm assuming this is a temp measure and at some point hopefully soon the "staging" can be dropped, like
>     https://waterservices.usgs.gov/
> 
> Good luck.

**Comment by marsmith** [comment]
TX geosearch and wim-styles upgraded to HTTPS.  Just need HTTPS on streamstats servers and we should be good.  test app here: https://marsmith.github.io/StreamStats/dist/

**Comment by HansVraga** [comment]
Testing the version available on SS Dev, still some insecure content:

![image](https://cloud.githubusercontent.com/assets/12058013/20903146/2974124a-bb08-11e6-88e4-945273d3cddb.png)

**Comment by marsmith** [comment]
addressed in #592, works as long as as one of the streamstats09 VM's is off
