### ISSUE TITLE
Hide "edit basin" toolbar for global watersheds

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#538]

**Comment by marsmith** [comment]
Moving this out of 4.0.6 for now.  stubbed in some code, we need an additional property or header on the watershed.json service that identifies if a basin is global or not

**Comment by marsmith** [comment]
leaving this for now, stub code in place, but streamstats services need to be updated so that GlobalWshd is not always = 1.

**Comment by HansVraga** [comment]
Needs https://github.com/USGS-WiM/StreamStatsServices/issues/44 before it can be fixed.

**Comment by harper-wavra** [comment]
Closing for https://github.com/USGS-WiM/StreamStats/issues/538
