### ISSUE TITLE
Warning missing from final report

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#549]
From Tana:
> Hello Ryan and Hans:
>       I have some exclusion polys in Oregon that allow delineations and BCs, and flow estimates, but they also warn the user about a problem if they delineate a basin from anywhere within that exclusion polygon.  V4 does warn the user in a pop-up window about exclusion poly warnings and the warning is listed inside the watershed attribute table, but I didn't see the warning in the final report. Do we want to add this to the report?

**Comment by marsmith** [comment]
I just looked at the code, these SHOULD be appearing in the final report.  I'm checking again now

**Comment by marsmith** [comment]
addressed in #592
