### ISSUE TITLE
adding basin characteristics doesn't allow continue

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#551]
I tried a few times to compute the BSHape and it failed so I tried to manually enter value 8.14 inorder to continue, but no dice.

![bcerror](https://cloud.githubusercontent.com/assets/8713714/20021187/5e11d1da-a29a-11e6-92e4-caa209c4f64f.JPG)

**Comment by marsmith** [comment]
fixed in #552
