### ISSUE TITLE
Users Manual - leverage Users manual freshdesk articles in UI

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#563]

**Comment by HansVraga** [comment]
From Big K:

>Marty,
>
>As you suggested, I've broken the user's manual up into several articles on Freshdesk.  There previously was a Users' Manual folder at https://streamstats.freshdesk.com/solution/folders/9000042933. I've put the articles in that folder. Previously, there was only one article there with a link to a pdf file of the entire users' manual. That is still there, but the manual is now substantially updated.  The individual articles are based on the updated manual. Please add a Users' Manual tab to the Help window with links to all of the articles there.

**Comment by marsmith** [comment]
fixed a while back
