### ISSUE TITLE
Naming shp Files prior to download

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#589]
Below is an enhancement request from a user. This isn't straightforward as one might think - will need to work out what options we actually have for this.

> Naming shp Files prior to download
> 
> Hello-
>  
> I am downloading shp files for several catchment areas.
>  
> Is there a way to associate a name to a catchment area and have this reflected in the shp and other supporting files being downloaded?
>  
> For example, if station name = XYZ, have the GlobalWatershed and GlobalWatershedPoint shp files named as XYZ_GlobalWatershed and XYZ_GlobalWatershedPoint prior to download.
>  
> Thanks for any assistance you can provide.  This is a great tool!
>  
> Andy Chapman │Biomonitoring Program │NH DES Watershed Management Bureau │PO Box 95 │Concord, NH 03302-0095 │ andrew.chapman@des.nh.gov │(603) 271- 5334
>  
> 
> https://streamstats.freshdesk.com/helpdesk/tickets/752
>

**Comment by jknewson** [comment]
Not going to do.
