### ISSUE TITLE
North Carolina peak flows are hosed

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#597]
![image](https://cloud.githubusercontent.com/assets/6529123/21275892/e433ad2e-c39c-11e6-8965-5c48ed790cbe.png)

**Comment by marsmith** [comment]
I can't find anything obvious, but I'm assuming this is an NSS regions table issue

**Comment by jknewson** [comment]
found the error, I seem to have forgotten to include "AND" and "OR" relational expressions in Expression ops... Adding them now.

**Comment by jknewson** [comment]
fixed by restructuring limitation criteria in nssdb and adding And/Or relational expressions
