### ISSUE TITLE
States w/ Basin characteristics only fail during regression query step.

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#603]
States w/ Basin characteristics only fail during regression query step.

![image](https://cloud.githubusercontent.com/assets/8713714/22424888/e057c21c-e6b5-11e6-80c2-d0f10a53ee97.png)

I'm thinking its due to:
https://github.com/USGS-WiM/StreamStats/blob/master/src/Services/StudyAreaService.ts#L460-L463

for Basin characteristics only sites, the scenario list will be 0,

**Comment by jknewson** [comment]
add in config file for short term. Longterm will be in exclusion polygon

**Comment by marsmith** [comment]
I think we can just set "sceariosAvailable" to false in appConfig for these states

**Comment by marsmith** [comment]
add SC, MS, WI, AZ to scenariosAvailable = false

**Comment by marsmith** [comment]
implemented with scenariosAvailable
