### ISSUE TITLE
unitsystem can be changed to configs

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#606]
the latest nss scenario endpoint has an added (optional) parameter to allow for a few special SS methods. such as limitations and flow coefficients. To enable these SS must include the configs=2 parameter for scenario requests. The parameter also sets the default units for ss to US customary.

So all that needs to be done is swap out unitsystem to configs
https://github.com/USGS-WiM/StreamStats/blob/master/src/appConfig.js#L33

**Comment by jknewson** [comment]
fyi, I already manually swapped it out on ssdev

**Comment by marsmith** [comment]
are you saying change it to: `'estimateFlows': '/scenarios/estimate.json?region={0}&statisticgroups={1}&regressionregions={2}&unitsystems=2&configs=2'`

**Comment by jknewson** [comment]
That will work, But I have it set up so configs=2 is the streamstats configuration so unitsystem is preset to = 2.. so its redundant. So you could just set it to 'estimateFlows': '/scenarios/estimate.json?region={0}&statisticgroups={1}&regressionregions={2}&configs=2'

and don't forget the scenarios one as well:
'statisticsGroupParameterLookup': '/scenarios.json?region={0}&statisticgroups={1}&regressionregions={2}&configs=2',

**Comment by marsmith** [comment]
implemented in #610
