### ISSUE TITLE
Errors being assigned wrong

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#608]
freshdesk ticket https://streamstats.freshdesk.com/helpdesk/tickets/1259

I think all that needs to happen is to assign the error based on the name of the error type:
![image](https://cloud.githubusercontent.com/assets/8713714/22901359/a1961512-f1ee-11e6-97b7-46b586a35073.png)
There are 4 different types of errors that could be returned with the results
>SE (Average standard error (of either estimate or prediction)
SEe (Average standard error of estimate)
SEp (Average standard error of prediction)
PC (Percent Correction)

**Comment by marsmith** [comment]
oh, nice thats easy

**Comment by marsmith** [comment]
fixed with #618
