### ISSUE TITLE
Basin characteristics only state

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#609]
Not sure if this one is in here or not, I looked and couldn't find a ref similar. but when working within a basin characteristics only state (MS, for example) the the continue method is blocked (PercentOverlay is empty). 

![image](https://cloud.githubusercontent.com/assets/8713714/22901908/83c55e74-f1f0-11e6-91d3-6826c21190b8.png)

**Comment by marsmith** [comment]
dup of #603, closing
