### ISSUE TITLE
Out of range disclaimer appears for multiple regions even though only applies to one

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#638]
test site: 02462600 in AL:

![image](https://cloud.githubusercontent.com/assets/6529123/23082971/a206e772-f529-11e6-8728-89ba9e73621d.png)

**Comment by jknewson** [comment]
See issue #659, has some suggestions

**Comment by HansVraga** [comment]
Jeremy suggest returning scenario-specific error message/warnings as part of the scenario, making it easier to attach to the specific scenario.

**Comment by marsmith** [comment]
Fixed with jeremy's services update:

![screenshot001](https://cloud.githubusercontent.com/assets/6529123/26456856/58d674dc-413c-11e7-90e7-d64c825061c6.jpg)
