### ISSUE TITLE
NSS parameter mismatch w/ SS basin characteristic 

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#644]
Currently when a scenario parameter is not available as a SS parameter the parameter gets lost and is not shown in either the select basin characteristic or "recalculate basin characteristic" section of the side bar. 

I think what should happen is if a scenario is selected which contains a BC that is not available on SS a msg in a toast notification stating that the characteristic is not available, and it is added to the list of parameters. So when continue is selected the parameter can be shown in the "recalculate BC" section so it can be manually populated so flow statistics can still be computed.

IA, BFI was an issue, but I have fixed it in the xml

**Comment by marsmith** [comment]
Fix in place in sidebarcontroller
