### ISSUE TITLE
Include the ability to search by Hydrologic Unit Code in search help

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#655]
Another bullet point to add to the search help (see image) but instead of "Watershed" it should read Hydrologic Units (HUC)

![image](https://cloud.githubusercontent.com/assets/12058013/23360787/52fd1fb8-fcbb-11e6-900a-73a76b3e0656.png)

**Comment by marsmith** [comment]
addressed, also included new updates to autocomplete address results with USGS search API tweaks I made, using 'dev' branch : https://github.com/usgs/search_api/
