### ISSUE TITLE
redelineating doesn't clear basin characteristics

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#656]
if I have delineated a basin, computed basin characteristics, and created a report, then decided to change to a different basin it appears that the user must use the "Start Over" button or the browser refresh button.  I attempted to use the "clear basin" tool and delineate a new basin, and calculate new basin characteristics.  I found that the previously computed basin characteristics to be populating the report.

**Comment by marsmith** [comment]
Wow I briefly looked into this just now, and have no idea whats going on.  It looks to me like everything gets cleared out when you press the "Clear Basin" button (when inspecting the scope)

**Comment by marsmith** [comment]
Tracked this down to the regionService.parameterList storing the old values.  Need to loop over this and clear values on 'clear basin' button click.  

These SHOULD have been getting overwritten but obviously aren't at the moment

**Comment by marsmith** [comment]
look into why values are getting into the regionService at all (they should not be)

**Comment by marsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/6529123/23554129/cd4c313a-fff1-11e6-9549-4b2e96616934.png)

**Comment by marsmith** [comment]
addressed in #664
