### ISSUE TITLE
Regulation disclaimer

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#658]
(MT request) report should always include a General Disclaimer when the upstream regulation has been checked even if there is no regulation?  For example, right now, if the upstream regulation is checked but is zero, there is no indication in the report that the upstream regulation was checked.  This, combined with issue #1 means that a basin could be highly regulated and if the user chooses not to check regulation the report looks like there is no regulation.

**Comment by marsmith** [comment]
done
