### ISSUE TITLE
Only first page prints when using IE (tested using IE11)

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#666]

**Comment by HansVraga** [comment]
We could add a warning for IE users that printing does not function properly?

**Comment by marsmith** [comment]
found some hints here, trying:
https://stackoverflow.com/questions/33735334/printing-iframe-in-ie-11-only-prints-first-page
https://jafferhaider.wordpress.com/2007/12/29/fix-for-the-firefoxcss-one-page-printing-bug/

**Comment by marsmith** [comment]
Implemented, first page is blank printing in IE11, but content is all there

**Comment by marsmith** [comment]
Opening this back up since apparently my fix broke print in Chrome

**Comment by marsmith** [comment]
try implementing an IE test for a CSS rule, like this:
https://philipnewcomer.net/2014/04/target-internet-explorer-10-11-css/

**Comment by marsmith** [comment]
fixed with above (hopefully)
