### ISSUE TITLE
Workflow advances from "Identify Study Area" to "Select Scenarios" without clicking continue

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#668]
In DRB, after a basin finishes delineating, the workflow (left-hand-bar) moves on to "Select Scenarios" without presenting the option to edit the basin/check water use or Continue.

We should make it work like other state/regions, where after delineation the user is presented with these options and needs to click "Continue" to move on to "Select Scenarios".

**Comment by HansVraga** [comment]
Jeremy reports this is true for whenever Scenarios are turned off - we should change it so the behavior is consistent for all states/regions; so, don't advance to the next step without user clicking "continue"

**Comment by jknewson** [comment]
closed with #681
