### ISSUE TITLE
to usgsFixed method need to be added to results view

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#669]
https://github.com/USGS-WiM/StreamStats/blob/staging/src/Views/reportview.html#L153

![image](https://cloud.githubusercontent.com/assets/8713714/25051616/d63dd976-210a-11e7-8d7a-d70f661c9546.png)

**Comment by HansVraga** [comment]
(see screenshot) Averaged standard error of prediction results are not hooked in. Perhaps others?

**Comment by marsmith** [comment]
fixed
