### ISSUE TITLE
Missing errors (Averages standard error of prediction is missing)

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#670]
NSS result Errors is a list of errors, currently I think we are just parsing out the SEe But we should be looping over errors array and populating all of them

 
![image](https://cloud.githubusercontent.com/assets/8713714/25053335/ed7847a8-2113-11e7-980a-3b000a9a5fe3.png)

There are currently 4 error types in the db, but not all equations use them all, some just 1, others more than 1

**Comment by marsmith** [comment]
fixed
