### ISSUE TITLE
IN Coordinated Reach Peak Flow calculations

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#671]
Add a method to calculate the Flow values on specific reaches in IN.

https://drive.google.com/open?id=0BygT1gkOzi3STlNkb2JETjYzY3o0OVk4aFpfVjZLdUZ5YWt3

**Comment by HansVraga** [comment]
Rough method for client-side implementation discussed

0) Are we in Indiana (coord reach flag) (client)
1) query to determine if coordinated react - if so, get a and b coefficients of reach  (query map service).
2) compute Drainage area (ss webservice)
3) compute flow = acoeff*DRNArea^bcoeff (client)
4) format results to fit in with Final Report (client)

**Comment by HansVraga** [comment]
Note: Archydo coordinated reach method is in ArcHydroOps.vb line 92713

**Comment by jknewson** [comment]
closed with #681
