### ISSUE TITLE
KY Karst warning message

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#672]
Karst in KY is included with the exclusion polygon. For KY, we'll need to compare the basin agasint the Exclusion polygon to see if any Karst is included in the basin. If it is, we need to pass on the warning message.

**Comment by HansVraga** [comment]
Add a post-delineation flag for comparing the delineation against a map services (for KY, the exclude poly to check for Karst). For throwing warnings if necessary.

**Comment by marsmith** [comment]
Implemented
