### ISSUE TITLE
Purchase and install SSL cert for streamstats.usgs.gov

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#675]

**Comment by HansVraga** [comment]
@aaronstephenson did we hear back on the cert purchase? I need to inform the StreamStats team if https:// redirect won't be available soon.

**Comment by aaronstephenson** [comment]
@HansVraga No response yet. I cc'd the WIM IT group, so you should all hear when I do.

**Comment by aaronstephenson** [comment]
Cert was purchased last night, and I just installed it. HTTPS redirect now working.
