### ISSUE TITLE
Mean Annual Precip Values do not agree in OH between V3 and V4

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#676]
Precip value at: 04196200
Was:

PRECIP
36 - V3
38.8 - V4

> Mean annual precip (PRECIP) values do not agree, and values of several of the monthly and annual flow statistics - those with PRECIP an an explanatory variable - do not agree. Station 04196200 was not included in the mean flow report, WRIR 02-4068. A check of another station, 04196000, indicated that v3 is reproducing the published PRECIP  value and cloud v4 is not. The report indicates that PRECIP values were taken from a digitized map by Harstine (1991). The general information page for Ohio indicates that PRECIP was taken from the layer at https://water.usgs.gov/GIS/metadata/usgswrd/XML/raintin.xml.
> 
> The low-flow equations from WRIR 86-4354 also include PRECIP as an explanatory variable, but those values were determined by eyeballing a map that was published with the report. I can only guess that PRECIP for this report in StreamStats was taken from the same layer as above.
>

**Comment by marsmith** [comment]
I dont understand how this is possible, unless the bc_layer grids are different

**Comment by jknewson** [comment]
No issue, mark it up as user error
