### ISSUE TITLE
Issues with streamstatstest mapservices

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#680]
I've seen several issues with this server over the last 24 hours that I have not experienced at all in the last month:
-500 errors on mapserver tile exports
-failed watershed delineations
-hung REST queries at this url: 'https://streamstatstest.wim.usgs.gov/arcgis/rest/services/StreamStats/stateServices/MapServer/50/query'

**Comment by aaronstephenson** [comment]
I'll look right away. Just FYI, it's a m4.xlarge (4 CPUs, 16 GB RAM), so it should be quite speedy.

**Comment by marsmith** [comment]
Thanks Aaron, I just had one random REST query work, tried again and its hung up, see screenshot, there is one 200 OK in the console, then the pending one, after a few minutes:

![image](https://cloud.githubusercontent.com/assets/6529123/25393463/84d17ece-29a9-11e7-9692-79f02fa4c69f.png)

**Comment by aaronstephenson** [comment]
I restarted the Windows AGS Service. It seems to have done the trick, not sure why... maybe it corrected some server settings from when we made a bunch of adjustments (SSL, server name, AD, etc) back in March? Anyway, it seems to be working now.

**Comment by marsmith** [comment]
I think things are better now, after some SSL hiccups today
