### ISSUE TITLE
Point test.streamstats.usgs.gov/ss traffic to streamstats-test bucket.

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#688]
I *think* this is a route 53 change, but not certain. The core request is to route test.streamstats.usgs.gov/ss --> streamstats-test/ss

where streamstats-test is a bucket in the streamstats subaccount

Eventually, we aim to have the following routing in place:

![image](https://cloud.githubusercontent.com/assets/12058013/25510710/32e8dace-2b90-11e7-9306-0a7cbfe6921a.png)

**Comment by aaronstephenson** [comment]
This won't work as currently configured. The S3 bucket must be a valid FQDN and have its Static Web Hosting property enabled. Otherwise, it's just a file storage location, not a web site.

**Comment by marsmith** [comment]
ok, maybe we can do `streamstats-test.wim.usgs.gov` bucket?

**Comment by aaronstephenson** [comment]
What about `test.streamstats.usgs.gov` as the bucket name? We have full control over the domain name now, since it was delegated to us.

**Comment by jknewson** [comment]
I think that will be fine for test, however for production I think we were hoping to redirect/rewrite the request to point to a production bucket so the url streamstats.usgs.gov/[insert app here] would be accessible, such as /ss => streamstats applicaton
/nss => nss application, etc. 

and where the root would point back to their current webpage (in all its glory)
is that still doable?

**Comment by aaronstephenson** [comment]
@jknewson yes, but that would be a separate bucket for the production code, e.g. `streamstats.usgs.gov` -- the point is that the bucket name must be a FQDN if it's hosting a website.

**Comment by jknewson** [comment]
ok, so we could have a buckets named prod.streamstats.usgs.gov and test.streamstats.usgs.gov and that would work, right?

**Comment by aaronstephenson** [comment]
yes you could, but my recommendation would be that anything considered production would not have a prefix, like how we have test.wim.usgsgov and wim.usgs.gov (not prod.wim.usgs.gov)

**Comment by jknewson** [comment]
any recommendations? We can't use streamstats.usgs.gov, right?

**Comment by marsmith** [comment]
I don't see how this is possible without a prefix.  We can't use wim.usgs.gov and we can't use streamstats.usgs.gov right?

**Comment by aaronstephenson** [comment]
Sure we can! We already do: https://console.aws.amazon.com/s3/buckets/wim.usgs.gov/?region=us-east-1&tab=overview

**Comment by jknewson** [comment]
ok, lets use streamstats.usgs.gov and test.streamstats.usgs.gov then

**Comment by aaronstephenson** [comment]
Sounds good. I just created those buckets in the SS account. You guys will need to move your files to the new buckets, though.

**Comment by jknewson** [comment]
ok, I'm on it

**Comment by jknewson** [comment]
Ok, Done. Feel free to delete streamstat-test and streamstats-prod buckets at your convenience.

**Comment by marsmith** [comment]
It could we use win.usgs.gov/ss?  Is this a bucket?

**Comment by marsmith** [comment]
Wait dudes, I thought Hans was saying he wants​ streamstats.usgs.gov to go to program page

**Comment by aaronstephenson** [comment]
The test bucket is now a fully operational static website:
http://test.streamstats.usgs.gov/ss
http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/ss

**Comment by HansVraga** [comment]
All planned URLs work for me.
