### ISSUE TITLE
Can I get SNS turned on for us

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#689]
I would like to try out AWS Lambda and SNS hooked to github webhooks to autodeploy when we push to master/staging. (outlined here:https://aws.amazon.com/blogs/compute/dynamic-github-actions-with-aws-lambda/) When I go to the SNS dashboard, I am receiving and authorization error.

![image](https://cloud.githubusercontent.com/assets/8713714/25530618/22d5042e-2be4-11e7-96e7-689cbb0e0e99.png)

**Comment by aaronstephenson** [comment]
I have given full access to you @jknewson and @marsmith for SNS, Lambda, and Cloudwatch (in case you want to do any scheduling of SNS or Lambda things). Let me know if you need access to more services, or if you need more refined permissions (for example, in the WIM Sandbox, I created a generic IAM role to do a very specific task with ec2, s3, and cloudwatch).
