### ISSUE TITLE
Remove/Reduce "User Input is Needed to Continue" Toast while looking for location

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#696]
This Toast appears with every zoom/pan of the map, which can cause them to stack up in a distracting fashion. We could remove this notification all-together (as the instructions on the left do tell the user what to do next) or only set a rule where we only show one toast notification of this message...

See the attached screenshot - can we keep all the stacked notifications (red circle) reduced to just one (blue circle)?

![image](https://cloud.githubusercontent.com/assets/12058013/25856244/7247b912-34a3-11e7-8d5f-f2c9a69d1fe1.png)

Issue based on this user feedback:
>If I zoomed out of the location after searching for Eureka, MO, I got a ton of toast messages requesting user input.  This seemed odd or out of place when I'm still at the stage of just looking around for my location of interest.

**Comment by marsmith** [comment]
looks like a dup of #710, closing
