### ISSUE TITLE
Shut down Unavailable State selections in "Select State/Region"

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#697]
- [x] Grey out State selection buttons that cannot progress in the interface workflow. (Blue circle below). This button cannot be clicked. 

- [x] Point the 'i' button click for those states/Regions (Red Circle below) at a freshdesk article for "Non-Implemented State/Region" (or if more trouble than worth, reference the program page FAQ entries (near the end) covering non-implemented states/regions)

![image](https://cloud.githubusercontent.com/assets/12058013/25859041/517b79a0-34ab-11e7-8aee-878df060c6e0.png)

Feedback that issue is based on:
>If I click on the green "Missouri" bar at left, then I get an orange toast message that says, "StreamStats not available here at this time."  That's a very generic message.  As an insider, I'm aware that the MO WSC has not completed their project yet, but the normal user would probably not know whether the toast message is referring to the area immediately around Eureka, or some wider area, or when.  Since it says, "at this time", the user might be wondering whether this was a temporary error or a longer-term problem.  The savvy user will recognize that the last thing they did before getting the orange toas message was to click on the green Missouri bar.  However, the interface is a little double-minded because it gives the orange warning, but then it proceeds on the left side as if it is ready to delineate (though you get no step 3 and the Delineate button does nothing).  It would be better if the green Missouri button was simply dithered and disabled to keep the user from clicking on it.  The program should not simultaneously respond positively (by proceeding to a dead end) and negatively (toast).  All dead ends should have a start-over button automatically appear if it isn't permanent.

**Comment by marsmith** [comment]
implemented
