### ISSUE TITLE
Basin Characteristic List not consistent in interface.

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#698]
The "Name" is missing from the list on the "Build a Report" Step. Also appears order is not the same?
We should look into making these two order the same, or at least, show the "Name" for the user.

See screenshots for comparisons:

![image](https://cloud.githubusercontent.com/assets/12058013/25860040/4a0d2bf2-34ae-11e7-9b16-dea75b69408c.png)

Issue from feedback:
>In the "Show Basin Characteristics" section, the Basin Characteristics names are not shown.  Since I selected them by name in the "Select Scenarios" section above it, then the names should appear here too when it tells me the value of each one.

**Comment by marsmith** [comment]
sorted the list of params based on code.  Added header row to table on left:
![image](https://cloud.githubusercontent.com/assets/6529123/26598733/3416f9d0-4544-11e7-85ab-96c31f0d41fd.png)

right image, swapped description with code:
![image](https://cloud.githubusercontent.com/assets/6529123/26598793/5d9b0aee-4544-11e7-8f28-1350641705b8.png)

**Comment by marsmith** [comment]
fixed
