### ISSUE TITLE
PLL PLU swapped in report

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#699]
(from a test in Illinois)
Feedback from reviewer:
>Check the explanation parts where you define "Pll" and "Plu".  Those are out of order and need to be swapped.  They are also confusing because they don't match the USGS standards for table explanations.  You are using colons to separate the abbreviation from the definition (which I personally like).  But USGS uses commas to separate each abbreviation from its definition, and semicolons to separate each abbrev./definition pair.
>I tried the CSV download, and the Pll and Plu labels appear to be correct there.

(screenshot example)
![image](https://cloud.githubusercontent.com/assets/12058013/25860170/b64308a0-34ae-11e7-8847-e04f3b13d341.png)

**Comment by HansVraga** [comment]
FIX: Change the heading in the Report & CSV download

**Comment by marsmith** [comment]
fixed
