### ISSUE TITLE
LEGEND: Basemap changes: Labels not available for the ESRI Imagery base map

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#703]
- [x] Add ESRI Dark Grey Basemap

- [x] Add labels layer to Imagry Basemap

- [x] Remove Oceans Basemap

- [x] Address console errors related to basemap

- [x] Address two 404 errors in console

Feedback from cooperator:
>Could some labels be added to the ESRI Imagery base map?  V3 had some labels to help the user orientate their location.

**Comment by marsmith** [comment]
address two 404 errors in console that come from legend service

**Comment by jknewson** [comment]
I have no idea where the 404's are coming from. I've stepped through all the layers and they look ok.

**Comment by jknewson** [comment]
got it, needed to change img src to ng-src
