### ISSUE TITLE
Measure/elevation INOP on mobile device

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#704]
Some console errors may be the cause.

**Elevation Profile needs to be re-sized to fit screen**

Feedback from Cooperator:
>Measure and elevation tools do not appear to be working on mobile device (iOS) - see screenshot below

**Comment by marsmith** [comment]
Joe vrabel says measurement is unreliable

**Comment by marsmith** [comment]
look out for any console errors related to mousemove.  check if we can replicate

**Comment by marsmith** [comment]
fixed
