### ISSUE TITLE
Remove drnarea from gage pop-up, spell out abbreviations

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#706]
- [x] Replace abbreviated field titles with full titles. (for example change sta_id: to Station ID:)

- [x] Remove drnarea from that pop-up.

From feedback:
>it is nice that there is a drainage area reported, but it is often null - yet it does have a da on NWIS - cross populate this somehow?

**Comment by marsmith** [comment]
fixed, cleanup of code here too,  instead of using a marker, just open the a popup on the map with the content
