### ISSUE TITLE
Alerts, reduce the cases of same alert 'stacking'

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#710]
Ideally, we can reset the timer of the same alert toast or clear the exact same alert toast and recreate it to reset the timer...

Example of what can cause this below:
>If I zoomed out of the location after searching for Eureka, MO, I got a ton of toast messages requesting user input.  This seemed odd or out of place when I'm still at the stage of just looking around for my location of interest.

**Comment by marsmith** [comment]
https://github.com/jirikavi/AngularJS-Toaster

looks like its possible to make a reference to a specific toast and just clear that

**Comment by marsmith** [comment]
done
