### ISSUE TITLE
Exploration Tools - bugs when switching between tools

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#712]
It appears selecting between the tools can cause bugs, throwing a good number of errors.
We also have some suggestions for enhancements - see comment.

Feedback from Tester:
>Exploration tools. Using tools and changing between tools is buggy. How do I exit a tool mode? For example, no obvious way to exit “Query Streamgages” mode after clicking that button.

Tester also found bugs when switching between the tools.

**Comment by HansVraga** [comment]
SUGGESTION:
The following is suggested as an improved workflow:

1. Map-click tools (“Query Streamgages”, “Measure  Tool”, and “Elevation Profile Tool”):
2. Clicking an inactive (blue) button activates that mode (makes orange) and turns off any other active modes (other map-click tools blue).
3. Clicking the map performs the operation of any active tool. Recommend setting a global map-click mode variable that keeps track of currently set mode (or possibly using css class to make buttons active-inactive and querying button classes to determine active mode). After map creation, map events (click, mousemove, etc.) need to look at the currently set mode (or which button is active by css class) and only do things they are supposed to based on the current mode (many console errors seem related to this).
4. Clicking an active (orange) button turns that tool and all others off (all blue) so there is no mode set.
5. When a tool is deactivated, all map graphics associated with it should be cleared from the map.
6. If a map-click tool is zoom-level dependent, consider making the buttons zoom-level aware and enable-disable automatically, so they are enabled only when you can actually use them.
7. “Show your location” – this button is independent from the buttons above it. Can click at any time. Clicking “activates” by making button orange, zooming to your location, and adding location map marker. Clicking when active “deactivates” by making blue and removing the map marker.
8.

**Comment by marsmith** [comment]
fixed
