### ISSUE TITLE
Left-hand Navigation Bar: CSS updates to disabled collapsible panels

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#713]
Feedback from Cooperator expresses confusion over left-hand nav bar interface that appears to have clickable accordions that don't respond when clicked.

Enact CSS rules when disabled that hide the "carrot" icon as well as not highlighting the buttons as if they can be clicked.

**Comment by marsmith** [comment]
tweaked some css to make these look less 'appealing'
