### ISSUE TITLE
Add mask to clarify the geographic focus of the tool

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#714]
Suggestion from reviewer:
>Add a mask around the focus area of the application. If it is the United States, consider using the mask from this public TXWSC AGS server: https://txpub.usgs.gov/arcgis/rest/services/Mapping/Mask/MapServer

**Comment by marsmith** [comment]
done

**Comment by HansVraga** [comment]
Selecting a new basemap loses the Area of Interest Layer. Toggling the AoI layer restores it.

**Comment by marsmith** [comment]
fixed, gave the tile layer a z-index
