### ISSUE TITLE
Legend/Layers - style changes to match Exploration Tools

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#716]
- [x] Default Layers to open 

- [x] When open, change the heading to "Layers" 

- [x] Fix close icon (Similar to Exploration Tools)

- [x] Annotate National Layers with required zoom level to see objects (for example zoom level 9 for gages)

- [x] Move carrot icons to right of section headings

- [x] Fix the checkbox/symbology overlaps (see screenshot:)

- [x] Check boxes in application layers are not appearing. The action works however there is no check.

![image](https://cloud.githubusercontent.com/assets/12058013/26365701/57bbb652-3fb6-11e7-8896-83cb1cfc9043.png)

**Comment by jknewson** [comment]
I got it as far as I can, I'm shifting it over for some mitchifications
![image](https://user-images.githubusercontent.com/8713714/26892748-79e3113c-4b76-11e7-905c-efb07a790212.png)

1) I'm trying to get the same circle button close as you had for the exploration tools, but it seems to be hidden behind. 
2) the down/up arrows should be all in line with the labels. 
3) the application layers check boxes will not show the check when "isChecked". the toggling works, however the check never appears.
