### ISSUE TITLE
Click to Query Streamgages, and other layers, by default (remove button)

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#717]
Feedback from reviewer:
>“Query Streamgages” tool – this tool seems unnecessary. If you turn the streamgages layer on and click on a triangle, it should automatically identify without needing to use a tool.

**Comment by HansVraga** [comment]
Suggestion from reviewer:
>If the layer is on and visible, automatically perform layer id when the map is clicked. If there is a result show the map point popup. If there is none, do nothing. Do not show any Info or Warning messages. Cancel any ongoing AGS identify tasks each time the map is clicked so any old id tasks don’t show popups with new map clicks.

**Comment by marsmith** [comment]
Like this idea

**Comment by marsmith** [comment]
implemented
