### ISSUE TITLE
Lower-right blue and orange info and warning popups cannot be closed

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#718]
Since Blue and Orange (info and warning) alerts are timer-based. Remove the "X" displayed on them.

Feedback from reviewer:
>Lower-right blue and orange info and warning popups (above screenshots) – they have “X’s” at the right but clicking the “X” does not seem to do anything. They only seem to disappear after a timeout.

**Comment by marsmith** [comment]
fixed, completely removed close buttons from toasts
