### ISSUE TITLE
Elevation Profile tools cleanup

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#719]
- [x] "X" in upper-right does not close the modal

- [x] On-screen elevation line stays after modal is closed

- [x] Add spinner to the "Querying elevation Service" (Similar to delineation spinner)

- [x] Suppress any "User Input Needed" alerts while working with the Elevation Profile tool. (When zoomed in, multiple “user input needed” messages appear when using the tool, making it seem like something is broken.)

**Comment by marsmith** [comment]
addressed these four, with some extra cleanup
