### ISSUE TITLE
Show loading icon when retrieving content for modals (from Freshdesk)

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#723]
From Reviewer:
ISSUE:
It looks like much content is dynamically loaded which makes for a better overall user experience. However, some dynamic content takes a while to load and nothing seems to be happening. Example: Click top right “HELP” – the User’s Manual takes a while to populate.

SUGGESTION:
Pre-populate all dynamically loaded content with animated wait spinners while content loads and replace spinner with content when retrieved. Clicking “close” mid-query cancels query and closes dialog.

**Comment by marsmith** [comment]
added loading spinners
