### ISSUE TITLE
Thank reviewers at the bottom of "About" content

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#724]
Add "Special Thanks To:" Joe, Silvia, Todd, and Jon for reviews.

**Comment by HansVraga** [comment]
Should also mention the angular/leaflet directive.

**Comment by HansVraga** [comment]
Add a disclaimer page to Freshdesk.

**Comment by marsmith** [comment]
I think disclaimer content should go in freshdesk, we could make a seperate tab for disclaimers , or keep them in about modal 'about the project' tab, right at the top and loop over them.  either way, make them seperate articles

**Comment by HansVraga** [comment]
I'm good with another tab. Article created:

https://streamstats.freshdesk.com/solution/articles/9000127695-disclaimers

**Comment by HansVraga** [comment]
We've decided to thank reviewers and testers in the release article.
Added a "Credits" Freshdesk article: https://streamstats.freshdesk.com/solution/articles/9000127697-credits
