### ISSUE TITLE
embiggen the machine

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#740]

**Comment by aaronstephenson** [comment]
This is in reference to StreamStatsTest, which is seeing a huge spike in traffic today. Through discussion on Slack, we decided to leave this EC2 instance as-is (it will remain the "test" instance), and make a copy of it, then double the size of the copy and make that copy the "production" instance.

**Comment by aaronstephenson** [comment]
The new EC2 instance is named StreamStatsProd and is a m4.2xlarge (double the size of the test instance). I assigned it an elastic IP address of 34.225.184.188, and a DNS record of streamstats.usgs.gov. The old test machine (StreamStatsTest) is keeping its assigned elastic IP address of 34.194.77.209 and DNS record of test.streamstats.usgs.gov.
