### ISSUE TITLE
Add Title to the Gages Pop-up

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#767]
For clarity on what's being shown, add a simple title to the Pop-up: "Streamgage"

https://files.slack.com/files-pri/T2PFUSXUL-F5RGUUG11/pasted_image_at_2017_06_09_16_25.png
![image](https://user-images.githubusercontent.com/12058013/26994291-094966d6-4d35-11e7-914f-d9af98e4dd6b.png)

**Comment by marsmith** [comment]
fixed with #804
