### ISSUE TITLE
Assign auto-shutoff rule (Buisness hours) for streamStatsTest EC2 instance in streamstats sub-account

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#771]
Please use the Buisness hours shutoff option. 

Assign auto-shutoff rule for streamStatsTest EC2 instance in streamstats sub-account

**Comment by aaronstephenson** [comment]
Done! Do we also want this particular instance to start up every morning, or just as needed?

**Comment by HansVraga** [comment]
Every morning for now, there is still testing going on.
We'll revisit in July.

**Comment by aaronstephenson** [comment]
Done!
