### ISSUE TITLE
Elevation Profile Tool

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#781]
Look at the values on the Y axis and the Elevation values on the lines below - I think the lines below might be meters instead of ft?

![image](https://user-images.githubusercontent.com/12058013/27395983-af4978f2-567f-11e7-9eed-a7692fe4e7b8.png)

**Comment by jknewson** [comment]
Done with #782

**Comment by jknewson** [comment]
Based on freshdesk issue ttps://streamstats.freshdesk.com/helpdesk/tickets/8219

**Comment by marsmith** [comment]
tweak sample distance and resulotions options as well: https://developers.arcgis.com/rest/elevation/api-reference/profile.htm

**Comment by marsmith** [comment]
i have a sneaking suspicion that the elevations aren't coming back consistent from the ESRI service, so sometimes units are right, sometimes they aren't

**Comment by marsmith** [comment]
fixed
