### ISSUE TITLE
Restore Bridge Functionality to States

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#783]
From Big K:
>Here is the screen shot of a bridge location and info provided as a result of clicking on the Info button and then on a bridge, as you requested. We need to restore this functionality in version 4 for 3 states, including MN and GA. I can't recall the third state. Hopefully, another team member can tell us that.

![image](https://user-images.githubusercontent.com/12058013/27607826-db38c31c-5b4a-11e7-99f5-8d2aaa45488f.png)

**Comment by jknewson** [comment]
GA and MN have bridges added to state services.
