### ISSUE TITLE
Prepare infrastructure for full V4 go-live

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#785]
Due to the unfortunate nature of ArcHydro, we'll need to prepare the infrastructure to fail gracefully. The method discussed for that was to build auto-scaling rules to spin up a new instance when production is over-taxed and swap route 53 to the new instance once it's ready for a (mostly) seamless transition.

**Comment by aaronstephenson** [comment]
Implemented using AutoScaling and Elastic Load Balancer. The Route 53 record for streamstats.usgs.gov now points to the ELB, not an elastic IP address. When the existing EC2 instance's CPU utilization gets too high, the AS will launch a new EC2 instance and add it to the ELB. When the average CPU utilization returns to a more reasonable number, the oldest EC2 instance will be terminated.

Note, though, that this means the elastic IP address cannot be maintained (except through some scripting, probably Lambda) with this arrangement. To access the new EC2 instance, just reference the FQDN.

**Comment by HansVraga** [comment]
> When the average CPU utilization returns to a more reasonable number, the oldest EC2 instance will be terminated.

The issue we're seeing is that when the existing EC2 CPU usage gets too high and then stays there, due to some sort of error caused by ArcHydro. When the new instance comes online, the old one may continue to have that high CPU usage - will that cause this rule to not fire?

**Comment by aaronstephenson** [comment]
I took that phenomenon into account. Assuming the old instance will be at 90-100% CPU, and the new instance will be at 1% CPU, I set the scale in to fire when the ELB average CPU is 60% or lower, which should be right when the new instance comes online.

**Comment by HansVraga** [comment]
Once #800 is complete, apply the golden image to our auto-scaling solution. M4xLs for size, spun up to meet demand during the business week (based on observed usage times). Oldest instances are always spun down to keep ArcHydro from running too long on an instance.

**Comment by HansVraga** [comment]
Moved back to 'in progress' as we've run into some hiccups.
Currently creating an instance from scratch in hopes of getting a good AMI.
Progress here: https://docs.google.com/a/doi.gov/document/d/1mELY5f720QtX8TZTqWdZzZChKt-rKOBXWHV6Bbppygs/edit?usp=sharing

**Comment by HansVraga** [comment]
@aaronstephenson  Leaving open as a reminder to park the IIS rules and other configuration documentation in the places you planed to put them - close when done!

For reference, here is the folder with the SS v4 cloud setup documentation: https://drive.google.com/open?id=0BygT1gkOzi3SdC1oXzlNN1BqcjQ

**Comment by HansVraga** [comment]
V4 is live.
