### ISSUE TITLE
Change Window/Tab title

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#787]
See the mismatch between the tab title and the About title for version number. ~Either remove "4.0" from the window title, or match the version number with what is in the about window.~ see comment

![image](https://user-images.githubusercontent.com/12058013/28289281-042b766e-6b10-11e7-9f11-4815e783e4ba.png)

**Comment by HansVraga** [comment]
With further thought, I think we just remove the "4.0" and have the title say "USGS StreamStats"

**Comment by marsmith** [comment]
fixed with #804
