### ISSUE TITLE
Add Disclaimer tab to "About" Modal

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#788]
Once Approval is given:

- [x] Remove Disclaimer box (Red Circle)
- [x] Remove Disclaimer paragraph (Blue Circle) [Here](https://streamstats.freshdesk.com/solution/articles/9000052344-about-streamstats).
- [x] Add tab to modal "Disclaimers" - populate with [Disclaimers ](https://streamstats.freshdesk.com/solution/articles/9000127695-disclaimers)and [Credit ](https://streamstats.freshdesk.com/solution/articles/9000127697-credits)fresh desk Articles

![image](https://user-images.githubusercontent.com/12058013/28577506-00a9168e-7125-11e7-873b-a73626ac2779.png)

**Comment by HansVraga** [comment]
Pete M suggested we just have both disclaimers in the same statement, here is the language:
Data Disclaimer:

Unless otherwise stated, all data, metadata and related materials are considered to satisfy the quality standards relative to the purpose for which the data were collected. Although these data and associated metadata have been reviewed for accuracy and completeness and approved for release by the U.S. Geological Survey (USGS), no warranty expressed or implied is made regarding the display or utility of the data for other purposes, nor on all computer systems, nor shall the act of distribution constitute any such warranty.

Software Disclaimer:

This software has been approved for release by the U.S. Geological Survey (USGS). Although the software has been subjected to rigorous review, the USGS reserves the right to update the software as needed pursuant to further analysis and review. No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. Furthermore, the software is released on condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from its authorized or unauthorized use.

**Comment by HansVraga** [comment]
Updated title and opening content of issue.

**Comment by marsmith** [comment]
fixed with #804
