### ISSUE TITLE
Report citation links redirect back to Streamstats

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#791]
When I click the citations at the bottom of each report section, it opens another instance of the StreamStats application instead of directing me to the report cited. I think it's because the hyperlink is hashing to the report's URL instead of opening the page to it. The report URLs I see look like this: https://test.streamstats.usgs.gov/ss/#http:%2F%2Fpubs.usgs.gov%2Fsir%2F2012%2F5113%2F%23

**Comment by jknewson** [comment]
Done, The issue stems from SSDB. For some reason SSDB has # surrounding the url.
