### ISSUE TITLE
Duplicate scenarios listed in the output report. 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#792]
I noticed that under certain conditions, scenario results would duplicate in the output report. Here are the steps I followed that resulted in duplicate scenario results:

1. Pick any study area for which peak-flow statistics are available, choose any point on the stream grid, and delineate the basin
2. Select "Peak-Flow Statistics" as the scenario to run
3. Open the report: it should have just one peak-flow statistics result set, as expected
4. Go back to "Identify a Study Area" section and click "Continue" without changing any parameters
5. Again select "Peak-Flow Statistics" as the scenario to run
6. Open the report: there seem to be two identical peak-flow statistics results sets

**Comment by HansVraga** [comment]
When clicking "Continue" for "Identify a Study Area" check to see if this basin has been edited, or if it has h ad the regression regions already queried.

Skip regression region query if basin has not been edited. Unless it's the first time through the workflow.

**Comment by marsmith** [comment]
fixed
