### ISSUE TITLE
WebConfig add condition for test and prod servers

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#801]
Current test webconfig (Located c/inetpub/wwwroot) is attached. If/when instance becomes golden image and used as production environment. webconfig needs to be able to Redirect to the correct (prod/test) S3 bucket
[web.config.txt](https://github.com/USGS-WiM/StreamStats/files/1170977/web.config.txt)

**Comment by aaronstephenson** [comment]
Done. New webconfig is attached for reference.
[web.config.txt](https://github.com/USGS-WiM/StreamStats/files/1176974/web.config.txt)
