### ISSUE TITLE
Layers icon-label misalignment 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#803]
Legend icon-label misalignment
See image:

![image](https://user-images.githubusercontent.com/12058013/28579310-4b29cc08-712a-11e7-94cc-9fe5cd803e0b.png)

**Comment by jknewson** [comment]
This is an esri thing, not sure if mitch can do anything about it

**Comment by HansVraga** [comment]
clearing milestone and assignee for now, leaving this for later work.

**Comment by amedenblik** [comment]
We added checkboxes to these individual layers, so this looks better now 
![image](https://user-images.githubusercontent.com/40237491/202745776-b2fcbc3c-e51d-4d9a-b3a9-22350c679f24.png)
