### ISSUE TITLE
Something happened with the Legend

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#805]
Some old issues came back: 

- [x] Title goes from "Layers" to "Legend"
- [x] Chevrons are below instead of beside

Latest screenshot from test:
![image](https://user-images.githubusercontent.com/12058013/28622054-1aa7fa98-71e1-11e7-99af-b8e7a8a7d36c.png)

What is in the prod client:
![image](https://user-images.githubusercontent.com/12058013/28622076-34cd4f5e-71e1-11e7-9f52-aad031f9eece.png)

**Comment by marsmith** [comment]
Fixed, need wim_angular update
