### ISSUE TITLE
Output for edited basin should show edited boundary, not original boundary

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#810]
Editing a basin in WI, shows edits in main map but when report is opened the basin wasn't edited.. FD ticket: https://streamstats.freshdesk.com/helpdesk/tickets/8245.

**Comment by jknewson** [comment]
I'm thinking it may be a global basin.. but will look into it further, at any rate.. probably need to figure out a way to toggle off editing for global basins.... I know we have talked about this being an issue from the services... SSservices issue :https://github.com/USGS-WiM/StreamStatsServices/issues/9

**Comment by marsmith** [comment]
I believe what was happening here is if you don't click "Finish" after editing-- it obviously doesn't make it to the report.
