### ISSUE TITLE
Font seems to be off

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#817]
Exploration tools/layers are different
![image](https://user-images.githubusercontent.com/8713714/29669927-486b5d4e-88a2-11e7-9218-8a60d87ab4dd.png)

citations are way to big
![image](https://user-images.githubusercontent.com/8713714/29670011-93478d60-88a2-11e7-988a-ef24d3012d09.png)

**Comment by marsmith** [comment]
Citations section header you mean, right

**Comment by jknewson** [comment]
Oh, yeah right, thanks for the clarification
