### ISSUE TITLE
Another 10.5 instance

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#820]
We can kill AGS10.3 and build a additional clean 10.5 instance so we can ensure our build scripts are reproducible.

**Comment by aaronstephenson** [comment]
Done. ArcGIS Desktop and Server are both licensed, web adaptor is installed and working, and the *.streamstats.usgs.gov SSL cert is installed.

Elastic IP is 52.4.196.28. Both Jeremy and Marty have individual accounts (equivalent to their AD account names), with a password that I sent to you separately. Please change the password after your first successful login.
