### ISSUE TITLE
Need to remove CDN ionicons dependency

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#824]
It is way too unreliable, seems to be down half of the time.

![screenshot131](https://user-images.githubusercontent.com/6529123/30167681-2f9a35ec-93b5-11e7-8546-7fa8bcee4f4c.jpg)

![screenshot130](https://user-images.githubusercontent.com/6529123/30167676-2c091a06-93b5-11e7-81e4-76ee50b5570f.jpg)

**Comment by MartinKolarik** [comment]
You can easily switch to https://www.jsdelivr.com/package/npm/ionicons?path=dist%2Ffonts which was built for production and doesn't have problems like this.

**Comment by HansVraga** [comment]
I *think* this was done? @mitch-wim want to close this one if you did it?

**Comment by marsmith** [comment]
Closing this for now because I updated to a 'better' CDN
