### ISSUE TITLE
Toast styles are getting overridden by main.css

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#825]
I think its nice they are overridden to match the rest of the mitchCSS, but we are losing the coloring based on toast status, ie: info,warning,error.   All toasts are currently blue.  Also, we have a global config option set to remove the 'x' close button in the upper right that seems to be overwritten as well

here you can see broken ionicon for 'x' close button (shouldn't be there), this is a 'warning' type toast but showing up as blue.
![image](https://user-images.githubusercontent.com/6529123/30167800-8f30af5e-93b5-11e7-8460-198f56b308aa.png)

**Comment by HansVraga** [comment]
this was fixed
