### ISSUE TITLE
Layers box has horizontal/vertical scroll bars and doesn't expand 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#826]
![image](https://user-images.githubusercontent.com/12058013/30181118-3573aa2c-93e0-11e7-9a1c-6e1db311281c.png)

**Comment by marsmith** [comment]
i think these could be hidden on initial view, because they overflows aren't needed until some of the content is expanded

**Comment by HansVraga** [comment]
National Layers is open on initial view, but you can't actually scroll to see the content.

**Comment by marsmith** [comment]
bottom overflow (X) isn't needed

**Comment by HansVraga** [comment]
this was fixed
