### ISSUE TITLE
go-live

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#827]
- [x] re-image [GoldTest] and attached storage one final time
- [x] create new three new EC2s from image and attached storage ^ [GoldenTestMMDDYY] and [GoldenProdMMDDYY] and [GoldenProdMMDDYY]
- [x] Load balance two prod instances
- [x] Terminate [GoldTest] and [StreamStatsNew105]
- [x] Test out prod and test before DNS Swap (notify jeremy, marty, hans)
- [x] Swap DNS streamstats.usgs.gov > [GoldenProd], test.streamstats.usgs.gov > [GoldenTest]
- [x] Setup all WebConfig's on [GoldenProd] to point to production NSS DB
- [x] Terminate [StreamStatsProdCurrent] and [StreamStatsTestCurrent]

**Comment by aaronstephenson** [comment]
The new gold test and prod instances are up and ready for review.
@jknewson @marsmith @HansVraga

**Comment by HansVraga** [comment]
I think we can close this!
