### ISSUE TITLE
broken citation URLS

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#831]
![image](https://user-images.githubusercontent.com/12058013/30357430-8eec2c0c-980c-11e7-8fee-28dd5a4a73dc.png)

**Comment by HansVraga** [comment]
FYI @marsmith I don't get this for any of the citations in VA

**Comment by marsmith** [comment]
It looks like its an issue where there is a '#' in the NSS db for the citation.  And this seems familiar to me--I think I remember Jeremy mentioning it.... I'm going to try to just do a string replace ('#','')

**Comment by marsmith** [comment]
![image](https://user-images.githubusercontent.com/6529123/30382353-e1b4f274-986c-11e7-9b55-00388a5387fe.png)
verified this is a db issue

**Comment by marsmith** [comment]
put in temporary fix in reportview.html: `<a href="{{citation.CitationURL.replace('#','')}}" target="_blank">{{citation.Author}}{{citation.Title}}</a>`
this only replace first instance of the '#'

**Comment by marsmith** [comment]
temp fixed with above but leaving issue open for @jknewson

**Comment by marsmith** [comment]
fixed with temp fix above
