### ISSUE TITLE
CRB, DRB not working on gold prod or test

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#834]
I believe we have a somewhat major issue here.  HTTP error at sites in CRB and DRB.  Looking into it on the server, and then looking at what v3 is doing, led me to the fact that it looks like what should happen in CRB is that it uses the State the point is in (not CRB) to do the delineation, and then has a seperate set of basin chars.

What v4 is trying to do is use CRB for delineation, and there is no HUC data for CRB (since it should be using individual states)-- hence the 404.  when i debug using delieation.py on the server I see this:
![screenshot040](https://user-images.githubusercontent.com/6529123/30439762-a134883c-9942-11e7-9b57-4506fd9d8909.jpg)

I dont know how this slipped thru the cracks

**Comment by marsmith** [comment]
Old prod works so we have something to go off for fix.  But I need @jknewson input on this.  I'm wondering if we have a slightly different version of streamstats services on old prod than we do on the new gold instances.

NOT working on current Gold Prod or Test:
https://streamstats.usgs.gov/streamstatsservices/watershed.geojson?rcode=CRB&xlocation=-72.3878002166748&ylocation=42.3545797931251&crs=4326&simplify=true&includeparameters=false&includeflowtypes=false&includefeatures=true

I fired up Old Prod to test, and it works:
http://34.225.184.188/streamstatsservices/watershed.geojson?rcode=CRB&xlocation=-72.3878002166748&ylocation=42.3545797931251&crs=4326&simplify=true&includeparameters=false&includeflowtypes=false&includefeatures=true

**Comment by HansVraga** [comment]
This has been fixed.
