### ISSUE TITLE
Edit function is broken

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#835]
Seems to work, click "finished' then when you hit "Continue" this message appears:

![image](https://user-images.githubusercontent.com/6529123/30445646-a7ac5520-9954-11e7-900c-6a668c25d009.png)

**Comment by marsmith** [comment]
fixed

**Comment by jknewson** [comment]
Reopening.
Looks like the services are failing to return the watershed. With the following error in the log:
>>>Failed to include fields Traceback (most recent call last):
  File "EditWatershed.py", line 120, in __addFields__
    includeList = list(set([f.name for f in fieldList])-set([f.name for f in arcpy.ListFields(feature)]))
  File "C:\Program Files (x86)\ArcGIS\Desktop10.5\ArcPy\arcpy\__init__.py", line 1138, in ListFields
    return gp.listFields(dataset, wild_card, field_type)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.5\ArcPy\arcpy\geoprocessing\_base.py", line 346, in listFields
    self._gp.ListFields(*gp_fixargs(args, True)))
IOError: "D:\ClientData\PA20181221133514086000\PA20181221133514086000.gdb\Layers\GlobalWatershed" does not exist

**Comment by kjacobsen16** [comment]
@marsmith I know you did some work with the edit, is it working now? other than the add/remove order issue (#1004)?

**Comment by marsmith** [comment]
This may be fixed
