### ISSUE TITLE
Tweak LB script to adjust 'bigkernb' startup time

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#845]
Looks like we're firing up BigKernB a few hours early. Can SysOps investigate?

![image](https://user-images.githubusercontent.com/12058013/30645561-1a8583c6-9de4-11e7-93b7-34deac883f41.png)

**Comment by HansVraga** [comment]
@aaronstephenson we took a look at analytics - we should adjust the times according to usage:

![image](https://user-images.githubusercontent.com/12058013/30651552-0df48a02-9df4-11e7-9218-21540356ed7f.png)

**Comment by HansVraga** [comment]
So, having the coverage from 8am (Eastern) to 6pm (Eastern) looks like the way to go.

**Comment by aaronstephenson** [comment]
This is implemented. All times Eastern.

1. Boot @ 730am
2. Register with Load Balancer @ 8am
3. Deregister from Load Balancer at 6pm
4. Shutdown at 7pm.

**Comment by HansVraga** [comment]
Leaving it open to check tomorrow AM
