### ISSUE TITLE
Set up linux micro EC2 and an EFS 'drive' for testing Windows EFS hack

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#849]
Following this tutorial:
https://erudinsky.com/2017/08/30/aws-efs-windows

**Comment by HansVraga** [comment]
(from @jknewson):
>  @aaronstephenson  we can't add anything to the attached efs drive (permissions error). Can you set aside time tomorrow to walk us through the process. I got a StreamStats keypair file from blake last week to connect so I'm thinking it's not the right permissions or something??

**Comment by aaronstephenson** [comment]
Done. The permissions issue is taken care of.
