### ISSUE TITLE
Wrong Column Label on CSV download of Elevation Profile tool 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#851]
See screenshots:
CSV download: 
![image](https://user-images.githubusercontent.com/12058013/32456490-d17d9f6c-c2f3-11e7-92ff-b4f9a8d2c84a.png)
Elevation Profile Modal:
![image](https://user-images.githubusercontent.com/12058013/32456510-e09f76c8-c2f3-11e7-8380-481180a45d24.png)

**Comment by marsmith** [comment]
done
