### ISSUE TITLE
Work with SoftNas representative to get cost estimate

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#853]
In order to make the decision to proceed to use SoftNas, we'll need an estimate of cost. I've (Hans) kicked off the conversation, but can't provide the details the SoftNas reps need to help us get a good estimate.

**Comment by aaronstephenson** [comment]
Now moot. SS dev staff no longer want to use it.

**Comment by jknewson** [comment]
I think it's still worth identifying a cost analysis. Having a single NAS would be ideal to having multiple TB drives. I think we couldn't wait any longer.
