### ISSUE TITLE
Create IAM user for StreamStats GIS team

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#857]
with write access to 'streamstats-staged-data' bucket ONLY

**Comment by aaronstephenson** [comment]
Are you asking for one user for the entire GIS team to use? What/who is this GIS team? What is the purpose of this user account?

**Comment by marsmith** [comment]
I was thinking one for the team, but we can make per user accounts.  There are only 3 people on the team (streamstats team GIS people).  The purpose of this account is so they can send updated GIS data to S3 via an ArcCatalog toolbox i'm writing.

**Comment by aaronstephenson** [comment]
We decided today to do this. Issue moved to https://github.com/USGS-WiM/StreamStats-Tools/issues/6
