### ISSUE TITLE
Something up with editing watershed.

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#862]
The program gives an error message every time I try to submit an edited basin. 
error 405

**Comment by jknewson** [comment]
additional info from Pete 

> I just confirmed that editing a basin does not work.  It looks like it does at first, but when you submit it, you get an error.  I confirmed that the update does not happen because I downloaded the basin and no edit piece shows up (just the original basin).  The real confusion is that if you click on the 'submit edited basin' (and get the error) and then just proceed anyway, you will get a warning message in the flowstats report that the basin was edited....even though it was not

**Comment by marsmith** [comment]
Issue is on services side

**Comment by jknewson** [comment]
Fixed (serverside) with following information: https://stackoverflow.com/questions/8131141/error-405-on-puts-ignoreme-rastahook-in-iis-log

**Comment by jknewson** [comment]
I'm throwing this in here so I can remember, something is up with the latest pull of the greiner-hormann.leaflet js. I had to update line 493 in order to get it to work. Below is what I changed it too
```
function boolean (polygonA, polygonB, sourceForwards, clipForwards) {
    var source = [], clip = [];

    var latlngs = polygonA['_latlngs'];
    for (var i = 0, len = latlngs.length; i < len; i++) {
        source.push([latlngs[i]['lng'], latlngs[i]['lat']]);
    }
    latlngs = polygonB['_latlngs'];
    for (var i$1 = 0, len$1 = latlngs.length; i$1 < len$1; i$1++) {
        clip.push([latlngs[i$1]['lng'], latlngs[i$1]['lat']]);
    }
```
