### ISSUE TITLE
Streamstats routing for water-use

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#869]
According to our routing documentation: https://docs.google.com/document/d/1yNX3Z4T5fm3DvuAbw8x0ZjpZOFD1ltYrNoGGCd6ljag/edit?usp=sharing

https://test.streamstats.usgs.gov/wu _should_ be the page for our water use client. It doesn't seem to work, however.
There is a client at https://test.streamstats.usgs.gov.s3.amazonaws.com/wu/index.html

**Comment by HansVraga** [comment]
@jknewson can you confirm the client is in the expected place in S3? If so, please add this to the infrastructure project & tag as an infrastructure task.

**Comment by jknewson** [comment]
This was temporary until we got the rewrite tools squared away.. should be good now.
