### ISSUE TITLE
Force only one Delineate|Exploration tool at a time

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#870]
In the below screenshot all three of these buttons are active.
We should make it so if one is clicked while another has been clicked, we should de-activate the previous one. (so if a user clicks delineate, then Measure tool, delinate should be deactivated)

![image](https://user-images.githubusercontent.com/12058013/35575377-39a3bb96-05aa-11e8-932c-5ab9110b177d.png)

**Comment by marsmith** [comment]
done
