### ISSUE TITLE
Network Navigation Workflow - open Modal upon tool click

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#872]
When any of the NN items are clicked, immediately open the tool modal. 
We'll use it to guide the user on using the tool with options (select a point, use pourpoint, use basin, etc).
The modal will need to open/close for users to select points on the map.

![image](https://user-images.githubusercontent.com/12058013/35576247-823f8ec8-05ac-11e8-86f9-98450fb95528.png)

**Comment by marsmith** [comment]
done
