### ISSUE TITLE
Style and add pop-up to Network Trace points

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#873]
a network trace shows upstream/downstream networks and points along that network.
We should add symbols to identify they type of points found, and a simple pop-up of each point explaining what it is.

Will need to add the symbolization to the "Layers" 

![image](https://user-images.githubusercontent.com/12058013/35576950-5aea2b7e-05ae-11e8-9cc5-bed8bd098015.png)

**Comment by marsmith** [comment]
added popups, not symbolized yet

**Comment by marsmith** [comment]
done
