### ISSUE TITLE
Network Navigation  - take a look at a smaller modal 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#875]
Even the more involved NN tools could probably get a way with a smaller modal. Should be less obtrusive to the user.

**Comment by marsmith** [comment]
I think this may need the mitch touch, I set the NG UI bootstrap modal size to 'sm' but i'm not sure it changed anything

**Comment by marsmith** [comment]
not sure this is an issue now with mitch styling
