### ISSUE TITLE
update appConfig accordingly

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#883]
Looks like the appConfig in Master might be a bit out-of-date - users reported map services down this weekend and today. After some troubleshooting it appears we have an older reference to the map-services still in the master branch.

>Marty Smith [11:23]
i think what happened is that appConfig never actually got updated for prod after we brought out mapServices to a seperate server
so when i did the hotfix build..... it overwrote an actual good (already hotfixed appConfig)

**Comment by HansVraga** [comment]
Also, take a peak to see if we're referencing the shaded out Mexico and Canada service from TX

**Comment by marsmith** [comment]
done
