### ISSUE TITLE
what happened to selecting pour point as my end point?

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#885]
![image](https://user-images.githubusercontent.com/12058013/35874724-492de046-0b3b-11e8-8756-47618f58a01c.png)

**Comment by HansVraga** [comment]
following the screenshot, I selected a point near the pourpoint and then got "use pourpoint back" I switched back to pourpoint and now "go" won't work...

**Comment by marsmith** [comment]
should be fixed
