### ISSUE TITLE
CRB and DRB need to be enabled. West Virginia needs disabled.

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#887]
![image](https://user-images.githubusercontent.com/12058013/35893172-cc8d5270-0b7a-11e8-8624-20d8ff601a63.png)

**Comment by HansVraga** [comment]
From Kitty
>Also, West Virginia's button is blue; it should be grayed out.

**Comment by marsmith** [comment]
disabled WV but left CRB and DRB disabled. .THis is a services issue jeremy already has an issue for : https://github.com/USGS-WiM/StreamStatsServices/issues/35
