### ISSUE TITLE
Give summary of previous selections made in the workflow display left-hand column

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#89]
When you've selected the state/region in the left hand workflow it moves on to the next step - Identify study area. The State/region section collapses - hiding the information of what you've selected. We should display the state. For further steps in the workflow, we should be able to communicate what the user has selected/decided at previous steps without making them click back through the workflow.

**Comment by HansVraga** [comment]
A perhaps-related question: can the user, from any step in the workflow, go to a previous step and make a change in their selections and pickup the workflow from there?

**Comment by marsmith** [comment]
Implemented
