### ISSUE TITLE
Review StreamStats Test -> Prod plan

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#892]
Aaron,
Kind of a different ticket, but we wanted to sort out our plan for promoting the Test System(s) to Production in StreamStats and run it by you for comment. We figure you can either give it the thumbs up, suggest changes here, or call a meeting to go over it as a group. Once we've agreed on the plan, I would look to open separate Sysops tickets to kick it off.

Quick overview of the pieces. Two environments: Test and Production.
Test:
TestAGS Server
Test Web Server

Production:
ProductionAGS Server
ProductionWebA Server
ProductionWebB Server

To promote Test to production, here is what we're planning:
1. Create a ticket requesting 2 clones (webA and webB) of the TestWebServer
2. Create a ticket requesting a new AGS server (name: ags-yyyymmdd) that we'll configure once ready.
3. SS team Manually (using scripts) configures the ags-yyyymmdd server
4. Update application on Test Web Server to point to new ags-yyyymmdd & test ags-yyyymmdd if fail go back to step 2.
5. Resize TestAGS Server (but don't rename) to make it ready to handle prod traffic.
6. Update the load balancer on production to point to the new webA, webB. Production system should now be webA, webB, TestAGS Server
7. Backup and Release old ProductionWebA & ProductionWebB servers.

Future updates the naming convention of ags-yyyymmdd should be better following these same steps (because this first time we're going to have "TestAGS" be the prod map server).

That's the plan in a nutshell. @jknewson @marsmith can review to ensure I didn't mess it up.

**Comment by HansVraga** [comment]
One thing I'm noticing typing this plan up is that we don't have a method to introduce server patching into it. TestWeb is always the copy for the clone. How do we fix that?

**Comment by aaronstephenson** [comment]
So step 2 is to create a new test AGS server?

By the way, you can give an EC2 instance a new name and it doesn't affect anything within that instance. The instance name has no connection to the "Computer Name" ("host name") within the OS. So TestAGS should be renamed ProdAGS, but its Computer Name will remain the same.

Overall this plan works. It would be much better to do this all through automated promotion using scripts, but I guess we just don't have time for that right now.

**Comment by marsmith** [comment]
@aaronstephenson we're thinking specifically of the issues we had with Web Adaptor last go around.  There was indeed some issue with the computer  'host' name.

The reason the configuration is complicated at all is because we learned last time that AGS instances can't be cloned.  so TestWeb --> Prodweb1 & 2 is fine.  But we're thinking test-gis will have to stay test-gis but will act as ProdAGS.   

Then the new TestAGS server will be named with a convention that would more intelligently NOT link it to 'prod' or 'test' so it can be promoted.  Does that make sense? I'd like your input on this

**Comment by aaronstephenson** [comment]
Yes, the web adaptor does seem to have some kind of problem with changing of host names. But that's not what I'm saying. I'm just saying that EC2 instance name (what you see in the web console) != host name (what you see when you're RDP'd onto the server).

**Comment by marsmith** [comment]
Yea I think Hans' original text is mashing 'host' name with ec2 console name a bit. 

The second part of my last comment though. Better hostnames for the AGS instances

**Comment by marsmith** [comment]
Thinking about this a bit more I think the 'host' names are probably all fine as whatever the random string amazon gives them?  Then we just organize with names in AWS console?

**Comment by HansVraga** [comment]
I didn't realize we could disconnect the AWS console name from the hostname! That makes things a little easier - we should be able to accurately rename the test AGS once it's prod on this first step, and if we pick a scheme like we've outlined it should be easier to understand what's going on going forward.

**Comment by HansVraga** [comment]
Also @aaronstephenson I agree this should be scripted as much as possible, and I think we'll get there over time.

Thoughts on my issue with server patching the Web EC2s?

**Comment by aaronstephenson** [comment]
Yeah, I think the auto-assigned names will be fine. We're past the point where you had to monkey-patch host names into the app, right? (in other words, the load balancer works properly without hacks?).

@HansVraga re: patching, we should really have these three prod servers managed by GTRI, and they should take care of patching, et al.

**Comment by jknewson** [comment]
I'm closing this issue, Since I think we have it documented [here](https://docs.google.com/document/d/1o9JxnmhEVYt5kboPo5EDFTdrFIznoTnqcSIpeqBN0eM/edit#heading=h.2lh0we843tu8)
