### ISSUE TITLE
Report only prints first page in MS EDGE

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#893]
I've verified that this issue is valid, however from my quick google searching it appears that there is an open ticket with MS and no work around is available yet.. Then again, the thread is from a few Years ago.. but its still unresolved
https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/print-webpage-from-windows-edge/0837652f-c05f-4ce8-8eff-081fe1354ab4

although question was last updated Dec 29,2017

**Comment by harper-wavra** [comment]
Newest version of edge does not have this problem.
