### ISSUE TITLE
Temp Warning for SC

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#898]
To address the data available for SC that hasn't been yet approved for release, these actions have been taken:

- [ ] A News article has been created warning users

- [ ] "News" now opens every time the interface is opened

- [ ] a note has been added to the report

These actions (minus the news article) will be 'undone' once the next push to prod happens, this issue is just to document they happened and account for any issues that may crop up due to the nature of this temp fix.

**Comment by jknewson** [comment]
I assume this has been worked out? or at least out of date? - reopen if not.
