### ISSUE TITLE
About Popup -> Contact Us -> Message Text Window Horizontal sizing

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#90]
What I would call a low-priority bug is attached. The text field in Chrome / Windows 8 can be expanded beyond the border of the 'about' popup horizontally. Vertical resizing resizes the popup appropriately. 
A couple ways to address this: not allow resizing. resize the entire 'about' popup with the text field. limit the resizing of the popup horizontally.

**Comment by HansVraga** [comment]
<img width="995" alt="sillyresizing" src="https://cloud.githubusercontent.com/assets/12058013/10058798/5c74a6e8-6215-11e5-8ab0-241ba0d27755.PNG">

**Comment by marsmith** [comment]
I'm going to close this since I've re-worked the 'contact us' modal.  let me know if there is still a formatting issue
