### ISSUE TITLE
Review Freshdesk Integration for styling

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#904]
If possible, enforce the content pulled in from Freshdesk to follow the styling of the StreamStats client. May need a review of the Freskdesk API and our implementation. See below for screenshot showing how different styling of the content looks a bit janky on the site.
Tangentially related to #807

**Comment by HansVraga** [comment]
![image](https://user-images.githubusercontent.com/12058013/38163140-cb68f46a-34bc-11e8-91c9-82c35ad87d8f.png)

**Comment by kjacobsen16** [comment]
fixed

**Comment by HansVraga** [comment]
If this is available in Test, still have a couple issues:

![image](https://user-images.githubusercontent.com/12058013/38518628-72144800-3c0b-11e8-958b-83712fce3181.png)

![image](https://user-images.githubusercontent.com/12058013/38518651-7d12685e-3c0b-11e8-8fbf-0a860e4e0086.png)

**Comment by kjacobsen16** [comment]
fixed styling, but other issues may come from freshdesk -- will need to fix manually or educate the team about how it's integrated
