### ISSUE TITLE
Navigation not working in IE

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#906]
In typical manor, IE is throwing an error when selecting a navigation tool.
... Object doesn't support property or method 'includes'. 
![image](https://user-images.githubusercontent.com/8713714/38208664-0fe0d17c-366f-11e8-8222-1c4464286b8a.png)

https://github.com/USGS-WiM/StreamStats/blob/staging/src/Services/ExplorationService.ts#L250

probably need to switch to indexOf
`... (item.valueType.toLowerCase().indexOf(text) >= 0) ...`

**Comment by jknewson** [comment]
looks like it exists [here](https://github.com/USGS-WiM/StreamStats/blob/21ee5590d85104f384541a64125e44640ff8a0ba/src/Models/NetworkNavModels.ts#L104) as well

**Comment by kjacobsen16** [comment]
fixed
