### ISSUE TITLE
Get ready for another Test -> Prod migration

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#908]
We'll know more tomorrow, but we are planning a migration for early next week. Follow the document outlined [Here](https://docs.google.com/document/d/1o9JxnmhEVYt5kboPo5EDFTdrFIznoTnqcSIpeqBN0eM/edit#heading=h.2lh0we843tu8) 

Migration checklist:
- [x] 1) Snapshot existing TestWeb
- [x] 2a) Create 2 ProdWeb(a&b)-new EC2 instances from TestWebSnapshot
- [x] 2b) Create new TestAGS machine
- No need to create a new TestAGS instance... we never switched to the new one last time
- [x] 3) Update config files on prod services
- [x] 4) test the AGS desktop licenses on 2 prod webservers
- [x] 5) Point prod load balancer to new prod machines
- [x] 6) Embiggen TestAGS (to m4.xlarge) and rename to ProdAGS
-  this is already done since we never switched over to new gis machine last time
- [x] 7) Terminate old ProdAGS machines
-  No need to do this since we never switched over to new gis machine last time
- [x] 8) Run GIS script to build new testGIS machine
-  this is already done since we never switched over to new gis machine last time
- [ ] 9) Terminate old ProdWebA, ProdWebB machines and their attached data volumes (the 3600GB data drives)

**Comment by jknewson** [comment]
I'm thinking Wednesday is the day for migration. @aaronstephenson, One thing we need to identify is how we can be sure the file geodatabases (.gdb) folders do a complete rewrite rather than sync... The sync tends to corrupt the folder leading to delineation issues and other miscalculations. If that means we 🔪 the volumes and image them completely, I'm ok with it,but we probably need to kick it off early so we are ready for Wend.

**Comment by aaronstephenson** [comment]
Can't do it, on a trip all day that day for the LIDE project.

For the files, just do a copy, not a sync:
`aws s3 cp s3://mybucket . --recursive`

It will take a lot longer, but will be complete and intact.

**Comment by jknewson** [comment]
OK, @aaronstephenson lets plan on Friday.. I'm ok with doing the cp command, however we should probably kick it off Thurs night so its all ready for us on Friday.

**Comment by jknewson** [comment]
closing because its out of date -- and probably finished
