### ISSUE TITLE
report Disclaimer format

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#909]
Few questions regarding disclaimer format:
1) margins seem too big
2) do we really need to ref the web application opensource proj in the report.. seems like this should only be in the about window and maybe have the application (and services used) version in the report??

![image](https://user-images.githubusercontent.com/8713714/38385975-90975b8e-38d0-11e8-877c-45e6f1f7597e.png)

**Comment by kjacobsen16** [comment]
fixed
