### ISSUE TITLE
Specific warning messages in exclusion poly query

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#911]
there should be a message somewhere either in the output report or the geodatabase saying "CAUTION: SEE FEASTER AND OTHERS 2009."

![image](https://user-images.githubusercontent.com/8713714/38735233-737ac084-3ee5-11e8-8a33-94b9b5f33f92.png)
see ticket: https://streamstats.freshdesk.com/a/tickets/110067

**Comment by marsmith** [comment]
I fixed this one
