### ISSUE TITLE
Select all basin characteristics requires several clicks to select all (after initial selection)

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#925]
Steps to reproduce

1. Delineate watershed
2. select all characteristics button
3. unselect a few characteristics
4. click continue 
5. once computed, return to scenario tab and select all basin characteristics button again

As noted in the[ Freshdesk ticket](https://streamstats.freshdesk.com/a/tickets/110737), this is a low priority, and seems to be a pretty limited use case to reproduce.

**Comment by kjacobsen16** [comment]
done (see test)
