### ISSUE TITLE
Duplicate information in gage pop-up

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#928]
Streamgage pop-up information appears to be duplicated - see screenshot for example. 
![image](https://user-images.githubusercontent.com/12058013/42474863-7c568de4-838e-11e8-9b90-e2c8133c1cea.png)

**Comment by jknewson** [comment]
It's most likely due to multiple points on top of each other, rather than duplicate info... Should/would be fixed w/ gages services

**Comment by marsmith** [comment]
yes, duplicate points in shapefile we have.  what jeremy said ^

**Comment by jknewson** [comment]
Closing because this is a mapservice issue, and will be addressed with new gageservices.
