### ISSUE TITLE
Prosper layers remain after Exploration tools are closed

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#932]
I don't  think the layer should remain if we close the Exploration tools?
![image](https://user-images.githubusercontent.com/12058013/43329631-f0f45074-918e-11e8-938d-2ba6038c7ce9.png)

**Comment by jknewson** [comment]
This was by design, to allow tool to be closed for better viewing of the map/layers
to turn off layers, the prosper button needs to be toggled off (by selecting the prosper button again)
