### ISSUE TITLE
Different Download options in sidebar and report - why?

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#941]
Currently in the test environment we have this for a download option in the report:
![image](https://user-images.githubusercontent.com/12058013/44595831-463bec80-a798-11e8-80d1-d717ba5c6e68.png)

and this in the sidebar:
![image](https://user-images.githubusercontent.com/12058013/44595860-5b188000-a798-11e8-8f60-f66cf1094ec2.png)

Why the different lists? (CSV being the difference here). Should they be the same?

**Comment by jknewson** [comment]
The csv is for the report. Geojson and shapefile are for the watershed and point specifically. Which is why CSV is on the report and not in sidebar.
