### ISSUE TITLE
update Google Analtyics Event for Point Query

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#944]
- [x] Update GA hook

- [ ] Update Report

This fires right now whenever someone clicks the map, catching stray clicks not intended to query a point.

https://github.com/USGS-WiM/StreamStats/blob/staging/src/Controllers/MapController.ts#L504

Let's move it so it only fires when something is found.
We should also update the StreamStats report to capture point queries - currently broken in the report emailed daily.

**Comment by jknewson** [comment]
Updated GA eventtrack to fire when gage is found (Note: if there are duplicate gages under point this will fire twice) 
also added analytics to fire for all point queries.

see lines 547 and 557 in mapController.

**Comment by kjacobsen16** [comment]
@HansVraga I'm looking through old issues. Is the daily report still an issue? Also, what is the daily report?

**Comment by kjacobsen16** [comment]
report no longer needed, closing
