### ISSUE TITLE
Add St. Louis StormWater Functions to Production

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#946]
- [ ] Move Data

- [ ] Enable St. Louis Region

- [ ] Add additional Disclaimer language to report - will be added to this issue when approved

**Comment by HansVraga** [comment]
Disclaimer language:
`The Storm Drain methods are being provided to meet the need for timely best science and are released on the condition that neither the USGS nor the U.S. Government may be held liable for any damages resulting from authorized or unauthorized use. At his time these methods are provisional and are subject to revision until thoroughly reviewed and approved.
`

**Comment by jknewson** [comment]
are we thinking this is a general disclaimer and should go in section 1 or an additional disclaimer that should reside in section 2 (see image)?  I'm leaning to section 2
![image](https://user-images.githubusercontent.com/8713714/46736061-3e0b1400-cc55-11e8-8323-960c9f14fe78.png)

**Comment by HansVraga** [comment]
Well it only applies to when the user is leveraging the storm drain stuff - and would go away after these methods go for USGS review. I think it should be in #1 because of it's nature.

**Comment by jknewson** [comment]
we can make disclaimers show/hide were ever they are located. My only thought on section 2 is because of the similar verbiage statements, either one works

**Comment by HansVraga** [comment]
Oh, if the show/hide functionality is already in place for #2 - I'm OK with it there.

**Comment by jknewson** [comment]
Done 
![image](https://user-images.githubusercontent.com/8713714/49102032-efc9c880-f234-11e8-9db6-01c6a2f0dd9b.png)
