### ISSUE TITLE
Ohio Water Use customization

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#947]
Put together implementation plan for Ohio Water Use customization.
Steps below:

> I read through your report and came up with the following workflow for the water use services. Can you please review these to make sure I've correctly captured the workflow as well as have the correct math for computing the water-use indices?
> 
> 
> The following workflow assumes that a user has already delineated the basin, and the current StreamStats functionality has queried and returned the water-use data (see screen capture below for the same site used in the report; note that the StreamStats report no longer returns zeros when there is no data and if there is no data does not return the column): 
> 
> 1. Obtain the total withdrawals (W) and total returns (R) from the current functionality.
> 2. Compute the total net withdrawal (Wn) where Wn=W-R and are also defined as the consumptive water uses.
> 3. Use the basin delineation and filegeodatabase for temporary registrations to compute and return:
>         3a: Temporary water-use registrations for surface water
>         3b: Temporary water-use registrations for groundwater
>         3c: Total water-use registrations (Rt) which is 3a + 3b
> 4. Use the basin delineation to query the basin characteristics services and flow stats services to solve for the mean October streamflow (Q10) 
> 5. Use data above and equations from 1&2 in the report to compute 
>        5a: water-use index without temporary registrations: I=Wn/(Q10 * 0.6463)
>        5b: water-use index with temporary registrations It=(Wn+Rt)/(Q10 * 0.6463)
> 6. Report values from steps 3, 4, and 5 to the Water Use report.

**Comment by jknewson** [comment]
I don't think there is much work to do here, and I'm thinking this could be all client side option. 
step 3 is a bit confusing because there is not temporary registrations in the gdb. I think the allocations were just computed based on the permits and October flows
Here is line 1625 of from his code 
`WUNdxWihTempAlloc As Double = Math.Round((((Me.wUse.PermittedTotalGWWithdrawal.value + Me.wUse.PermittedTotalSWWithdrawal.value) / TotalYears) + totNWDAvr) / lowFlowStat, 5)`

**Comment by kjacobsen16** [comment]
Looking through the ticket [here](https://streamstats.freshdesk.com/a/tickets/110165), there was an additional problem that seems to still exist:
>Finally, the current application permits downloading of facility-specific information. The facility-specific information was never intended to be available to the public. 

I believe this is referring to the "Source CSV" download, which means it should be removed
![image](https://user-images.githubusercontent.com/35497731/90161349-9c751200-dd58-11ea-9a2c-eb120bd1a48c.png)

**Comment by jknewson** [comment]
source csv was a requirement for other state WU. In order to run some sort of models (or something). It may not have been intended for OH, but it is for other implementations

**Comment by kjacobsen16** [comment]
@jknewson digging into this more. I thought it was weird that the image in the SIR had the registrations properties etc. if it wasn't in SS
![image](https://user-images.githubusercontent.com/35497731/90179249-c63b3280-dd72-11ea-8745-b5345d6c40ca.png)

Then I found this https://github.com/USGS-WiM/StreamStats/blob/dev/src/Controllers/WateruseController.ts#L305-L312, which has some code in for that, but I don't see the "TotalTempStats" anywhere in the wu services. Does this sound familiar at all?

**Comment by jknewson** [comment]
So there is a long history behind wateruse. Short being. 
1) I wrote a component for wateruse for delaware basin
2) OH asked for the implementation w/ some added changes
3) we didn't have time so we had OH fork our project code and build in their added components, with the idea that we would merge them in later
4) what we got back was 🗑️ so we wouldn't (couldn't,... did I say it was 🗑️ ) merge it back in, lots of duplication of code, loops, etc. 
5) Kernal told us we had to serve what they gave us so we served it as a separate project until we hand time to refactor and bring in their changes
6) we started brining in the components and left some out... hoping they would go away

This was all pre-github, so it really wasn't merging/forking... but equivalent

I'm guessing totaltempstats was one of the looped global variables that was in one of his files. I'd have to go back and look at my notes for more info

**Comment by kjacobsen16** [comment]
Oh wow, ok. Well shoot, I saw that and was hoping the code was all there, just needed to get hooked up or something.

Did they do work with the services then too? I feel like this had to be working at some point for them to have it all in here/displayed in that image, but we'll have to weigh out time digging back through that v. setting it up ourselves.

**Comment by amedenblik** [comment]
This was fixed
