### ISSUE TITLE
Water-Use Display issue

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#949]
From cooperator
>...it looks like as the list of water use categories wraps it overlaps with the January bar graph (screen capture below).

![image](https://user-images.githubusercontent.com/12058013/47922889-7c7ba380-de8e-11e8-891c-4136753a918d.png)

**Comment by kjacobsen16** [comment]
Also issue with formatting when value is 0:
![image](https://user-images.githubusercontent.com/35497731/49113657-bbb5ce00-f25b-11e8-9173-07ca978868a7.png)

**Comment by kjacobsen16** [comment]
done
