### ISSUE TITLE
Printing the user manual from streamstats application

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#951]
A user just requested that we have a print button available for the User Manual that is available via the help button in Version 4. The user noted (and I confirmed that in both IE and Chrome) that expanding the sections of the manual and trying to print via the browser menu seems to just result in blank pages, or pages with only a heading. I referred the user to our .pdf user document available elsewhere

See [Fresh desk ticket] (Ticket URL:
https://streamstats.freshdesk.com/helpdesk/tickets/112228 )

**Comment by HansVraga** [comment]
Couple of quick thoughts:
Maintaining a .pdf might be a mistake - the content is already outdated (refers to application as 'beta'): http://water.usgs.gov/osw/streamstats/Version4UserInstructions-20160321.pdf

Further the FAQ where this is listed is dated as well, it still mentions Version 3.

I think the best solution would be to retire these PDFs and offer a link at the top of the User Manual section to open (in a new tab) all of the Help content, which from there a user could print.

**Comment by amedenblik** [comment]
User manual has moved to https://www.usgs.gov/streamstats/how-guides

Recommend `wontfix`
