### ISSUE TITLE
PROSPER SPP layer refresh

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#955]
Rebuild Prosper SPP layer query to handle a list of SPP maplayers from Sciencebase, given selected date

Service 2004 -2011 https://gis.usgs.gov/sciencebase2/rest/services/Catalog/5b895182e4b0702d0e7cd017/MapServer

Service 2012-2016
https://gis.usgs.gov/sciencebase2/rest/services/Catalog/5b8958a1e4b0702d0e7cd03c/MapServer

**Comment by kjacobsen16** [comment]
done
