### ISSUE TITLE
Update traffic routing rules for streamstats.usgs.gov

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#964]
Currently traffic pointed to the root of www.streamstats.usgs.gov ends up at https://water.usgs.gov/osw/streamstats/ .

There is a new site in Drupal that we should now point to:

https://www.usgs.gov/mission-areas/water-resources/science/streamstats

**Comment by HansVraga** [comment]
@jknewson want to run this by you before I add it to the infrastructure task list

**Comment by jknewson** [comment]
Done.
