### ISSUE TITLE
Prosper Typo fixes

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#970]
Proofread the Prosper text for spacing issues.

From cooperator:
>he project description appears to be missing some spaces between words. See below.

> The PRObability of Streamflow PERmanence (PROSPER) model provides annual (2004-2016)streamflow permanence probabilities (SPPs; probabilistic predictions) and streamflow permanenceclasses(SPCs; categorical wet/ dry with an associated confidence level). Probabilities are of a streamchannel having year- round flow at a 30- m spatial resolution.Model methods, output, and appropriateuses are detailed in Jaeger et al. (2018).Interpretation of a pixel as wet or dry will be based oncombined consideration of the SPP, the sign of the SPC (negative for dry, positive for wet), and theassociated confidence (1 - 5 representing 50% - 95 %).For example, predictions with a negative(positive) sign, high confidence level indicated by an SPC of - 5(5), and an SPP of less than (greaterthan) 0.5 will be the most reliable. Click here for more information.

**Comment by kjacobsen16** [comment]
done
