### ISSUE TITLE
Gages are plotting under exclusion polys

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#972]
Can we plot the gages on top of the other layers? Exclusion polys are getting plotted on top of gages and they are difficult to see.
-- request from pete

**Comment by marsmith** [comment]
Fix didnt work look at this again

**Comment by HansVraga** [comment]
Current workaround available - toggle layer display here to reveal the underlying gages:
![image](https://user-images.githubusercontent.com/12058013/86163139-701d7300-bad5-11ea-84a5-5646c90b56f3.png)
![image](https://user-images.githubusercontent.com/12058013/86163183-80cde900-bad5-11ea-83e7-c2f480686851.png)
