### ISSUE TITLE
Setup a new StreamStats test-EC2 instance (to replace the older one)

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#973]
We are just about ready for a new "updated" EC2 test instance, Same specs as previous Test (Windows Server but with updated arc 10.6 desktop, 100GB C:\ drive, 100GB (system drive), D:\ drive (arcgis temp and client data temp space), and a much smaller attached volume. I'm thinking 1.85 TB???? (could probably get away with smaller). Attached is the space we are now using thanks to Katrin's data cleaning scripts:
![image](https://user-images.githubusercontent.com/8713714/53740566-b74c1300-3e51-11e9-9ca4-a45151033b0b.png)

**Comment by aaronstephenson** [comment]
@DanielJBeckman this would be a good one for us to work on together, to give you some more experience  with Windows server provisioning.

**Comment by aaronstephenson** [comment]
@jknewson is Windows Server 2016 ok with you, or so you want to try the new 2019? The current test server is 2012 R2.

**Comment by jknewson** [comment]
latest 2019 is ok with me.

**Comment by jknewson** [comment]
@aaronstephenson @DanielJBeckman. The SS coordinator asked for status, I told him, probably beginning of next week, Was that a fair assessment?

**Comment by aaronstephenson** [comment]
Yes, I can definitely have it to you before then. @DanielJBeckman are you available today to work on this with me?

**Comment by aaronstephenson** [comment]
Done! IP address and Administrator creds are in the WIM keepass DB. I have not assigned a DNS record to it yet, though, so let me know when you want to do that; we could reassign the current test FQDN or create a new one.

**Comment by jknewson** [comment]
Great thanks, I'll dive in and let you know. and yes probably just use old test when we are ready. 👍

**Comment by jknewson** [comment]
@aaronstephenson @DanielJBeckman  There seems to be an issue with the ssl cert, I tried export/import from the old testweb w/o any success. I tried swapping out the elastic IP's but when I did it through a cert error, 
There was a .wim.usgs.gov cert in there, so I removed it and tried to add one that I exported from the other test machine, but it didn't work, so I removed it.

**Comment by aaronstephenson** [comment]
Ah, I see what happened, I installed the WIM star cert when I should have installed the Streamstats star cert. Sorry about that.

So, it looks like you installed the Streamstats star cert fine, but forgot to bind it to the Default website's port 443, so I did that. It should work as expected now.
