### ISSUE TITLE
Rebuild "shaded" layer 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#980]
Rebuild "shaded" layer to avoid shading regions outside US with Streamstats availability.

**Comment by HansVraga** [comment]
I think @esmyers has some time available this FY - we'll see if he's up for this.

**Comment by jknewson** [comment]
preferably a tilemap, I'm trying to pull away from mapservices, we only have a few on there now, and removing more going forward.
I remember Marty talking about serving them from s3??? could be cool

**Comment by HansVraga** [comment]
Should we grey out TX or other states not implemented?

**Comment by jknewson** [comment]
No, I think that could get messy. I would recommend just opening up the shaded area that we've included, ie. Rainy river basin. 
SS already has a map of applicability on the FAQ/documentation page

**Comment by esmyers** [comment]
Do you have a polygon area of the data I can pass on to Lorraine for GIS processing?  Is it just Continental U.S. and Rainy river basin?

**Comment by jknewson** [comment]
Yep, essentially just the gray layer from [streamstats ](https://test.streamstats.usgs.gov/ss/) with the RRB cut out (include shapefile is the exclusion poly, just need to reverse it)
the gray layer is being pulled as a mapservice from tx, so we could get the data from them, or just make our own.
[RRBexcludepolys.zip](https://github.com/USGS-WiM/StreamStats/files/3291795/RRBexcludepolys.zip)

**Comment by esmyers** [comment]
Do you want to use the layer with the buffer on it?  Or do you have a polygon that is just the basin outline?

![image](https://user-images.githubusercontent.com/2495167/59533902-70d76d00-8eb2-11e9-8969-2048a9b6c9e4.png)

**Comment by jknewson** [comment]
The shapefile indicates the area of interest (inside of the polygon). What we need is the area inside of the polygon clippped out of the gray overview map shown with yellow hashmarks on image

![image](https://user-images.githubusercontent.com/8713714/59534620-15a27c00-8eac-11e9-9b0c-9fde60d52023.png)
Currently we are using tx tiled [mapservice ](https://txgeo.usgs.gov/arcgis/rest/services/Mapping/Mask/MapServer)
So we will need to make one equivalent (but hopefully tiles) -->maybe even served from s3??? that has the area clipped.

**Comment by esmyers** [comment]
Ok that's what I figured.  But the one you sent has the buffer added, so I was just wondering if you have a Rainy river polygon without it.  If not, I can make one.

**Comment by jknewson** [comment]
no unfortunately, that is all I have,

**Comment by esmyers** [comment]
Just an update to this.  I created a non-buffered shapefile for that area.  I sent it all to Lorraine who will do the work to create the layer.  I'll check in with her early next week at the latest so see how it's going.

**Comment by HansVraga** [comment]
@esmyers did you get a chance to check in with Lorraine?

**Comment by kjacobsen16** [comment]
@esmyers are there any updates on this? I'm just getting myself reoriented with the project, so sorry if this is documented elsewhere!

**Comment by marsmith** [comment]
if anyone needs help on this we can do a call.. im out for about next hour and a half

**Comment by esmyers** [comment]
I swear she put this together awhile back.  I'll have a look around for it.

**Comment by kjacobsen16** [comment]
done (see test)
