### ISSUE TITLE
Add Toast Notification when simplifying Basin

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#981]
Add toast notification when performing simplification to more easily render basin.

Text:
>Displaying simplified Basin, see FAQ for more information.

**Comment by jknewson** [comment]
I can take this one, its pretty straight forward

**Comment by HansVraga** [comment]
Fired off a quick email to Pete and Jeremy on the language.

**Comment by jknewson** [comment]
too late already done.. pushing changes now :)
