### ISSUE TITLE
Need a new Prod NSSV2 RDS

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#983]
Will one of you spin up a new empty RDS equivalent to test
(test | Instance | PostgreSQL | us-east-1a | db.t2.medium)
Name could be NSS_V2 (or something like that) It will eventually replace the mariadb stuff

**Comment by aaronstephenson** [comment]
@DanielJBeckman do you want to take this one?

**Comment by DanielJBeckman** [comment]
I can get it.

**Comment by DanielJBeckman** [comment]
AWS name is NSS-V2 (Can't use '_' character)~~
Database name is NSS_V2
~~Username is NSS_V2admin~~

**Comment by aaronstephenson** [comment]
@jknewson any particular reason you want a medium? It would be $55.59/mo as opposed to ~$14 for a micro.

**Comment by jknewson** [comment]
We had micro before, but the spatial analysis dogged it down, we could try it at micro again, see how it reacts

**Comment by aaronstephenson** [comment]
There's a small in between, do you want to try that?

Also, @DanielJBeckman it looks like there's a new t3 series which has better resources and is a tiny bit cheaper, let's use that instead of the t3 series.

**Comment by jknewson** [comment]
yep, that is fine

**Comment by DanielJBeckman** [comment]
Ok. Everything build ok accept that the console froze at this step:

"We have generated your database master password during the database creation and will be displayed in the connection details. This is the only time you will be able to view this password. However you can modify your database to create a new password at any time."

So, I have rebuild it anyways because I can't get the login data.

**Comment by DanielJBeckman** [comment]
Ok. All done.
name is nss_v2
endpoint is nss-v2.c69uuui2tzs0.us-east-1.rds.amazonaws.com
username /password updated in keypass

**Comment by jknewson** [comment]
Its all good, thanks

**Comment by DanielJBeckman** [comment]
```diff
+ WIM SysOps attacks ticket #983 for 42 damage. pew pew pew.  
- ticket #983 has died.
```
