### ISSUE TITLE
Add Streamstats test to the shutdown script

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#985]
StreamStats subaccount.

Please put TestWeb_20190315 

[Instance ID i-096504e3845291262 ]

in the shutdown script

**Comment by HansVraga** [comment]
@jknewson reports that this is already in the sandbox stop ec2 instances text file but it doesn't appear to be shutting down every night.

**Comment by DanielJBeckman** [comment]
The Lambda script is not working. Like it was shut off.

**Comment by DanielJBeckman** [comment]
On closer examination it looks like the execution task is working and logging in cloudwatch but lambda says nothing happened. I need to test the function. **This will shutdown: ProdWebB_Aug, and TestWeb_20190315**

**Comment by kjacobsen16** [comment]
@aaronstephenson it doesn't seem to be working. I was able to run a script on the test server after hours. Can you confirm what time it should shutdown, or point me to where I can check it myself? It doesn't look like I have full access to the SS lambda, but I'm also a noob.

**Comment by aaronstephenson** [comment]
Looks like the lambda trigger was disabled.
![image](https://user-images.githubusercontent.com/8713712/71852966-b7372800-309f-11ea-8c07-c55630b47670.png)


I re-enabled it. Let me know how it goes.

**Comment by kjacobsen16** [comment]
Looks like it worked, thanks!
