### ISSUE TITLE
Edit basin issues

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#986]
... The basin characteristics do not update after I have edited a basin.

... This also happened for a test basin I delineated at 46.89073, -122.15322. Perhaps the issues are related, but when I clicked the "Undo Edits" button, it didn't seem to work (the parts of the basin I removed didn't come back).

**Comment by jknewson** [comment]
comment from Pete:
>I just edited a basin in StreamStats and submitted it to compute new basin characteristics. The basin returned with the same characteristics I had computed pre-edit. I'll keep looking into this, but it appears to be a bug.

**Comment by HansVraga** [comment]
Doing a quick check, looks like I'm getting different BC numbers at the same delineation point if you edit without continuing. So I think this is just an order of operations issue.
I think the easiest way to prevent misunderstanding here is to grey out the edit button once a user clicks 'continue'

**Comment by marsmith** [comment]
I think I fixed this with refactor to turfjs for polygon union and subtract operations used in editing.  That, in addition to remove small single cell polygon slivers before start of edit.

**Comment by marsmith** [comment]
Needs to be tested, on test

**Comment by HansVraga** [comment]
Feedback from testing: 
>I would like to see a toast message after the basin has been edited and submitted  that lets us know the new basin perimeter is being computed. The process is kind of slow and made me think the client had timed out.

can create this as a separate issue if it shouldn't be tackled as part of this effort.

**Comment by harper-wavra** [comment]
Created new issue #1018 to address testing feedback.
